# **Fine-Tuning W2V2-Bert for Maltese ASR**

*The following notebook is an adaptation of https://huggingface.co/blog/fine-tune-w2v2-bert*

## Notebook Setup

In [1]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Wed Apr 29 10:28:06 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 590.57                 Driver Version: 591.86         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3080        On  |   00000000:07:00.0  On |                  N/A |
|  0%   41C    P8             24W /  370W |    1124MiB /  10240MiB |     35%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A              32      G   /Xwayland                             N/A      |
+-----------------------------------------------------------------------------------------+

Before we start, let's install `datasets` and `transformers`. Also, we need `accelerate` for training, `torchaudio` to load audio files and `jiwer` to evaluate our fine-tuned model using the [word error rate (WER)](https://huggingface.co/metrics/wer) metric ${}^1$.

In [ ]:
# %%capture
# !pip install datasets
# !pip install transformers
# !pip install torchaudio
# !pip install jiwer
# !pip install accelerate -U

In [2]:
import torch

In [3]:
print(f"CUDA Available: {torch.cuda.is_available()}")
print(f"Using GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'NONE'}")
print(f"Torch Version: {torch.__version__}")

CUDA Available: True
Using GPU: NVIDIA GeForce RTX 3080
Torch Version: 2.8.0+cu126

## Prepare Data, Tokenizer, Feature Extractor

ASR models transcribe speech to text, which means that we both need a feature extractor that processes the speech signal to the model's input format, *e.g.* a feature vector, and a tokenizer that processes the model's output format to text.

In 🤗 Transformers, the Wav2Vec2-BERT model is thus accompanied by both a tokenizer, called [Wav2Vec2CTCTokenizer](https://huggingface.co/transformers/master/model_doc/wav2vec2.html#wav2vec2ctctokenizer), and a feature extractor, called [SeamlessM4TFeatureExtractor](https://huggingface.co/docs/transformers/v4.36.1/en/model_doc/seamless_m4t#transformers.SeamlessM4TFeatureExtractor) that the model shares with the [first](https://huggingface.co/docs/transformers/main/en/model_doc/seamless_m4t) and [second](https://huggingface.co/docs/transformers/main/en/model_doc/seamless_m4_v2t) versions of Seamless-M4T, as they all process audio in the same way.

Let's start by creating the tokenizer to decode the predicted output classes to the output transcription.

### Create `Wav2Vec2CTCTokenizer`

Remember that Wav2Vec2-like models fine-tuned on CTC transcribe an audio file with a single forward pass by first processing the audio input into a sequence of processed context representations and then using the final vocabulary output layer to classify each context representation to a character that represents the transcription.

The output size of this layer corresponds to the number of tokens in the vocabulary, and therefore only on the labeled dataset used for fine-tuning. So in the first step, we will take a look at the chosen dataset of Common Voice and define a vocabulary based on the transcriptions.

#### Combined Data Loading

In [1]:
import os
import pandas as pd
from pathlib import Path
from datasets import Dataset, concatenate_datasets

# --- Configuration ---
DATA_ROOT = Path.home() / "MalteseProject" / "Data"

def get_audio_path(root_dir, filename, is_nested=False):
    if not filename or filename == "None":
        return None
        
    root_dir = Path(root_dir)
    # Ensure filename has the .wav extension for searching
    search_name = filename if filename.lower().endswith(".wav") else f"{filename}.wav"
    
    if not is_nested:
        direct_path = root_dir / search_name
        return str(direct_path) if direct_path.exists() else None
    
    # Recursive search for MASRI (searching through gender/speaker folders)
    for p in root_dir.rglob(search_name):
        return str(p)
            
    return None

def process_subset(folder_path, source_type, subset_name):
    data_list = []
    folder_path = Path(folder_path)
    
    def safe_str(val):
        return str(val).strip() if pd.notna(val) else ""

    # --- 1 & 2: MASRI / CV (Train & Dev) ---
    if subset_name in ["Train", "Dev"]:
        if source_type == "MASRI":
            csv_name = "masriTrain.csv" if subset_name == "Train" else "masriDev.csv"
            df = pd.read_csv(folder_path / csv_name)
            audio_dir = folder_path / "audio files"
            is_nested = True
            sent_col, id_col = 'transcription_mt', 'filename' # Handle MASRI casing
            # Check if MASRI uses 'Filename' with capital F
            if id_col not in df.columns and 'Filename' in df.columns:
                id_col = 'Filename'
        else: # CV
            csv_name = "cvTrain.csv" if subset_name == "Train" else "cvDev.csv"
            df = pd.read_csv(folder_path / csv_name)
            audio_dir = folder_path / "audio files"
            is_nested = False
            sent_col, id_col = 'sentence_mt', 'filename'

        for _, row in df.iterrows():
            fname = safe_str(row[id_col])
            path = get_audio_path(audio_dir, fname, is_nested=is_nested)
            
            if path:
                data_list.append({
                    "path": path, 
                    "sentence_id": fname,
                    "sentence": safe_str(row[sent_col]), 
                    "sentence_domain": source_type, 
                    "variant": "MT", 
                    "audio": path
                })

    # --- 3: MASRI Test ---
    elif source_type == "MASRI" and subset_name == "Test":
        trans_path = folder_path / "transcription.trans"
        audio_dir = folder_path / "speech"
        
        if trans_path.exists():
            with open(trans_path, "r", encoding="utf-8") as f:
                for line in f:
                    parts = line.strip().split(" ", 1)
                    if len(parts) < 2: continue
                    file_id = parts[0]
                    fname = f"{file_id}.wav"
                    path = get_audio_path(audio_dir, fname, is_nested=True)
                    if path:
                        data_list.append({
                            "path": path, "sentence_id": file_id,
                            "sentence": safe_str(parts[1]), 
                            "sentence_domain": "MASRI", "variant": "MT", "audio": path
                        })

    # --- 4: CV Test ---
    elif source_type == "CV" and subset_name == "Test":
        csv_path = folder_path / "FileSequenceCV.csv"
        df = pd.read_csv(csv_path)
        audio_dir = folder_path / "speech"
        corr_col = "If MT-Sentence needs correction, put it here"
        
        for _, row in df.iterrows():
            # Use correction if it exists, else use standard 'sentence'
            final_sent = row[corr_col] if pd.notna(row[corr_col]) and str(row[corr_col]).strip() != "" else row['sentence']
            fname = safe_str(row['path'])
            path = get_audio_path(audio_dir, fname, is_nested=False)
            
            if path:
                data_list.append({
                    "path": path, "sentence_id": fname,
                    "sentence": safe_str(final_sent), 
                    "sentence_domain": "CommonVoice", "variant": "MT", "audio": path
                })

    return Dataset.from_list(data_list)

In [2]:
# --- Process Datasets ---
common_voice_train = concatenate_datasets([
    process_subset(f"{DATA_ROOT}/Train/MASRI Train Release 202501", "MASRI", "Train"),
    process_subset(f"{DATA_ROOT}/Train/CV Train Release 202501", "CV", "Train")
])

common_voice_dev = concatenate_datasets([
    process_subset(f"{DATA_ROOT}/Dev/MASRI Dev Release 202501", "MASRI", "Dev"),
    process_subset(f"{DATA_ROOT}/Dev/CV Dev Release 202501", "CV", "Dev")
])

common_voice_test = concatenate_datasets([
    process_subset(f"{DATA_ROOT}/Test/MASRI", "MASRI", "Test"),
    process_subset(f"{DATA_ROOT}/Test/CV", "CV", "Test")
])

In [3]:
# --- 5. Decode Audio ---
import librosa
import numpy as np

def decode_audio_batched(batch):
    # Process the whole batch in a list comprehension
    audio_data = []
    for path in batch["path"]:
        speech_array, _ = librosa.load(path, sr=16000)
        audio_data.append({
            "path": path,
            "array": np.array(speech_array, dtype=np.float32),
            "sampling_rate": 16000
        })
    batch["audio"] = audio_data
    return batch

# Applying the decoding to all three sets
common_voice_train = common_voice_train.map(decode_audio_batched, batched=True)
common_voice_dev = common_voice_dev.map(decode_audio_batched, batched=True)
common_voice_test = common_voice_test.map(decode_audio_batched, batched=True)

print(f"✅ Loaded and Decoded with Librosa! Train: {len(common_voice_train)} samples.")

Map:   0%|          | 0/8886 [00:00<?, ? examples/s]

Map:   0%|          | 0/1883 [00:00<?, ? examples/s]

Map:   0%|          | 0/1892 [00:00<?, ? examples/s]

✅ Loaded and Decoded with Librosa! Train: 8886 samples.

#### MASRI Only Loading

In [ ]:
import os
import pandas as pd
from pathlib import Path
from datasets import Dataset, concatenate_datasets
import librosa
import numpy as np

# --- Configuration ---
DATA_ROOT = Path.home() / "MalteseProject" / "Data"

def get_audio_path(root_dir, filename, is_nested=False):
    if not filename or filename == "None":
        return None
        
    root_dir = Path(root_dir)
    search_name = filename if filename.lower().endswith(".wav") else f"{filename}.wav"
    
    if not is_nested:
        direct_path = root_dir / search_name
        return str(direct_path) if direct_path.exists() else None
    
    for p in root_dir.rglob(search_name):
        return str(p)
            
    return None

def process_subset(folder_path, source_type, subset_name):
    data_list = []
    folder_path = Path(folder_path)
    
    def safe_str(val):
        return str(val).strip() if pd.notna(val) else ""

    # --- MASRI (Train & Dev) ---
    if subset_name in ["Train", "Dev"] and source_type == "MASRI":
        csv_name = "masriTrain.csv" if subset_name == "Train" else "masriDev.csv"
        df = pd.read_csv(folder_path / csv_name)
        audio_dir = folder_path / "audio files"
        is_nested = True
        sent_col, id_col = 'transcription_mt', 'filename'
        
        if id_col not in df.columns and 'Filename' in df.columns:
            id_col = 'Filename'

        for _, row in df.iterrows():
            fname = safe_str(row[id_col])
            path = get_audio_path(audio_dir, fname, is_nested=is_nested)
            
            if path:
                data_list.append({
                    "path": path, 
                    "sentence_id": fname,
                    "sentence": safe_str(row[sent_col]), 
                    "sentence_domain": source_type, 
                    "variant": "MT", 
                    "audio": path
                })

    # --- MASRI Test ---
    elif source_type == "MASRI" and subset_name == "Test":
        trans_path = folder_path / "transcription.trans"
        audio_dir = folder_path / "speech"
        
        if trans_path.exists():
            with open(trans_path, "r", encoding="utf-8") as f:
                for line in f:
                    parts = line.strip().split(" ", 1)
                    if len(parts) < 2: continue
                    file_id = parts[0]
                    fname = f"{file_id}.wav"
                    path = get_audio_path(audio_dir, fname, is_nested=True)
                    if path:
                        data_list.append({
                            "path": path, "sentence_id": file_id,
                            "sentence": safe_str(parts[1]), 
                            "sentence_domain": "MASRI", "variant": "MT", "audio": path
                        })

    return Dataset.from_list(data_list)

# --- Process Only MASRI Datasets ---
masri_train = process_subset(f"{DATA_ROOT}/Train/MASRI Train Release 202501", "MASRI", "Train")
masri_dev = process_subset(f"{DATA_ROOT}/Dev/MASRI Dev Release 202501", "MASRI", "Dev")
masri_test = process_subset(f"{DATA_ROOT}/Test/MASRI", "MASRI", "Test")

In [2]:
# --- Decode Audio ---
def decode_audio_batched(batch):
    audio_data = []
    for path in batch["path"]:
        speech_array, _ = librosa.load(path, sr=16000)
        audio_data.append({
            "path": path,
            "array": np.array(speech_array, dtype=np.float32),
            "sampling_rate": 16000
        })
    batch["audio"] = audio_data
    return batch

# Applying decoding (Note: names updated to masri_*)
masri_train = masri_train.map(decode_audio_batched, batched=True)
masri_dev = masri_dev.map(decode_audio_batched, batched=True)
masri_test = masri_test.map(decode_audio_batched, batched=True)

print(f"✅ Loaded MASRI! Train: {len(masri_train)}, Dev: {len(masri_dev)}, Test: {len(masri_test)}")

Map:   0%|          | 0/4963 [00:00<?, ? examples/s]

Map:   0%|          | 0/648 [00:00<?, ? examples/s]

Map:   0%|          | 0/668 [00:00<?, ? examples/s]

✅ Loaded MASRI! Train: 4963, Dev: 648, Test: 668

#### Common Voice Only Loading

In [1]:
import os
import pandas as pd
from pathlib import Path
from datasets import Dataset
import librosa
import numpy as np

# --- Configuration ---
DATA_ROOT = Path.home() / "MalteseProject" / "Data"

def get_audio_path(root_dir, filename, is_nested=False):
    if not filename or filename == "None":
        return None
    root_dir = Path(root_dir)
    search_name = filename if filename.lower().endswith(".wav") else f"{filename}.wav"
    
    if not is_nested:
        direct_path = root_dir / search_name
        return str(direct_path) if direct_path.exists() else None
    
    for p in root_dir.rglob(search_name):
        return str(p)
    return None

def process_cv_subset(folder_path, subset_name):
    data_list = []
    folder_path = Path(folder_path)
    
    def safe_str(val):
        return str(val).strip() if pd.notna(val) else ""

    # --- Train & Dev Logic ---
    if subset_name in ["Train", "Dev"]:
        csv_name = "cvTrain.csv" if subset_name == "Train" else "cvDev.csv"
        df = pd.read_csv(folder_path / csv_name)
        audio_dir = folder_path / "audio files"
        
        for _, row in df.iterrows():
            fname = safe_str(row['filename'])
            path = get_audio_path(audio_dir, fname, is_nested=False)
            if path:
                data_list.append({
                    "path": path, 
                    "sentence_id": fname,
                    "sentence": safe_str(row['sentence_mt']), 
                    "sentence_domain": "CommonVoice", 
                    "variant": "MT", 
                    "audio": path
                })

    # --- Test Logic (with Correction Column) ---
    elif subset_name == "Test":
        csv_path = folder_path / "FileSequenceCV.csv"
        df = pd.read_csv(csv_path)
        audio_dir = folder_path / "speech"
        corr_col = "If MT-Sentence needs correction, put it here"
        
        for _, row in df.iterrows():
            # logic: Use correction if it exists, otherwise use standard 'sentence'
            final_sent = row[corr_col] if pd.notna(row[corr_col]) and str(row[corr_col]).strip() != "" else row['sentence']
            fname = safe_str(row['path'])
            path = get_audio_path(audio_dir, fname, is_nested=False)
            
            if path:
                data_list.append({
                    "path": path, 
                    "sentence_id": fname,
                    "sentence": safe_str(final_sent), 
                    "sentence_domain": "CommonVoice", 
                    "variant": "MT", 
                    "audio": path
                })

    return Dataset.from_list(data_list)

# --- 1. Load the Splits Individually ---
# These are now kept as separate Dataset objects
common_voice_train = process_cv_subset(DATA_ROOT / "Train" / "CV Train Release 202501", "Train")
common_voice_dev = process_cv_subset(DATA_ROOT / "Dev" / "CV Dev Release 202501", "Dev")
common_voice_test = process_cv_subset(DATA_ROOT / "Test" / "CV", "Test")

# --- Verification ---
print(f"Train size: {len(common_voice_train)}")
print(f"Dev size: {len(common_voice_dev)}")
print(f"Test size: {len(common_voice_test)}")

Train size: 3923
Dev size: 1235
Test size: 1224

In [2]:
# --- 3. Decode Audio ---
def decode_audio(batch):
    # Note: Using librosa to match your target format
    speech_array, _ = librosa.load(batch["path"], sr=16000)
    batch["audio"] = {
        "path": batch["path"],
        "array": np.array(speech_array, dtype=np.float32),
        "sampling_rate": 16000
    }
    return batch

# Apply decoding (this processes one row at a time as per your old script)
common_voice_train = common_voice_train.map(decode_audio)
common_voice_test = common_voice_test.map(decode_audio)

print(f"✅ Loaded CV! Train+Dev: {len(common_voice_train)}, Test: {len(common_voice_test)}")

Map:   0%|          | 0/3923 [00:00<?, ? examples/s]

Map:   0%|          | 0/1224 [00:00<?, ? examples/s]

✅ Loaded CV! Train+Dev: 3923, Test: 1224

#### Utilities

In [6]:
def print_dataset_stats(dataset, name):
    total_utterances = len(dataset)
    # Extract the 'sentence' column and find unique entries
    unique_utterances = len(set(dataset["sentence"]))
    
    print(f"--- Statistics for {name} ---")
    print(f"Total Utterances:  {total_utterances}")
    print(f"Unique Sentences:  {unique_utterances}")
    if total_utterances > 0:
        print(f"Redundancy Ratio: {((total_utterances - unique_utterances) / total_utterances):.2%}")
    print("-" * 30)

# Usage
print_dataset_stats(common_voice_train, "Common Voice Train")
print_dataset_stats(common_voice_dev, "Common Voice Dev")
print_dataset_stats(common_voice_test, "Common Voice Test")

--- Statistics for Common Voice Train ---
Total Utterances:  3923
Unique Sentences:  3499
Redundancy Ratio: 10.81%
------------------------------
--- Statistics for Common Voice Dev ---
Total Utterances:  1235
Unique Sentences:  1195
Redundancy Ratio: 3.24%
------------------------------
--- Statistics for Common Voice Test ---
Total Utterances:  1224
Unique Sentences:  1176
Redundancy Ratio: 3.92%
------------------------------

In [ ]:
import librosa

def calculate_duration(dataset):
    # Sum up durations of all paths in the 'audio' column
    total_seconds = sum(librosa.get_duration(path=x) for x in dataset['audio'])
    
    total_hours = total_seconds / 3600
    print(f"Total Duration: {total_seconds:.2f} seconds")
    print(f"Total Duration: {total_hours:.2f} hours")
    
    return total_hours


calculate_duration(common_voice_test)

Total Duration: 5657.74 seconds
Total Duration: 1.57 hours

1.5715933333333323

In [2]:
def add_duration(example):
    # librosa.get_duration reads the header without loading the full waveform
    example["duration"] = librosa.get_duration(path=example["path"])
    return example

# Apply to your datasets
cv_train_with_duration = common_voice_train.map(add_duration)

# Calculate Average
avg_duration = np.mean(cv_train_with_duration["duration"])
print(f"Average Duration: {avg_duration:.2f} seconds")
print(f"Total Hours: {sum(cv_train_with_duration['duration']) / 3600:.2f}")

Map:   0%|          | 0/3923 [00:00<?, ? examples/s]

Average Duration: 4.76 seconds
Total Hours: 5.19

### Textual Preprocessing

Many ASR datasets only provide the target text, `'sentence'` for each audio array `'audio'` and file `'path'`. Common Voice actually provides much more information about each audio file, such as the `'accent'`, etc. Keeping the notebook as general as possible, we only consider the transcribed text for fine-tuning.

In [4]:
print(f"Current columns: {common_voice_train.column_names}")

Current columns: ['path', 'sentence_id', 'sentence', 'sentence_domain', 'variant', 'audio']

In [ ]:
common_voice_train = common_voice_train.remove_columns(["accents", "age", "client_id", "down_votes", "gender", "locale", "segment", "up_votes"])
common_voice_test = common_voice_test.remove_columns(["accents", "age", "client_id", "down_votes", "gender", "locale", "segment", "up_votes"])

Let's write a short function to display some random samples of the dataset and run it a couple of times to get a feeling for the transcriptions.

In [3]:
from datasets import ClassLabel
import random
import pandas as pd
from IPython.display import display, HTML

def show_random_elements(dataset, num_examples=10):
    assert num_examples <= len(dataset), "Can't pick more elements than there are in the dataset."
    picks = []
    for _ in range(num_examples):
        pick = random.randint(0, len(dataset)-1)
        while pick in picks:
            pick = random.randint(0, len(dataset)-1)
        picks.append(pick)

    df = pd.DataFrame(dataset[picks])
    display(HTML(df.to_html()))

In [4]:
show_random_elements(common_voice_train.remove_columns(["path", "audio"]), num_examples=10)

Alright! The transcriptions look fairly clean. Having translated the transcribed sentences, it seems that the language corresponds more to written-out text than noisy dialogue. This makes sense considering that [Common Voice](https://huggingface.co/datasets/mozilla-foundation/common_voice_16_0) is a crowd-sourced read speech corpus.

We can see that the transcriptions contain some special characters, such as `,.?!;:`. Without a language model, it is much harder to classify speech chunks to such special characters because they don't really correspond to a characteristic sound unit. *E.g.*, the letter `"s"` has a more or less clear sound, whereas the special character `"."` does not.
Also in order to understand the meaning of a speech signal, it is usually not necessary to include special characters in the transcription.

Let's simply remove all characters that don't contribute to the meaning of a word and cannot really be represented by an acoustic sound and normalize the text.

In [5]:
import re
chars_to_remove_regex = '[\,\?\.\!\;\:\"\“\%\‘\”\�\»\«]'

def remove_special_characters(batch):
    # remove special characters
    batch["sentence"] = re.sub(chars_to_remove_regex, '', batch["sentence"]).lower()

    return batch

In [6]:
common_voice_train = common_voice_train.map(remove_special_characters)
common_voice_test = common_voice_test.map(remove_special_characters)
common_voice_dev = common_voice_dev.map(remove_special_characters)

Map:   0%|          | 0/3923 [00:00<?, ? examples/s]

Map:   0%|          | 0/1224 [00:00<?, ? examples/s]

Map:   0%|          | 0/1235 [00:00<?, ? examples/s]

Let's look at the processed text labels again.

In [19]:
show_random_elements(common_voice_test.remove_columns(["path","audio"]))

In CTC, it is common to classify speech chunks into letters, so we will do the same here.
Let's extract all distinct letters of the training and test data and build our vocabulary from this set of letters.

We write a mapping function that concatenates all transcriptions into one long transcription and then transforms the string into a set of chars.
It is important to pass the argument `batched=True` to the `map(...)` function so that the mapping function has access to all transcriptions at once.

In [8]:
def extract_all_chars(batch):
  all_text = " ".join(batch["sentence"])
  vocab = list(set(all_text))
  return {"vocab": [vocab], "all_text": [all_text]}

In [9]:
vocab_train = common_voice_train.map(extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True, remove_columns=common_voice_train.column_names)
vocab_test = common_voice_test.map(extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True, remove_columns=common_voice_test.column_names)
vocab_dev = common_voice_dev.map(extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True, remove_columns=common_voice_dev.column_names)

Map:   0%|          | 0/3923 [00:00<?, ? examples/s]

Map:   0%|          | 0/1224 [00:00<?, ? examples/s]

Map:   0%|          | 0/1235 [00:00<?, ? examples/s]

Now, we create the union of all distinct letters in the training dataset and test dataset and convert the resulting list into an enumerated dictionary.

In [11]:
vocab_list = list(set(vocab_train["vocab"][0]) | set(vocab_test["vocab"][0]) | set(vocab_dev["vocab"][0]))

In [12]:
vocab_dict = {v: k for k, v in enumerate(sorted(vocab_list))}
vocab_dict

{' ': 0,
 "'": 1,
 '-': 2,
 '`': 3,
 'a': 4,
 'b': 5,
 'c': 6,
 'd': 7,
 'e': 8,
 'f': 9,
 'g': 10,
 'h': 11,
 'i': 12,
 'j': 13,
 'k': 14,
 'l': 15,
 'm': 16,
 'n': 17,
 'o': 18,
 'p': 19,
 'q': 20,
 'r': 21,
 's': 22,
 't': 23,
 'u': 24,
 'v': 25,
 'w': 26,
 'x': 27,
 'y': 28,
 'z': 29,
 'à': 30,
 'á': 31,
 'è': 32,
 'é': 33,
 'ì': 34,
 'ò': 35,
 'ù': 36,
 'ć': 37,
 'ċ': 38,
 'ġ': 39,
 'ħ': 40,
 'ż': 41}

Cleaning up a dataset is a back-and-forth process that needs to be done with care.

Looking at the separate letters in the training and test datasets, and after discussing them with a native speaker of the target language (thanks [Mishig](https://github.com/mishig25)  for taking a look), we can see Latin characters that we are going to remove for two reasons:
1. the CTC algorithm benefits from reduced vocabulary size
2. in this example, we are concentrating entirely on the Mongolian alphabet.

In [13]:
import sys
import re
from pathlib import Path

masri_root = str(Path(".").resolve() / "MASRI")

if masri_root not in sys.path:
    sys.path.append(masri_root)

# Importing tokeniser
try:
    from masri.tokenise.tokenise import MTWordTokenizer
    tokenizer = MTWordTokenizer()
    print("MASRI Tokenizer loaded successfully!")
except ImportError as e:
    print(f"Failed to load MASRI: {e}")


# 3. Define the cleaning function
# Removing digits and unecessary characters that show up in the datasets
chars_to_remove_regex = r'[\d\_\`]' #Removed ` because only appears twice.

def process_maltese_text(batch):
    # Initial cleaning (remove unwanted symbols/punctuation)
    clean_text = re.sub(chars_to_remove_regex, '', batch["sentence"]).lower()

    # Define your Normalization Mapping
    # This maps rare accented characters to their base versions
    mapping = {
         'á': 'a',
         'é': 'e',
         'ć': 'ċ'  

     }

     # 3. Apply the mapping
    for char, replacement in mapping.items():
         clean_text = clean_text.replace(char, replacement)

    # 4. Use MASRI tokenizer to handle Maltese specifics (clitics, etc.)
    # Note: Ensure the tokenizer is initialized outside this function
    #tokens = tokenizer.tokenize(clean_text)
    batch["sentence"] = clean_text.strip()
    
    # 5. Re-join into a clean string for ASR training
    #batch["sentence"] = " ".join(tokens)
    return batch

MASRI Tokenizer loaded successfully!

In [ ]:
# 4. Apply to your datasets
masri_train = masri_train.map(process_maltese_text)
masri_test = masri_test.map(process_maltese_text)
masri_dev = masri_dev.map(process_maltese_text)

In [15]:
# 4. Apply to your datasets
common_voice_train = common_voice_train.map(process_maltese_text)
common_voice_test = common_voice_test.map(process_maltese_text)
common_voice_dev = common_voice_dev.map(process_maltese_text)

Map:   0%|          | 0/3923 [00:00<?, ? examples/s]

Map:   0%|          | 0/1224 [00:00<?, ? examples/s]

Map:   0%|          | 0/1235 [00:00<?, ? examples/s]

In [16]:
vocab_train = common_voice_train.map(extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True, remove_columns=common_voice_train.column_names)
vocab_test = common_voice_test.map(extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True, remove_columns=common_voice_test.column_names)
vocab_dev = common_voice_dev.map(extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True, remove_columns=common_voice_dev.column_names)

Map:   0%|          | 0/3923 [00:00<?, ? examples/s]

Map:   0%|          | 0/1224 [00:00<?, ? examples/s]

Map:   0%|          | 0/1235 [00:00<?, ? examples/s]

In [17]:
vocab_list = list(set(vocab_train["vocab"][0]) | set(vocab_test["vocab"][0]) | set(vocab_dev["vocab"][0]))

In [18]:
vocab_dict = {v: k for k, v in enumerate(sorted(vocab_list))}
vocab_dict

{' ': 0,
 "'": 1,
 '-': 2,
 'a': 3,
 'b': 4,
 'c': 5,
 'd': 6,
 'e': 7,
 'f': 8,
 'g': 9,
 'h': 10,
 'i': 11,
 'j': 12,
 'k': 13,
 'l': 14,
 'm': 15,
 'n': 16,
 'o': 17,
 'p': 18,
 'q': 19,
 'r': 20,
 's': 21,
 't': 22,
 'u': 23,
 'v': 24,
 'w': 25,
 'x': 26,
 'y': 27,
 'z': 28,
 'à': 29,
 'è': 30,
 'ì': 31,
 'ò': 32,
 'ù': 33,
 'ċ': 34,
 'ġ': 35,
 'ħ': 36,
 'ż': 37}

Cool, we see that all letters of the alphabet occur in the dataset (which is not really surprising) and we also extracted the special character `" "`. Note that we did not exclude this special character because:

The model has to learn to predict when a word is finished or else the model prediction would always be a sequence of chars which would make it impossible to separate words from each other.

One should always keep in mind that pre-processing is a very important step before training your model. E.g., we don't want our model to differentiate between `a` and `A` just because we forgot to normalize the data. The difference between `a` and `A` does not depend on the "sound" of the letter at all, but more on grammatical rules - *e.g.* use a capitalized letter at the beginning of the sentence. So it is sensible to remove the difference between capitalized and non-capitalized letters so that the model has an easier time learning to transcribe speech.

To make it clearer that `" "` has its own token class, we give it a more visible character `|`. In addition, we also add an "unknown" token so that the model can later deal with characters not encountered in Common Voice's training set.

In [27]:
vocab_dict["|"] = vocab_dict[" "]
del vocab_dict[" "]

Finally, we also add a padding token that corresponds to CTC's "*blank token*".


The "blank token" is a core component of the CTC algorithm. For more information, please take a look at the "Alignment" section [here](https://distill.pub/2017/ctc/).

In [28]:
vocab_dict["[UNK]"] = len(vocab_dict)
vocab_dict["[PAD]"] = len(vocab_dict)
len(vocab_dict)

36

Cool, now our vocabulary is complete and consists of 37 tokens, which means that the linear layer that we will add on top of the pretrained W2V-BERT checkpoint will have an output dimension of 37.

Let's now save the vocabulary as a json file.

In [36]:
import json
with open('vocab.json', 'w') as vocab_file:
    json.dump(vocab_dict, vocab_file)

In a final step, we use the json file to load the vocabulary into an instance of the `Wav2Vec2CTCTokenizer` class.

In [37]:
from transformers import Wav2Vec2CTCTokenizer

tokenizer = Wav2Vec2CTCTokenizer.from_pretrained("./", unk_token="[UNK]", pad_token="[PAD]", word_delimiter_token="|")

### Create `SeamlessM4TFeatureExtractor`

The role of the `SeamlessM4TFeatureExtractor` is to prepare the raw audio input in a format that the model can "understand". It therefore maps the sequence of one-dimensional amplitude values (aka the raw audio input) to a two-dimensional matrix of log-mel spectrogram values. The latter encodes the signal frequency information as a function of time. See [this section](https://huggingface.co/learn/audio-course/chapter1/audio_data#the-frequency-spectrum) from the Audio Transformers course to learn more about spectrograms and why they are important.

Unlike the tokenizer, the feature extractor doesn't need to be "learned" from the data, so we can load it directly from the [initial model checkpoint](https://huggingface.co/facebook/w2v-bert-2.0).

In [21]:
from transformers import SeamlessM4TFeatureExtractor

feature_extractor = SeamlessM4TFeatureExtractor(feature_size=80, num_mel_bins=80, sampling_rate=16000, padding_value=0.0)

Great, W2V-BERT's feature extraction pipeline is thereby fully defined!

For improved user-friendliness, the feature extractor and tokenizer are *wrapped* into a single `Wav2Vec2BertProcessor` class so that one only needs a `model` and `processor` object.

In [22]:
from transformers import Wav2Vec2BertProcessor

processor = Wav2Vec2BertProcessor(feature_extractor=feature_extractor, tokenizer=tokenizer)

Next, we can prepare the dataset.

### Preprocess Data

So far, we have not looked at the actual values of the speech signal but just the transcription. In addition to `sentence`, our datasets include two more column names `path` and `audio`. `path` states the absolute path of the audio file. Let's take a look.

In [ ]:
# !pip install torchcodec

Collecting torchcodec
  Downloading torchcodec-0.10.0-cp310-cp310-win_amd64.whl.metadata (11 kB)
Downloading torchcodec-0.10.0-cp310-cp310-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 10.4 MB/s  0:00:00
Installing collected packages: torchcodec
Successfully installed torchcodec-0.10.0

In [28]:
common_voice_train[0]["path"]

'/home/ian/MalteseProject/Data/Train/MASRI Train Release 202501/audio files/female/F_01/MSRHS_F_01_P02U001_0001.wav'

W2V-BERT expects the input in the format of a 1-dimensional array of 16 kHz. This means that the audio file has to be loaded and resampled.

 Thankfully, `datasets` does this automatically by calling the other column `audio`. Let try it out.

In [45]:
common_voice_train[0]["audio"]

{'array': [0.005828857421875,
  0.008819580078125,
  0.006988525390625,
  0.0079345703125,
  0.00732421875,
  0.007232666015625,
  0.007720947265625,
  0.00823974609375,
  0.00909423828125,
  0.0087890625,
  0.008087158203125,
  0.008056640625,
  0.007354736328125,
  0.008270263671875,
  0.007354736328125,
  0.00726318359375,
  0.0076904296875,
  0.007781982421875,
  0.00775146484375,
  0.0067138671875,
  0.0074462890625,
  0.008056640625,
  0.006805419921875,
  0.006378173828125,
  0.00738525390625,
  0.0069580078125,
  0.007537841796875,
  0.00689697265625,
  0.005828857421875,
  0.00543212890625,
  0.007080078125,
  0.006988525390625,
  0.006072998046875,
  0.006317138671875,
  0.005828857421875,
  0.006439208984375,
  0.006072998046875,
  0.005462646484375,
  0.0057373046875,
  0.00689697265625,
  0.005645751953125,
  0.005126953125,
  0.005615234375,
  0.005706787109375,
  0.00634765625,
  0.004180908203125,
  0.005126953125,
  0.005340576171875,
  0.0047607421875,
  0.005279541015625,
  0.005889892578125,
  0.005584716796875,
  0.005859375,
  0.00579833984375,
  0.004302978515625,
  0.004180908203125,
  0.004791259765625,
  0.005096435546875,
  0.003875732421875,
  0.00469970703125,
  0.005340576171875,
  0.0052490234375,
  0.005615234375,
  0.0052490234375,
  0.005340576171875,
  0.004669189453125,
  0.004547119140625,
  0.0057373046875,
  0.005218505859375,
  0.00537109375,
  0.005584716796875,
  0.00579833984375,
  0.005279541015625,
  0.004608154296875,
  0.005279541015625,
  0.005157470703125,
  0.005615234375,
  0.005828857421875,
  0.005889892578125,
  0.005706787109375,
  0.005645751953125,
  0.005157470703125,
  0.005401611328125,
  0.00457763671875,
  0.004852294921875,
  0.0052490234375,
  0.00506591796875,
  0.004364013671875,
  0.004180908203125,
  0.004425048828125,
  0.005126953125,
  0.004791259765625,
  0.004608154296875,
  0.005218505859375,
  0.00518798828125,
  0.00439453125,
  0.00396728515625,
  0.003692626953125,
  0.003936767578125,
  0.00433349609375,
  0.004486083984375,
  0.00347900390625,
  0.0042724609375,
  0.00396728515625,
  0.003692626953125,
  0.003753662109375,
  0.003387451171875,
  0.00347900390625,
  0.003082275390625,
  0.003326416015625,
  0.0028076171875,
  0.003143310546875,
  0.00274658203125,
  0.002410888671875,
  0.0020751953125,
  0.00213623046875,
  0.00250244140625,
  0.001373291015625,
  0.001495361328125,
  0.00103759765625,
  0.00238037109375,
  0.003326416015625,
  0.002105712890625,
  0.001739501953125,
  0.002044677734375,
  0.001953125,
  0.001251220703125,
  0.000335693359375,
  0.001007080078125,
  0.001556396484375,
  0.0006103515625,
  -3.0517578125e-05,
  -0.00042724609375,
  -0.000518798828125,
  0.000213623046875,
  0.000152587890625,
  6.103515625e-05,
  0.0,
  0.000335693359375,
  0.00164794921875,
  0.000701904296875,
  0.000244140625,
  0.001068115234375,
  0.0001220703125,
  -0.00030517578125,
  -0.00164794921875,
  -0.001220703125,
  -0.001068115234375,
  -0.000823974609375,
  -0.000152587890625,
  -0.0003662109375,
  -3.0517578125e-05,
  -3.0517578125e-05,
  0.000213623046875,
  -0.000396728515625,
  -0.00048828125,
  -0.00042724609375,
  -0.00048828125,
  -0.001251220703125,
  -0.001922607421875,
  -0.00177001953125,
  -0.001495361328125,
  -0.002288818359375,
  -0.002044677734375,
  -0.001007080078125,
  -0.000701904296875,
  -0.0015869140625,
  -0.000244140625,
  0.000396728515625,
  -0.000396728515625,
  -0.000457763671875,
  -0.001129150390625,
  -0.000946044921875,
  -0.002410888671875,
  -0.002227783203125,
  -0.000640869140625,
  -0.00091552734375,
  -0.0020751953125,
  -0.001953125,
  -0.001129150390625,
  -0.001861572265625,
  -0.001953125,
  -0.0025634765625,
  -0.002777099609375,
  -0.001983642578125,
  -0.00128173828125,
  -0.00140380859375,
  -0.002288818359375,
  -0.002349853515625,
  -0.003021240234375,
  -0.00274658203125,
  -0.003387451171875,
  -0.003753662109375,
  -0.002655029296875,
  -0.002716064453125,
  -0.002777099609375,
  -0.003875732421875,
  -0.003662109375,
  -0.003997802734375,
  -0.004608154296875,
  -0.003997802734375,
  -0.004425048828125,
  -0.00408935546875,
  -0.003814697265625,
  -0.00360107421875,
  -0.002716064453125,
  -0.003082275390625,
  -0.00341796875,
  -0.003204345703125,
  -0.002227783203125,
  -0.00225830078125,
  -0.00311279296875,
  -0.0028076171875,
  -0.003173828125,
  -0.00341796875,
  -0.003875732421875,
  -0.002716064453125,
  -0.002349853515625,
  -0.00341796875,
  -0.003448486328125,
  -0.002593994140625,
  -0.003875732421875,
  -0.00384521484375,
  -0.0037841796875,
  -0.003265380859375,
  -0.0025634765625,
  -0.002410888671875,
  -0.003021240234375,
  -0.0032958984375,
  -0.002685546875,
  -0.003509521484375,
  -0.0032958984375,
  -0.0032958984375,
  -0.002716064453125,
  -0.00299072265625,
  -0.0030517578125,
  -0.003509521484375,
  -0.00408935546875,
  -0.004302978515625,
  -0.004425048828125,
  -0.004669189453125,
  -0.004150390625,
  -0.004608154296875,
  -0.00439453125,
  -0.00506591796875,
  -0.005279541015625,
  -0.005035400390625,
  -0.005218505859375,
  -0.00543212890625,
  -0.005615234375,
  -0.00494384765625,
  -0.004730224609375,
  -0.0045166015625,
  -0.004852294921875,
  -0.0042724609375,
  -0.003936767578125,
  -0.004058837890625,
  -0.004425048828125,
  -0.00445556640625,
  -0.00439453125,
  -0.00421142578125,
  -0.004150390625,
  -0.00567626953125,
  -0.004486083984375,
  -0.0052490234375,
  -0.005767822265625,
  -0.00579833984375,
  -0.005462646484375,
  -0.005096435546875,
  -0.005279541015625,
  -0.00616455078125,
  -0.006256103515625,
  -0.00592041015625,
  -0.006439208984375,
  -0.00677490234375,
  -0.00628662109375,
  -0.006988525390625,
  -0.006683349609375,
  -0.006317138671875,
  -0.007293701171875,
  -0.0069580078125,
  -0.00677490234375,
  -0.0067138671875,
  -0.0069580078125,
  -0.006500244140625,
  -0.007537841796875,
  -0.00640869140625,
  -0.006072998046875,
  -0.006622314453125,
  -0.0069580078125,
  -0.007598876953125,
  -0.007171630859375,
  -0.00787353515625,
  -0.00787353515625,
  -0.00738525390625,
  -0.006927490234375,
  -0.007659912109375,
  -0.00714111328125,
  -0.00750732421875,
  -0.006927490234375,
  -0.007415771484375,
  -0.00836181640625,
  -0.008392333984375,
  -0.00848388671875,
  -0.008148193359375,
  -0.008514404296875,
  -0.009429931640625,
  -0.008544921875,
  -0.00787353515625,
  -0.0081787109375,
  -0.0093994140625,
  -0.0091552734375,
  -0.008331298828125,
  -0.00897216796875,
  -0.00933837890625,
  -0.00970458984375,
  -0.008941650390625,
  -0.00860595703125,
  -0.0074462890625,
  -0.008453369140625,
  -0.00823974609375,
  -0.00927734375,
  -0.009796142578125,
  -0.0101318359375,
  -0.010040283203125,
  -0.009307861328125,
  -0.01007080078125,
  -0.009521484375,
  -0.0087890625,
  -0.00872802734375,
  -0.008941650390625,
  -0.00897216796875,
  -0.0089111328125,
  -0.008026123046875,
  -0.00823974609375,
  -0.008880615234375,
  -0.0101318359375,
  -0.009552001953125,
  -0.009552001953125,
  -0.00958251953125,
  -0.009002685546875,
  -0.009002685546875,
  -0.009063720703125,
  -0.010009765625,
  -0.010589599609375,
  -0.010284423828125,
  -0.0101318359375,
  -0.010101318359375,
  -0.010711669921875,
  -0.01068115234375,
  -0.010467529296875,
  -0.011322021484375,
  -0.010711669921875,
  -0.01220703125,
  -0.011138916015625,
  -0.0111083984375,
  -0.010498046875,
  -0.012054443359375,
  -0.01190185546875,
  -0.01263427734375,
  -0.013031005859375,
  -0.01165771484375,
  -0.01275634765625,
  -0.01251220703125,
  -0.0123291015625,
  -0.0123291015625,
  -0.012420654296875,
  -0.0125732421875,
  -0.0135498046875,
  -0.011322021484375,
  -0.012786865234375,
  -0.012451171875,
  -0.01251220703125,
  -0.013214111328125,
  -0.012298583984375,
  -0.013092041015625,
  -0.01385498046875,
  -0.0137939453125,
  -0.01348876953125,
  -0.013519287109375,
  -0.012908935546875,
  -0.01287841796875,
  -0.014617919921875,
  -0.014251708984375,
  -0.013763427734375,
  -0.01416015625,
  -0.015106201171875,
  -0.015838623046875,
  -0.01617431640625,
  -0.016357421875,
  -0.01544189453125,
  -0.014434814453125,
  -0.014678955078125,
  -0.01507568359375,
  -0.015106201171875,
  -0.01409912109375,
  -0.01470947265625,
  -0.015625,
  -0.014862060546875,
  -0.015289306640625,
  -0.015045166015625,
  -0.01495361328125,
  -0.015533447265625,
  -0.016387939453125,
  -0.01593017578125,
  -0.01593017578125,
  -0.016937255859375,
  -0.016387939453125,
  -0.01593017578125,
  -0.01544189453125,
  -0.0155029296875,
  -0.014801025390625,
  -0.014068603515625,
  -0.015167236328125,
  -0.0166015625,
  -0.01617431640625,
  -0.0166015625,
  -0.01544189453125,
  -0.01556396484375,
  -0.014434814453125,
  -0.014556884765625,
  -0.0152587890625,
  -0.0157470703125,
  -0.015899658203125,
  -0.01580810546875,
  -0.015716552734375,
  -0.01458740234375,
  -0.015380859375,
  -0.015716552734375,
  -0.01641845703125,
  -0.016326904296875,
  -0.016204833984375,
  -0.01605224609375,
  -0.017333984375,
  -0.017913818359375,
  -0.01812744140625,
  -0.01849365234375,
  -0.017608642578125,
  -0.01824951171875,
  -0.0177001953125,
  -0.01678466796875,
  -0.01788330078125,
  -0.017608642578125,
  -0.016357421875,
  -0.01654052734375,
  -0.01690673828125,
  -0.016326904296875,
  -0.016632080078125,
  -0.0169677734375,
  -0.016448974609375,
  -0.01678466796875,
  -0.017333984375,
  -0.016510009765625,
  -0.0166015625,
  -0.01708984375,
  -0.01654052734375,
  -0.0159912109375,
  -0.0167236328125,
  -0.01715087890625,
  -0.017669677734375,
  -0.01788330078125,
  -0.01739501953125,
  -0.0177001953125,
  -0.016754150390625,
  -0.016693115234375,
  -0.016998291015625,
  -0.017791748046875,
  -0.01837158203125,
  -0.019073486328125,
  -0.0194091796875,
  -0.0185546875,
  -0.0177001953125,
  -0.017608642578125,
  -0.018341064453125,
  -0.019073486328125,
  -0.019622802734375,
  -0.019561767578125,
  -0.01837158203125,
  -0.0179443359375,
  -0.01904296875,
  -0.019134521484375,
  -0.019744873046875,
  -0.02032470703125,
  -0.019073486328125,
  -0.019317626953125,
  -0.019775390625,
  -0.019500732421875,
  -0.01885986328125,
  -0.018157958984375,
  -0.01800537109375,
  -0.018341064453125,
  -0.019561767578125,
  -0.0196533203125,
  -0.01873779296875,
  -0.018646240234375,
  -0.01959228515625,
  -0.020751953125,
  -0.0201416015625,
  -0.01873779296875,
  -0.018157958984375,
  -0.019805908203125,
  -0.020050048828125,
  -0.01910400390625,
  -0.0191650390625,
  -0.01953125,
  -0.02020263671875,
  -0.019683837890625,
  -0.018646240234375,
  -0.019622802734375,
  -0.0206298828125,
  -0.019256591796875,
  -0.0194091796875,
  -0.019744873046875,
  -0.01885986328125,
  -0.017913818359375,
  -0.0177001953125,
  -0.01837158203125,
  -0.019439697265625,
  -0.019622802734375,
  -0.02001953125,
  -0.019378662109375,
  -0.01934814453125,
  -0.020111083984375,
  -0.01983642578125,
  -0.01947021484375,
  -0.0205078125,
  -0.019775390625,
  -0.019805908203125,
  -0.019775390625,
  -0.01983642578125,
  -0.020172119140625,
  -0.018829345703125,
  -0.01922607421875,
  -0.019683837890625,
  -0.018646240234375,
  -0.01904296875,
  -0.019561767578125,
  -0.019622802734375,
  -0.019439697265625,
  -0.0181884765625,
  -0.01947021484375,
  -0.01983642578125,
  -0.019317626953125,
  -0.01904296875,
  -0.020294189453125,
  -0.0196533203125,
  -0.019622802734375,
  -0.02020263671875,
  -0.020263671875,
  -0.020233154296875,
  -0.021514892578125,
  -0.0206298828125,
  -0.02020263671875,
  -0.021728515625,
  -0.020111083984375,
  -0.020538330078125,
  -0.02105712890625,
  -0.020294189453125,
  -0.020416259765625,
  -0.0201416015625,
  -0.020660400390625,
  -0.02166748046875,
  -0.02099609375,
  -0.021087646484375,
  -0.020233154296875,
  -0.01971435546875,
  -0.021575927734375,
  -0.020843505859375,
  -0.0218505859375,
  -0.021270751953125,
  -0.021148681640625,
  -0.021392822265625,
  -0.020660400390625,
  -0.020843505859375,
  -0.019744873046875,
  -0.020355224609375,
  -0.021240234375,
  -0.02008056640625,
  -0.02032470703125,
  -0.020751953125,
  -0.01971435546875,
  -0.02056884765625,
  -0.01934814453125,
  -0.0196533203125,
  -0.0211181640625,
  -0.019927978515625,
  -0.021240234375,
  -0.0206298828125,
  -0.01934814453125,
  -0.020660400390625,
  -0.019378662109375,
  -0.018646240234375,
  -0.01934814453125,
  -0.01922607421875,
  -0.018035888671875,
  -0.01824951171875,
  -0.019561767578125,
  -0.019195556640625,
  -0.0179443359375,
  -0.01898193359375,
  -0.019073486328125,
  -0.01800537109375,
  -0.018341064453125,
  -0.019866943359375,
  -0.019287109375,
  -0.017486572265625,
  -0.01922607421875,
  -0.01971435546875,
  -0.018218994140625,
  -0.018280029296875,
  -0.0186767578125,
  -0.017303466796875,
  -0.017822265625,
  -0.017791748046875,
  -0.018463134765625,
  -0.01898193359375,
  -0.01812744140625,
  -0.0179443359375,
  -0.0189208984375,
  -0.019073486328125,
  -0.017486572265625,
  -0.017547607421875,
  -0.0181884765625,
  -0.0185546875,
  -0.017730712890625,
  -0.017974853515625,
  -0.01922607421875,
  -0.01910400390625,
  -0.01812744140625,
  -0.019012451171875,
  -0.018035888671875,
  -0.01776123046875,
  -0.017730712890625,
  -0.01922607421875,
  -0.019439697265625,
  -0.018280029296875,
  -0.019439697265625,
  -0.018585205078125,
  -0.017730712890625,
  -0.0177001953125,
  -0.01800537109375,
  -0.017486572265625,
  -0.017791748046875,
  -0.018096923828125,
  -0.019287109375,
  -0.018463134765625,
  -0.018524169921875,
  -0.017730712890625,
  -0.017333984375,
  -0.01641845703125,
  -0.015533447265625,
  -0.016632080078125,
  -0.01715087890625,
  -0.017547607421875,
  -0.016632080078125,
  -0.01605224609375,
  -0.0157470703125,
  -0.015228271484375,
  -0.01593017578125,
  -0.0169677734375,
  -0.0172119140625,
  -0.016326904296875,
  -0.01593017578125,
  -0.016510009765625,
  -0.015655517578125,
  -0.01678466796875,
  -0.016937255859375,
  -0.016021728515625,
  -0.016448974609375,
  -0.016143798828125,
  -0.016265869140625,
  -0.017547607421875,
  -0.016326904296875,
  -0.015838623046875,
  -0.015167236328125,
  -0.014617919921875,
  -0.01495361328125,
  -0.01568603515625,
  -0.0164794921875,
  -0.015716552734375,
  -0.015869140625,
  -0.0152587890625,
  -0.015380859375,
  -0.014892578125,
  -0.015350341796875,
  -0.0145263671875,
  -0.015625,
  -0.015625,
  -0.015716552734375,
  -0.015869140625,
  -0.0152587890625,
  -0.015869140625,
  -0.014556884765625,
  -0.014862060546875,
  -0.014434814453125,
  -0.0147705078125,
  -0.0145263671875,
  -0.014617919921875,
  -0.0147705078125,
  -0.0135498046875,
  -0.014495849609375,
  -0.015106201171875,
  -0.015167236328125,
  -0.01531982421875,
  -0.01483154296875,
  -0.01422119140625,
  -0.01373291015625,
  -0.013885498046875,
  -0.01373291015625,
  -0.013916015625,
  -0.013885498046875,
  -0.014678955078125,
  -0.014495849609375,
  -0.013763427734375,
  -0.013641357421875,
  -0.013580322265625,
  -0.013458251953125,
  -0.01458740234375,
  -0.01385498046875,
  -0.01336669921875,
  -0.013885498046875,
  -0.013580322265625,
  -0.012420654296875,
  -0.0118408203125,
  -0.01348876953125,
  -0.01348876953125,
  -0.01312255859375,
  -0.012969970703125,
  -0.01300048828125,
  -0.012969970703125,
  -0.013153076171875,
  -0.012542724609375,
  -0.012054443359375,
  -0.01239013671875,
  -0.011627197265625,
  -0.011474609375,
  -0.011138916015625,
  -0.0115966796875,
  -0.011962890625,
  -0.012542724609375,
  -0.012359619140625,
  -0.010589599609375,
  -0.009857177734375,
  -0.010955810546875,
  -0.01153564453125,
  -0.011749267578125,
  -0.011810302734375,
  -0.010498046875,
  -0.0098876953125,
  -0.00958251953125,
  -0.010040283203125,
  -0.011566162109375,
  -0.00958251953125,
  -0.00872802734375,
  -0.011260986328125,
  -0.01104736328125,
  -0.00933837890625,
  -0.009185791015625,
  -0.0106201171875,
  -0.010955810546875,
  -0.0107421875,
  -0.009521484375,
  -0.010040283203125,
  -0.010101318359375,
  -0.01019287109375,
  -0.00958251953125,
  -0.00921630859375,
  -0.00921630859375,
  -0.010223388671875,
  -0.008819580078125,
  -0.009246826171875,
  -0.009368896484375,
  -0.007232666015625,
  -0.0084228515625,
  -0.008636474609375,
  -0.00848388671875,
  -0.008026123046875,
  -0.00830078125,
  -0.007293701171875,
  -0.008087158203125,
  -0.006500244140625,
  -0.007598876953125,
  -0.0074462890625,
  -0.007293701171875,
  -0.007171630859375,
  -0.0067138671875,
  -0.0076904296875,
  -0.0067138671875,
  -0.00726318359375,
  -0.00592041015625,
  -0.008148193359375,
  -0.0067138671875,
  -0.00604248046875,
  -0.008819580078125,
  -0.005035400390625,
  -0.0067138671875,
  -0.0081787109375,
  -0.003662109375,
  -0.00628662109375,
  -0.00531005859375,
  -0.00469970703125,
  -0.00677490234375,
  -0.006011962890625,
  -0.00531005859375,
  -0.00537109375,
  -0.005096435546875,
  -0.003753662109375,
  -0.003387451171875,
  -0.002410888671875,
  -0.00439453125,
  -0.004791259765625,
  -0.002899169921875,
  -0.006256103515625,
  -0.003448486328125,
  -0.002471923828125,
  -0.006805419921875,
  -0.00213623046875,
  -0.003631591796875,
  -0.006256103515625,
  -0.003448486328125,
  -0.003387451171875,
  -0.00634765625,
  -0.00360107421875,
  -0.003631591796875,
  -0.004302978515625,
  -0.0028076171875,
  -0.005523681640625,
  -0.0023193359375,
  -0.00433349609375,
  -0.005615234375,
  -0.002960205078125,
  -0.004913330078125,
  -0.0025634765625,
  -0.00299072265625,
  -0.00323486328125,
  -0.0032958984375,
  -0.0047607421875,
  -0.003753662109375,
  -0.005218505859375,
  -0.004974365234375,
  -0.0040283203125,
  -0.005462646484375,
  -0.00384521484375,
  -0.0037841796875,
  -0.0042724609375,
  -0.0042724609375,
  -0.00433349609375,
  -0.003448486328125,
  -0.002655029296875,
  -0.003448486328125,
  -0.003875732421875,
  -0.0025634765625,
  -0.00286865234375,
  -0.002532958984375,
  -0.002288818359375,
  -0.002227783203125,
  -0.001556396484375,
  -0.001708984375,
  -0.002197265625,
  -0.00042724609375,
  -0.0010986328125,
  -0.001800537109375,
  -0.000244140625,
  -0.00067138671875,
  0.000244140625,
  -0.00067138671875,
  -0.001007080078125,
  0.00128173828125,
  -0.00018310546875,
  -9.1552734375e-05,
  -0.000640869140625,
  -0.001220703125,
  0.000244140625,
  -0.0003662109375,
  -0.000762939453125,
  -0.00067138671875,
  -0.000640869140625,
  -0.000518798828125,
  -0.001708984375,
  -0.000701904296875,
  0.0001220703125,
  -0.00079345703125,
  -6.103515625e-05,
  -0.000152587890625,
  0.00042724609375,
  -0.00018310546875,
  0.000457763671875,
  -0.0001220703125,
  0.000701904296875,
  0.0008544921875,
  -0.00018310546875,
  0.001220703125,
  0.000701904296875,
  0.00128173828125,
  0.0018310546875,
  -0.000213623046875,
  0.000518798828125,
  0.000244140625,
  -0.001312255859375,
  0.00189208984375,
  0.00048828125,
  9.1552734375e-05,
  0.001312255859375,
  -0.0009765625,
  6.103515625e-05,
  0.00103759765625,
  -0.00091552734375,
  0.001678466796875,
  0.000640869140625,
  0.00091552734375,
  0.001312255859375,
  6.103515625e-05,
  0.001251220703125,
  0.000732421875,
  0.00018310546875,
  0.001220703125,
  0.001068115234375,
  -0.0003662109375,
  0.000244140625,
  0.00018310546875,
  -0.00018310546875,
  0.000823974609375,
  0.00042724609375,
  0.001434326171875,
  0.0013427734375,
  0.002777099609375,
  0.00244140625,
  0.00140380859375,
  0.001861572265625,
  0.000946044921875,
  0.001129150390625,
  0.001129150390625,
  0.002532958984375,
  0.0023193359375,
  0.004119873046875,
  0.003143310546875,
  0.00286865234375,
  0.003173828125,
  0.003204345703125,
  0.004669189453125,
  0.003814697265625,
  0.004241943359375,
  0.004669189453125,
  0.003936767578125,
  0.003692626953125,
  0.00372314453125,
  0.00311279296875,
  0.002960205078125,
  0.003021240234375,
  0.002471923828125,
  0.002960205078125,
  0.00250244140625,
  0.003082275390625,
  0.002899169921875,
  0.003875732421875,
  0.0032958984375,
  0.002410888671875,
  0.00433349609375,
  0.003570556640625,


Great, we can see that the audio file has automatically been loaded. This is thanks to the new [`"Audio"` feature](https://huggingface.co/docs/datasets/package_reference/main_classes.html?highlight=audio#datasets.Audio) introduced in `datasets == 4.13.3`, which loads and resamples audio files on-the-fly upon calling.

In the example above we can see that the audio data is loaded with a sampling rate of 48kHz whereas Wav2Vec2-BERT was pre-trained at a sampling rate of 16kHz. The sampling rate plays an important role in that it defines how many data points of the speech signal are measured per second. Therefore, sampling with a higher sampling rate results in a better approximation of the *real* speech signal but also necessitates more values per second.

A pre-trained checkpoint expects its input data to have been sampled more or less from the same distribution as the data it was trained on. The same speech signals sampled at two different rates have a very different distribution, *e.g.*, doubling the sampling rate results in data points being twice as long. Thus,
before fine-tuning a pre-trained checkpoint of an ASR model, it is crucial to verify that the sampling rate of the data that was used to pre-train the model matches the sampling rate of the dataset used to fine-tune the model.

Let's listen to a couple of audio files to better understand the dataset and verify that the audio was correctly loaded.

**Note**: *You can click the following cell a couple of times to listen to different speech samples.*

In [30]:
import IPython.display as ipd
import numpy as np
import random

rand_int = random.randint(0, len(common_voice_train)-1)

print(common_voice_train[rand_int]["sentence"])
ipd.Audio(data=common_voice_train[rand_int]["audio"]["array"], autoplay=True, rate=16000)

jinħabbu bil- bosta għarajjes flimkien u mat- tabib callus ma tantx tista' tiċċajta

It seems like the data is now correctly loaded and resampled.

It can be heard, that the speakers change along with their speaking rate, accent, and background environment, etc. Overall, the recordings sound acceptably clear though, which is to be expected from a crowd-sourced read speech corpus.

Let's do a final check that the data is correctly prepared, by printing the shape of the speech input, its transcription, and the corresponding sampling rate.

**Note**: *You can click the following cell a couple of times to verify multiple samples.*

In [50]:
import random
import numpy as np

rand_int = random.randint(0, len(common_voice_train)-1)

# Get the array data
audio_data = common_voice_train[rand_int]["audio"]["array"]

print("Target text:", common_voice_train[rand_int]["sentence"])
# We wrap it in np.array here just to check the shape
print("Input array shape:", np.array(audio_data).shape) 
print("Sampling rate:", common_voice_train[rand_int]["audio"]["sampling_rate"])

Target text: il- fieragħ tal- fizzjal imħawwad b' dak kollu li kien ġralu wara li ħallieha laqqas kien jiftakar iżjed fil- laqgħa li kellu qawl il- lejl ma' marjetta
Input array shape: (128521,)
Sampling rate: 16000

Good! Everything looks fine - the data is a 1-dimensional array, the sampling rate always corresponds to 16kHz, and the target text is normalized.

Finally, we can leverage `Wav2Vec2BertProcessor` to process the data to the format expected by `Wav2Vec2BertForCTC` for training. To do so let's make use of Dataset's [`map(...)`](https://huggingface.co/docs/datasets/package_reference/main_classes.html?highlight=map#datasets.DatasetDict.map) function.

First, we load and resample the audio data, simply by calling `batch["audio"]`.
Second, we extract the `input_features` from the loaded audio file. In our case, the `Wav2Vec2BertProcessor` creates a more complex representation as the raw waveform, known as [Log-Mel feature extraction](https://en.wikipedia.org/wiki/Mel-frequency_cepstrum).
Third, we encode the transcriptions to label ids.

In [31]:
def prepare_dataset(batch):
    audio = batch["audio"]
    batch["input_features"] = processor(audio["array"], sampling_rate=audio["sampling_rate"]).input_features[0]
    batch["input_length"] = len(batch["input_features"])

    batch["labels"] = processor(text=batch["sentence"]).input_ids
    return batch

Let's apply the data preparation function to all examples.

In [32]:
common_voice_train = common_voice_train.map(prepare_dataset, remove_columns=common_voice_train.column_names)
common_voice_test = common_voice_test.map(prepare_dataset, remove_columns=common_voice_test.column_names)

Map:   0%|          | 0/8886 [00:00<?, ? examples/s]

Map:   0%|          | 0/1892 [00:00<?, ? examples/s]

**Note**: `datasets` automatically takes care of audio loading and resampling. If you wish to implement your own costumized data loading/sampling, feel free to just make use of the `"path"` column instead and disregard the `"audio"` column.

Awesome, now we are ready to start training!

## Training

The data is processed so that we are ready to start setting up the training pipeline. We will make use of 🤗's [Trainer](https://huggingface.co/transformers/master/main_classes/trainer.html?highlight=trainer) for which we essentially need to do the following:

- Define a data collator. In contrast to most NLP models, W2V-BERT has a much larger input length than output length. Given the large input sizes, it is much more efficient to pad the training batches dynamically meaning that all training samples should only be padded to the longest sample in their batch and not the overall longest sample. Therefore, fine-tuning W2V-BERT requires a special padding data collator, which we will define below.

- Evaluation metric. During training, the model should be evaluated on the word error rate. We should define a `compute_metrics` function accordingly

- Load a pretrained checkpoint. We need to load a pretrained checkpoint and configure it correctly for training.

- Define the training configuration.

After having fine-tuned the model, we will correctly evaluate it on the test data and verify that it has indeed learned to correctly transcribe speech.

### Set-up Trainer

Let's start by defining the data collator. The code for the data collator was copied from [this example](https://github.com/huggingface/transformers/blob/7e61d56a45c19284cfda0cee8995fb552f6b1f4e/examples/pytorch/speech-recognition/run_speech_recognition_ctc.py#L219).

Without going into too many details, in contrast to the common data collators, this data collator treats the `input_features` and `labels` differently and thus applies to separate padding functions on them. This is necessary because in speech input and output are of different modalities meaning that they should not be treated by the same padding function.
Analogous to the common data collators, the padding tokens in the labels with `-100` so that those tokens are **not** taken into account when computing the loss.

In [33]:
import torch

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union

@dataclass
class DataCollatorCTCWithPadding:
    processor: Wav2Vec2BertProcessor
    padding: Union[bool, str] = True

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        # split inputs and labels since they have to be of different lenghts and need
        # different padding methods
        input_features = [{"input_features": feature["input_features"]} for feature in features]
        label_features = [{"input_ids": feature["labels"]} for feature in features]

        batch = self.processor.pad(
            input_features,
            padding=self.padding,
            return_tensors="pt",
        )

        labels_batch = self.processor.pad(
            labels=label_features,
            padding=self.padding,
            return_tensors="pt",
        )
        # replace padding with -100 to ignore loss correctly
        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)

        batch["labels"] = labels

        return batch

In [34]:
data_collator = DataCollatorCTCWithPadding(processor=processor, padding=True)

Next, the evaluation metric is defined. As mentioned earlier, the
predominant metric in ASR is the word error rate (WER), hence we will use it in this notebook as well.

In [35]:
import evaluate
wer_metric = evaluate.load("wer")
cer_metric = evaluate.load("cer")

The model will return a sequence of logit vectors:
$\mathbf{y}_1, \ldots, \mathbf{y}_m$ with $\mathbf{y}_1 = f_{\theta}(x_1, \ldots, x_n)[0]$ and $n >> m$.

A logit vector $\mathbf{y}_1$ contains the log-odds for each word in the vocabulary we defined earlier, thus $\text{len}(\mathbf{y}_i) =$ `config.vocab_size`. We are interested in the most likely prediction of the model and thus take the `argmax(...)` of the logits. Also, we transform the encoded labels back to the original string by replacing `-100` with the `pad_token_id` and decoding the ids while making sure that consecutive tokens are **not** grouped to the same token in CTC style ${}^1$.

In [36]:
def compute_metrics(pred):
    pred_logits = pred.predictions
    pred_ids = np.argmax(pred_logits, axis=-1)

    # Handle the -100 labels
    pred.label_ids[pred.label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str = processor.batch_decode(pred_ids)
    label_str = processor.batch_decode(pred.label_ids, group_tokens=False)

    # Compute both metrics
    wer = wer_metric.compute(predictions=pred_str, references=label_str)
    cer = cer_metric.compute(predictions=pred_str, references=label_str)

    return {"wer": wer, "cer": cer}

Now, we can load the pretrained checkpoint of [Wav2Vec2-XLS-R-300M](https://huggingface.co/facebook/wav2vec2-xls-r-300m). The tokenizer's `pad_token_id` must be to define the model's `pad_token_id` or in the case of `Wav2Vec2BertForCTC` also CTC's *blank token* ${}^2$. To save GPU memory, we enable PyTorch's [gradient checkpointing](https://pytorch.org/docs/stable/checkpoint.html) and also set the loss reduction to "*mean*".

Since, we're only training a small subset of weights, the model is not prone to overfitting. Therefore, we make sure to disable all dropout layers.

**Note**: When using this notebook to train W2V-BERT on another language of Common Voice those hyper-parameter settings might not work very well. Feel free to adapt those depending on your use case.

In [37]:
from transformers import Wav2Vec2BertForCTC

model = Wav2Vec2BertForCTC.from_pretrained(
    "facebook/w2v-bert-2.0",
    attention_dropout=0.0,
    hidden_dropout=0.0,
    feat_proj_dropout=0.0,
    mask_time_prob=0.0,
    layerdrop=0.0,
    ctc_loss_reduction="mean",
    ctc_zero_infinity=True, #ADDED BY IAN TO TRY TO PREVENT NAN
    add_adapter=True,
    pad_token_id=processor.tokenizer.pad_token_id,
    vocab_size=len(processor.tokenizer),
)

Some weights of Wav2Vec2BertForCTC were not initialized from the model checkpoint at facebook/w2v-bert-2.0 and are newly initialized: ['lm_head.bias', 'lm_head.weight', 'wav2vec2_bert.adapter.layers.0.ffn.intermediate_dense.bias', 'wav2vec2_bert.adapter.layers.0.ffn.intermediate_dense.weight', 'wav2vec2_bert.adapter.layers.0.ffn.output_dense.bias', 'wav2vec2_bert.adapter.layers.0.ffn.output_dense.weight', 'wav2vec2_bert.adapter.layers.0.ffn_layer_norm.bias', 'wav2vec2_bert.adapter.layers.0.ffn_layer_norm.weight', 'wav2vec2_bert.adapter.layers.0.residual_conv.bias', 'wav2vec2_bert.adapter.layers.0.residual_conv.weight', 'wav2vec2_bert.adapter.layers.0.residual_layer_norm.bias', 'wav2vec2_bert.adapter.layers.0.residual_layer_norm.weight', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_k.bias', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_k.weight', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_out.bias', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_out.weight', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_q.bias', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_q.weight', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_v.bias', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_v.weight', 'wav2vec2_bert.adapter.layers.0.self_attn_conv.bias', 'wav2vec2_bert.adapter.layers.0.self_attn_conv.weight', 'wav2vec2_bert.adapter.layers.0.self_attn_layer_norm.bias', 'wav2vec2_bert.adapter.layers.0.self_attn_layer_norm.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In a final step, we define all parameters related to training.
To give more explanation on some of the parameters:
- `group_by_length` makes training more efficient by grouping training samples of similar input length into one batch. This can significantly speed up training time by heavily reducing the overall number of useless padding tokens that are passed through the model
- `learning_rate` was heuristically tuned until fine-tuning has become stable. Note that those parameters strongly depend on the Common Voice dataset and might be suboptimal for other speech datasets.

For more explanations on other parameters, one can take a look at the [docs](https://huggingface.co/transformers/master/main_classes/trainer.html?highlight=trainer#trainingarguments).

During training, a checkpoint will be uploaded asynchronously to the hub every 600 training steps. It allows you to also play around with the demo widget even while your model is still training.

**Note**: If one does not want to upload the model checkpoints to the hub, simply set `push_to_hub=False`.

In [39]:
from transformers import TrainingArguments

training_args = TrainingArguments(
  output_dir=repo_name,
  group_by_length=True,
  per_device_train_batch_size=16,
  gradient_accumulation_steps=2,
  evaluation_strategy="steps",
  num_train_epochs=10,
  gradient_checkpointing=True,
  fp16=True,
  save_steps=600,
  eval_steps=300,
  logging_steps=300,
  learning_rate=5e-5,
  warmup_steps=500,
  save_total_limit=2,
  push_to_hub=True,
)

NameError: name 'repo_name' is not defined

In [38]:
from transformers import TrainingArguments

# Output path
local_output_dir = "/mnt/c/Users/Ian/Documents/TeziTesting/Runs/runTokenised"

training_args = TrainingArguments(
  output_dir=local_output_dir,
  group_by_length=True,
  
  # --- GPU VRAM ADJUSTMENTS (Safe for 3080) ---
  per_device_train_batch_size=4,
  gradient_accumulation_steps=8,
  gradient_checkpointing=True,
  fp16=True,
  bf16=False, 


  # Prevents NaN by capping giant gradient spikes
  max_grad_norm=1.0,
  
  # --- TRAINING SETTINGS ---
  eval_strategy="steps",
  save_strategy="steps",
  num_train_epochs=10,
  # learning_rate=2e-5,
  learning_rate=5e-5,  #Changed this since Im resuming training
  warmup_steps=500,
  
  # --- LOGGING & LOCAL SAVING ---
  save_steps=300,       # Saves a checkpoint folder every 300 steps
  eval_steps=300,       # Tests the model every 300 steps
  logging_steps=100,    # Shows you the loss/progress every 100 steps
  save_total_limit=3,   # Keeps only the 2 most recent checkpoints (saves disk space)

  # Best model logic
  load_best_model_at_end=True, # Automatically loads the best model when training finishes
  metric_for_best_model="wer", # Decide 'best' based on Word Error Rate
  greater_is_better=False,
  
  # --- DISABLE HUB/GIT ---
  push_to_hub=False,            # No Hugging Face upload
  report_to="none",             # Prevents trying to log to online tools like WandB
)

Now, all instances can be passed to Trainer and we are ready to start training!

In [39]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    data_collator=data_collator,
    args=training_args,
    compute_metrics=compute_metrics,
    train_dataset=common_voice_train,
    eval_dataset=common_voice_test,
    # Use processing_class instead of tokenizer
    processing_class=processor, 
)



---

${}^1$ To allow models to become independent of the speaker rate, in CTC, consecutive tokens that are identical are simply grouped as a single token. However, the encoded labels should not be grouped when decoding since they don't correspond to the predicted tokens of the model, which is why the `group_tokens=False` parameter has to be passed. If we wouldn't pass this parameter a word like `"hello"` would incorrectly be encoded, and decoded as `"helo"`.

${}^2$ The blank token allows the model to predict a word, such as `"hello"` by forcing it to insert the blank token between the two l's. A CTC-conform prediction of `"hello"` of our model would be `[PAD] [PAD] "h" "e" "e" "l" "l" [PAD] "l" "o" "o" [PAD]`.

### Training

In [ ]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 44, 'bos_token_id': 43}.

## KenLM Experiments

In [17]:
import torch
import librosa
from pathlib import Path
from transformers import Wav2Vec2BertForCTC, Wav2Vec2BertProcessor
from pyctcdecode import build_ctcdecoder
from jiwer import wer
from tqdm import tqdm

# 1. Setup paths
base_path = Path(".") 
my_model_path = base_path / "Runs" / "checkpoint-5690"
LM_PATH = str(base_path / "3_untok_red.bin")

device = "cuda" if torch.cuda.is_available() else "cpu"

# 2. Load Model and Processor
model = Wav2Vec2BertForCTC.from_pretrained(my_model_path).to(device)
processor = Wav2Vec2BertProcessor.from_pretrained(my_model_path)
model.eval()

# 3. Prepare Decoder Vocab
vocab = processor.tokenizer.get_vocab()
sorted_vocab = [k for k, v in sorted(vocab.items(), key=lambda item: item[1])]


ARPA_PATH = str(base_path / "3_untok_red.arpa") # Path to  ARPA file

# 1. Extract Unigrams 
def get_unigram_list(arpa_path):
    unigrams = []
    with open(arpa_path, "r") as f:
        is_unigram_section = False
        for line in f:
            if "\\1-grams:" in line:
                is_unigram_section = True
                continue
            if "\\2-grams:" in line or line.startswith("\\end\\"):
                break
            if is_unigram_section:
                parts = line.strip().split()
                if len(parts) >= 2:
                    word = parts[1]
                    if word not in ["<s>", "</s>", "<unk>"]:
                        unigrams.append(word)
    return unigrams

print("Extracting unigrams...")
UNIGRAM_LIST = get_unigram_list(ARPA_PATH)

def optimize_with_dataset(dataset):
    all_logits_numpy = []
    all_ground_truths = []
    greedy_preds = []

    print(f"--- Step 1: Generating Logits for {len(dataset)} samples ---")
    
    for i in tqdm(range(len(dataset))):
        batch = dataset[i]
        # Use the logic from your attempt: Load from the 'audio' dictionary in the dataset
        audio = batch["audio"]["array"] 
        
        # 4. Convert audio to format the model expects (Your Step 5 logic)
        inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
        input_features = inputs.input_features.to(device)

        # 5. Run Inference (Your Step 6 logic)
        with torch.no_grad():
            logits = model(input_features).logits
        
        # Store for KenLM
        all_logits_numpy.append(logits.cpu().numpy()[0])
        
        # Store Ground Truth
        all_ground_truths.append(batch["sentence"].lower())
        
        # Store Greedy (Your Step 7 logic)
        pred_ids = torch.argmax(logits, dim=-1)
        greedy_preds.append(processor.batch_decode(pred_ids)[0].lower())

    # Calculate Baseline WER
    baseline_wer = wer(all_ground_truths, greedy_preds)
    print(f"\nRAW MODEL WER: {baseline_wer:.4f}")

    # 6. Grid Search for Alpha and Beta
    best_wer = 1.0
    best_params = (0, 0)
    
    # Expanded ranges to find the true minimum
    alphas = [0.4, 0.45, 0.5, 0.55, 0.6] 
    betas = [2.5, 2.75, 3.0, 3.25, 3.5]

    print(f"\n--- Step 2: Grid Search ({len(alphas) * len(betas)} combinations) ---")
    print(f"{'Alpha':<8} | {'Beta':<8} | {'WER':<10}")
    print("-" * 35)

    # Initialize decoder ONCE to save time and memory
    decoder = build_ctcdecoder(
        labels=sorted_vocab,
        kenlm_model_path=LM_PATH,
        unigrams=UNIGRAM_LIST,
    )

    for a in alphas:
        for b in betas:
            # Update the existing decoder's weights (fast)
            decoder.reset_params(alpha=a, beta=b)
            
            # Run the decoding
            kenlm_preds = [decoder.decode(l).lower() for l in all_logits_numpy]
            current_wer = wer(all_ground_truths, kenlm_preds)
            
            print(f"{a:<8} | {b:<8} | {current_wer:.4f}")
            
            if current_wer < best_wer:
                best_wer = current_wer
                best_params = (a, b)
    
    return best_params

Extracting unigrams...

#### Trigram Refinement

In [18]:
best_a, best_b = optimize_with_dataset(common_voice_dev)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [03:16<00:00,  9.57it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

RAW MODEL WER: 0.1237

--- Step 2: Grid Search (25 combinations) ---
Alpha    | Beta     | WER
-----------------------------------
0.4      | 2.5      | 0.1074
0.4      | 2.75     | 0.1083
0.4      | 3.0      | 0.1095
0.4      | 3.25     | 0.1107
0.4      | 3.5      | 0.1120
0.45     | 2.5      | 0.1067
0.45     | 2.75     | 0.1074
0.45     | 3.0      | 0.1079
0.45     | 3.25     | 0.1093
0.45     | 3.5      | 0.1103
0.5      | 2.5      | 0.1064
0.5      | 2.75     | 0.1067
0.5      | 3.0      | 0.1064
0.5      | 3.25     | 0.1075
0.5      | 3.5      | 0.1088
0.55     | 2.5      | 0.1074
0.55     | 2.75     | 0.1072
0.55     | 3.0      | 0.1071
0.55     | 3.25     | 0.1074
0.55     | 3.5      | 0.1076
0.6      | 2.5      | 0.1086
0.6      | 2.75     | 0.1085
0.6      | 3.0      | 0.1078
0.6      | 3.25     | 0.1077
0.6      | 3.5      | 0.1079

#### Bi grams

In [20]:
best_a, best_b = optimize_with_dataset(common_voice_dev)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [03:25<00:00,  9.18it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

RAW MODEL WER: 0.1237

--- Step 2: Grid Search (30 combinations) ---
Alpha    | Beta     | WER
-----------------------------------
0.3      | 1.0      | 0.1074
0.3      | 2.0      | 0.1083
0.3      | 3.0      | 0.1132
0.3      | 4.0      | 0.1243
0.3      | 5.0      | 0.1430
0.3      | 7.0      | 0.1960
0.5      | 1.0      | 0.1097
0.5      | 2.0      | 0.1071
0.5      | 3.0      | 0.1070
0.5      | 4.0      | 0.1123
0.5      | 5.0      | 0.1215
0.5      | 7.0      | 0.1584
0.7      | 1.0      | 0.1161
0.7      | 2.0      | 0.1116
0.7      | 3.0      | 0.1087
0.7      | 4.0      | 0.1089
0.7      | 5.0      | 0.1100
0.7      | 7.0      | 0.1333
0.9      | 1.0      | 0.1317
0.9      | 2.0      | 0.1241
0.9      | 3.0      | 0.1182
0.9      | 4.0      | 0.1150
0.9      | 5.0      | 0.1125
0.9      | 7.0      | 0.1169
1.1      | 1.0      | 0.1549
1.1      | 2.0      | 0.1436
1.1      | 3.0      | 0.1346
1.1      | 4.0      | 0.1269
1.1      | 5.0      | 0.1229
1.1      | 7.0      | 0.1187

#### Four Gram Big Model

In [19]:
best_a, best_b = optimize_with_dataset(common_voice_dev)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [02:53<00:00, 10.86it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

RAW MODEL WER: 0.1237

--- Step 2: Grid Search (30 combinations) ---
Alpha    | Beta     | WER
-----------------------------------
0.3      | 1.0      | 0.1072
0.3      | 2.0      | 0.1086
0.3      | 3.0      | 0.1133
0.3      | 4.0      | 0.1277
0.3      | 5.0      | 0.1467
0.3      | 7.0      | 0.1974
0.5      | 1.0      | 0.1092
0.5      | 2.0      | 0.1071
0.5      | 3.0      | 0.1075
0.5      | 4.0      | 0.1132
0.5      | 5.0      | 0.1245
0.5      | 7.0      | 0.1658
0.7      | 1.0      | 0.1169
0.7      | 2.0      | 0.1123
0.7      | 3.0      | 0.1106
0.7      | 4.0      | 0.1098
0.7      | 5.0      | 0.1121
0.7      | 7.0      | 0.1408
0.9      | 1.0      | 0.1335
0.9      | 2.0      | 0.1243
0.9      | 3.0      | 0.1194
0.9      | 4.0      | 0.1145
0.9      | 5.0      | 0.1118
0.9      | 7.0      | 0.1206
1.1      | 1.0      | 0.1571
1.1      | 2.0      | 0.1438
1.1      | 3.0      | 0.1348
1.1      | 4.0      | 0.1280
1.1      | 5.0      | 0.1240
1.1      | 7.0      | 0.1185

### Trigram Big Model

In [21]:
best_a, best_b = optimize_with_dataset(common_voice_dev)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [02:54<00:00, 10.80it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

RAW MODEL WER: 0.1237

--- Step 2: Grid Search (30 combinations) ---
Alpha    | Beta     | WER
-----------------------------------
0.3      | 1.0      | 0.1077
0.3      | 2.0      | 0.1087
0.3      | 3.0      | 0.1130
0.3      | 4.0      | 0.1280
0.3      | 5.0      | 0.1467
0.3      | 7.0      | 0.1956
0.5      | 1.0      | 0.1093
0.5      | 2.0      | 0.1072
0.5      | 3.0      | 0.1064
0.5      | 4.0      | 0.1116
0.5      | 5.0      | 0.1257
0.5      | 7.0      | 0.1660
0.7      | 1.0      | 0.1166
0.7      | 2.0      | 0.1114
0.7      | 3.0      | 0.1103
0.7      | 4.0      | 0.1089
0.7      | 5.0      | 0.1123
0.7      | 7.0      | 0.1407
0.9      | 1.0      | 0.1324
0.9      | 2.0      | 0.1248
0.9      | 3.0      | 0.1179
0.9      | 4.0      | 0.1141
0.9      | 5.0      | 0.1127
0.9      | 7.0      | 0.1207
1.1      | 1.0      | 0.1581
1.1      | 2.0      | 0.1451
1.1      | 3.0      | 0.1354
1.1      | 4.0      | 0.1283
1.1      | 5.0      | 0.1249
1.1      | 7.0      | 0.1197

### Fourgram Mid Reduction

In [20]:
best_a, best_b = optimize_with_dataset(common_voice_dev)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [02:57<00:00, 10.62it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

RAW MODEL WER: 0.1724

--- Step 2: Grid Search (30 combinations) ---
Alpha    | Beta     | WER
-----------------------------------
0.3      | 1.0      | 0.1378
0.3      | 2.0      | 0.1402
0.3      | 3.0      | 0.1483
0.3      | 4.0      | 0.1612
0.3      | 5.0      | 0.1869
0.3      | 7.0      | 0.2542
0.5      | 1.0      | 0.1337
0.5      | 2.0      | 0.1329
0.5      | 3.0      | 0.1349
0.5      | 4.0      | 0.1422
0.5      | 5.0      | 0.1576
0.5      | 7.0      | 0.2099
0.7      | 1.0      | 0.1361
0.7      | 2.0      | 0.1347
0.7      | 3.0      | 0.1326
0.7      | 4.0      | 0.1334
0.7      | 5.0      | 0.1392
0.7      | 7.0      | 0.1759
0.9      | 1.0      | 0.1430
0.9      | 2.0      | 0.1394
0.9      | 3.0      | 0.1370
0.9      | 4.0      | 0.1341
0.9      | 5.0      | 0.1343
0.9      | 7.0      | 0.1526
1.1      | 1.0      | 0.1541
1.1      | 2.0      | 0.1485
1.1      | 3.0      | 0.1434
1.1      | 4.0      | 0.1396
1.1      | 5.0      | 0.1377
1.1      | 7.0      | 0.1387

### Bigrams Mid Reduction

In [19]:
best_a, best_b = optimize_with_dataset(common_voice_dev)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [02:51<00:00, 10.98it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

RAW MODEL WER: 0.1724

--- Step 2: Grid Search (30 combinations) ---
Alpha    | Beta     | WER
-----------------------------------
0.3      | 1.0      | 0.1388
0.3      | 2.0      | 0.1418
0.3      | 3.0      | 0.1497
0.3      | 4.0      | 0.1634
0.3      | 5.0      | 0.1871
0.3      | 7.0      | 0.2546
0.5      | 1.0      | 0.1348
0.5      | 2.0      | 0.1335
0.5      | 3.0      | 0.1357
0.5      | 4.0      | 0.1437
0.5      | 5.0      | 0.1560
0.5      | 7.0      | 0.2085
0.7      | 1.0      | 0.1380
0.7      | 2.0      | 0.1351
0.7      | 3.0      | 0.1335
0.7      | 4.0      | 0.1353
0.7      | 5.0      | 0.1409
0.7      | 7.0      | 0.1773
0.9      | 1.0      | 0.1451
0.9      | 2.0      | 0.1406
0.9      | 3.0      | 0.1384
0.9      | 4.0      | 0.1348
0.9      | 5.0      | 0.1346
0.9      | 7.0      | 0.1508
1.1      | 1.0      | 0.1557
1.1      | 2.0      | 0.1489
1.1      | 3.0      | 0.1447
1.1      | 4.0      | 0.1409
1.1      | 5.0      | 0.1387
1.1      | 7.0      | 0.1400

#### Trigrams Mid Reduction

In [22]:
best_a, best_b = optimize_with_dataset(common_voice_dev)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [02:58<00:00, 10.54it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

RAW MODEL WER: 0.1724

--- Step 2: Grid Search (30 combinations) ---
Alpha    | Beta     | WER
-----------------------------------
0.3      | 1.0      | 0.1384
0.3      | 2.0      | 0.1405
0.3      | 3.0      | 0.1485
0.3      | 4.0      | 0.1608
0.3      | 5.0      | 0.1849
0.3      | 7.0      | 0.2533
0.5      | 1.0      | 0.1334
0.5      | 2.0      | 0.1327
0.5      | 3.0      | 0.1348
0.5      | 4.0      | 0.1425
0.5      | 5.0      | 0.1568
0.5      | 7.0      | 0.2066
0.7      | 1.0      | 0.1354
0.7      | 2.0      | 0.1341
0.7      | 3.0      | 0.1326
0.7      | 4.0      | 0.1336
0.7      | 5.0      | 0.1402
0.7      | 7.0      | 0.1750
0.9      | 1.0      | 0.1430
0.9      | 2.0      | 0.1382
0.9      | 3.0      | 0.1362
0.9      | 4.0      | 0.1341
0.9      | 5.0      | 0.1348
0.9      | 7.0      | 0.1524
1.1      | 1.0      | 0.1546
1.1      | 2.0      | 0.1489
1.1      | 3.0      | 0.1440
1.1      | 4.0      | 0.1408
1.1      | 5.0      | 0.1382
1.1      | 7.0      | 0.1407

#### Redcued, fourgram

In [12]:
best_a, best_b = optimize_with_dataset(common_voice_dev)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [03:26<00:00,  9.12it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

RAW MODEL WER: 0.1722

--- Step 2: Grid Search (30 combinations) ---
Alpha    | Beta     | WER
-----------------------------------
0.3      | 1.0      | 0.1375
0.3      | 2.0      | 0.1408
0.3      | 3.0      | 0.1492
0.3      | 4.0      | 0.1652
0.3      | 5.0      | 0.1913
0.3      | 7.0      | 0.2634
0.5      | 1.0      | 0.1335
0.5      | 2.0      | 0.1324
0.5      | 3.0      | 0.1351
0.5      | 4.0      | 0.1444
0.5      | 5.0      | 0.1625
0.5      | 7.0      | 0.2159
0.7      | 1.0      | 0.1359
0.7      | 2.0      | 0.1334
0.7      | 3.0      | 0.1316
0.7      | 4.0      | 0.1329
0.7      | 5.0      | 0.1401
0.7      | 7.0      | 0.1815
0.9      | 1.0      | 0.1418
0.9      | 2.0      | 0.1388
0.9      | 3.0      | 0.1352
0.9      | 4.0      | 0.1330
0.9      | 5.0      | 0.1337
0.9      | 7.0      | 0.1559
1.1      | 1.0      | 0.1542
1.1      | 2.0      | 0.1496
1.1      | 3.0      | 0.1442
1.1      | 4.0      | 0.1396
1.1      | 5.0      | 0.1372
1.1      | 7.0      | 0.1400

#### Reduced, trigram, actual split, tokenised + unigrams

In [14]:
best_a, best_b = optimize_with_dataset(common_voice_dev)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [03:18<00:00,  9.49it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

RAW MODEL WER: 0.1722

--- Step 2: Grid Search (30 combinations) ---
Alpha    | Beta     | WER
-----------------------------------
0.3      | 1.0      | 0.1374
0.3      | 2.0      | 0.1406
0.3      | 3.0      | 0.1479
0.3      | 4.0      | 0.1649
0.3      | 5.0      | 0.1925
0.3      | 7.0      | 0.2605
0.5      | 1.0      | 0.1331
0.5      | 2.0      | 0.1328
0.5      | 3.0      | 0.1358
0.5      | 4.0      | 0.1433
0.5      | 5.0      | 0.1607
0.5      | 7.0      | 0.2135
0.7      | 1.0      | 0.1361
0.7      | 2.0      | 0.1337
0.7      | 3.0      | 0.1314
0.7      | 4.0      | 0.1333
0.7      | 5.0      | 0.1399
0.7      | 7.0      | 0.1814
0.9      | 1.0      | 0.1425
0.9      | 2.0      | 0.1390
0.9      | 3.0      | 0.1357
0.9      | 4.0      | 0.1333
0.9      | 5.0      | 0.1339
0.9      | 7.0      | 0.1563
1.1      | 1.0      | 0.1532
1.1      | 2.0      | 0.1488
1.1      | 3.0      | 0.1440
1.1      | 4.0      | 0.1401
1.1      | 5.0      | 0.1369
1.1      | 7.0      | 0.1419

##### Reduced Vocabulary with actual spliuts, tokenised and 4 grams.

In [17]:
best_a, best_b = optimize_with_dataset(common_voice_dev)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [02:57<00:00, 10.61it/s]
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

RAW MODEL WER: 0.1722

Alpha    | Beta     | WER
-----------------------------------

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 2.0      | 0.1429
0.85     | 3.0      | 0.1398

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 4.0      | 0.1394
0.9      | 2.0      | 0.1454

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 3.0      | 0.1413
0.9      | 4.0      | 0.1402

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 2.0      | 0.1465
0.95     | 3.0      | 0.1433

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 4.0      | 0.1417

--- Optimization Result ---
Best Alpha: 0.85
Best Beta:  4.0
Best WER:   0.1394 (Reduction of 0.0328)

#### W2v tokenised but with actual data splits

In [24]:
best_a, best_b = optimize_with_dataset(common_voice_dev)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [02:50<00:00, 11.04it/s]
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

RAW MODEL WER: 0.1709

Alpha    | Beta     | WER
-----------------------------------

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 2.0      | 0.1435
0.85     | 3.0      | 0.1401

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 4.0      | 0.1384

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 2.0      | 0.1455

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 3.0      | 0.1427

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 4.0      | 0.1390

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 2.0      | 0.1468

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 3.0      | 0.1442

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 4.0      | 0.1409

--- Optimization Result ---
Best Alpha: 0.85
Best Beta:  4.0
Best WER:   0.1384 (Reduction of 0.0325)

#### Standard w2v2-bert + LM

In [ ]:
best_a, best_b = optimize_with_dataset(common_voice_test)

--- Step 1: Generating Logits for 1660 samples ---

100%|██████████| 1660/1660 [02:36<00:00, 10.60it/s]
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

RAW MODEL WER: 0.1390

Alpha    | Beta     | WER
-----------------------------------

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 2.0      | 0.0979
0.85     | 3.0      | 0.0974

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 4.0      | 0.0984
0.9      | 2.0      | 0.0995

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 3.0      | 0.0973

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 4.0      | 0.0980

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 2.0      | 0.0996

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 3.0      | 0.0992
0.95     | 4.0      | 0.0979

--- Optimization Result ---
Best Alpha: 0.9
Best Beta:  3.0
Best WER:   0.0973 (Reduction of 0.0417)

#### Tokenised w2v2-bert + lm

In [17]:
best_a, best_b = optimize_with_dataset(common_voice_test)

--- Step 1: Generating Logits for 1660 samples ---

100%|██████████| 1660/1660 [02:35<00:00, 10.67it/s]

RAW MODEL WER: 0.1256

Alpha    | Beta     | WER
-----------------------------------

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 2.0      | 0.0886
0.85     | 3.0      | 0.0880

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.

0.85     | 4.0      | 0.0881

Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.

0.9      | 2.0      | 0.0891

Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 3.0      | 0.0884

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 4.0      | 0.0881
0.95     | 2.0      | 0.0898

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 3.0      | 0.0886

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 4.0      | 0.0878

--- Optimization Result ---
Best Alpha: 0.95
Best Beta:  4.0
Best WER:   0.0878 (Reduction of 0.0378)

### Tokenised + Processed

In [15]:
best_a, best_b = optimize_with_dataset(common_voice_test)

--- Step 1: Generating Logits for 1660 samples ---

100%|██████████| 1660/1660 [02:58<00:00,  9.32it/s]
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

RAW MODEL WER: 0.1256

Alpha    | Beta     | WER
-----------------------------------
0.85     | 2.0      | 0.0889

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 3.0      | 0.0880

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 4.0      | 0.0881

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 2.0      | 0.0889

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 3.0      | 0.0884

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 4.0      | 0.0882

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 2.0      | 0.0896

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 3.0      | 0.0885
0.95     | 4.0      | 0.0878

--- Optimization Result ---
Best Alpha: 0.95
Best Beta:  4.0
Best WER:   0.0878 (Reduction of 0.0378)

### Vanilla CV+MASRI W2v2 + Highly Processed KenLM

In [27]:
# Run with the new kenlm. The rest used the older one
best_a, best_b = optimize_with_dataset(common_voice_test)

--- Step 1: Generating Logits for 1660 samples ---

100%|██████████| 1660/1660 [03:06<00:00,  8.90it/s]
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

RAW MODEL WER: 0.1141

Alpha    | Beta     | WER
-----------------------------------

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 2.0      | 0.0808

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 3.0      | 0.0807

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 4.0      | 0.0809

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 2.0      | 0.0808

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 3.0      | 0.0808

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 4.0      | 0.0812
0.95     | 2.0      | 0.0814

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 3.0      | 0.0809
0.95     | 4.0      | 0.0812

--- Optimization Result ---
Best Alpha: 0.85
Best Beta:  3.0
Best WER:   0.0807 (Reduction of 0.0334)

In [38]:
# Run the process
best_a, best_b = optimize_with_dataset(common_voice_test)

--- Step 1: Generating Logits for 1660 samples ---

100%|██████████| 1660/1660 [02:39<00:00, 10.41it/s]
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

RAW MODEL WER: 0.1141

Alpha    | Beta     | WER
-----------------------------------

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 2.0      | 0.0807
0.85     | 3.0      | 0.0805

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 4.0      | 0.0808

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 2.0      | 0.0807

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 3.0      | 0.0806
0.9      | 4.0      | 0.0810

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 2.0      | 0.0812

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 3.0      | 0.0806

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 4.0      | 0.0809

--- Optimization Result ---
Best Alpha: 0.85
Best Beta:  3.0
Best WER:   0.0805 (Reduction of 0.0336)

In [36]:
# Run the optimization
train_subset = common_voice_train.shuffle(seed=42).select(range(2000))

# Run the same optimization function on this subset
best_alpha_train, best_beta_train = optimize_with_dataset(train_subset)

print(f"Parameters tuned on Train: Alpha {best_alpha_train}, Beta {best_beta_train}")

--- Step 1: Generating Logits for 2000 samples ---

100%|██████████| 2000/2000 [02:52<00:00, 11.62it/s]

RAW MODEL WER: 0.0370

Alpha    | Beta     | WER
-----------------------------------

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 2.0      | 0.0396

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.85     | 3.0      | 0.0396
0.85     | 4.0      | 0.0393

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 2.0      | 0.0400

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 3.0      | 0.0402

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.9      | 4.0      | 0.0401

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 2.0      | 0.0411

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 3.0      | 0.0407

Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

0.95     | 4.0      | 0.0404

--- Optimization Result ---
Best Alpha: 0.85
Best Beta:  4.0
Best WER:   0.0393 (Reduction of -0.0023)
Parameters tuned on Train: Alpha 0.85, Beta 4.0

## Other Experiments

#### Raw Model

In [40]:
import torch
from pathlib import Path
from transformers import Wav2Vec2BertForCTC, Wav2Vec2BertProcessor
from jiwer import wer, cer  # <--- Added cer import
from tqdm import tqdm

# 1. Setup
base_path = Path(".") 
my_model_path = base_path / "Runs" / "checkpoint-5690"
device = "cuda" if torch.cuda.is_available() else "cpu"

# 2. Load Model and Processor
model = Wav2Vec2BertForCTC.from_pretrained(my_model_path).to(device)
processor = Wav2Vec2BertProcessor.from_pretrained(my_model_path)
model.eval()

def evaluate_raw_model(dataset):
    all_ground_truths = []
    greedy_preds = []

    print(f"--- Evaluating {len(dataset)} samples (Greedy Decoding) ---")
    
    for i in tqdm(range(len(dataset))):
        batch = dataset[i]
        audio = batch["audio"]["array"] 
        
        # Preprocess
        inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
        input_features = inputs.input_features.to(device)

        # Inference
        with torch.no_grad():
            logits = model(input_features).logits
        
        # Greedy Decode (Argmax)
        pred_ids = torch.argmax(logits, dim=-1)
        transcription = processor.batch_decode(pred_ids)[0]
        
        # Store results
        greedy_preds.append(transcription.lower())
        all_ground_truths.append(batch["sentence"].lower())

    # --- Metrics Calculation ---
    final_wer = wer(all_ground_truths, greedy_preds)
    final_cer = cer(all_ground_truths, greedy_preds)
    
    print("\n" + "="*35)
    print(f"RAW MODEL RESULTS:")
    print(f"WER: {final_wer:.4f} ({final_wer*100:.2f}%)")
    print(f"CER: {final_cer:.4f} ({final_cer*100:.2f}%)")
    print("="*35)
    
    # Sanity Check
    print("\nSample Transcriptions:")
    for j in range(min(2, len(all_ground_truths))):
        print(f"REF: {all_ground_truths[j]}")
        print(f"HYP: {greedy_preds[j]}")
        print("-" * 10)

    return {"wer": final_wer, "cer": final_cer}

In [ ]:
import torch
from pathlib import Path
from transformers import Wav2Vec2BertForCTC, Wav2Vec2BertProcessor
from jiwer import wer, cer
from tqdm import tqdm
import malti.tokeniser  # Import the malti library

# 1. Setup
base_path = Path(".") 
my_model_path = base_path / "Runs" / "SplitRunReduced" / "checkpoint-2780"
device = "cuda" if torch.cuda.is_available() else "cpu"

# Initialize the Maltese Detokenizer
malti_tokenizer = malti.tokeniser.KMTokeniser()

# 2. Load Model and Processor
model = Wav2Vec2BertForCTC.from_pretrained(my_model_path).to(device)
processor = Wav2Vec2BertProcessor.from_pretrained(my_model_path)
model.eval()

def evaluate_raw_model(dataset, print_all=False):
    all_ground_truths = []
    greedy_preds = []
    mismatches = []  # List to store errors for review

    print(f"--- Evaluating {len(dataset)} samples ---")
    
    for i in tqdm(range(len(dataset))):
        batch = dataset[i]
        audio = batch["audio"]["array"] 
        
        inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
        input_features = inputs.input_features.to(device)

        with torch.no_grad():
            logits = model(input_features).logits
        
        pred_ids = torch.argmax(logits, dim=-1)
        raw_transcription = processor.batch_decode(pred_ids)[0].lower()
        raw_reference = batch["sentence"].lower()

        # Detokenization
        detok_transcription = malti_tokenizer.detokenise(raw_transcription.split())
        detok_reference = malti_tokenizer.detokenise(raw_reference.split())
        
        greedy_preds.append(detok_transcription)
        all_ground_truths.append(detok_reference)

        # Track Mismatches
        if detok_transcription != detok_reference:
            mismatches.append({
                "index": i,
                "ref": detok_reference,
                "hyp": detok_transcription
            })
        
        # Optional: Print every single result as it happens
        if print_all:
            print(f"[{i}] REF: {detok_reference}")
            print(f"[{i}] HYP: {detok_transcription}")
            print("-" * 20)

    # --- Metrics ---
    final_wer = wer(all_ground_truths, greedy_preds)
    final_cer = cer(all_ground_truths, greedy_preds)
    
    # --- Final Report ---
    print("\n" + "="*40)
    print(f"RESULTS Summary")
    print(f"Total Samples: {len(dataset)}")
    print(f"Perfect Matches: {len(dataset) - len(mismatches)}")
    print(f"Mismatches: {len(mismatches)}")
    print(f"WER: {final_wer:.4f} | CER: {final_cer:.4f}")
    print("="*40)
    
    if len(mismatches) > 0 and not print_all:
        print("\n--- DETAILED MISMATCHES ---")
        for m in mismatches:
            print(f"Sample #{m['index']}")
            print(f"  REF: {m['ref']}")
            print(f"  HYP: {m['hyp']}")
            print(f"  diff: {'[Length Mismatch]' if len(m['ref']) != len(m['hyp']) else ''}")
            print("-" * 15)

    return {"wer": final_wer, "cer": final_cer, "mismatches": mismatches}

Extracting unigrams and building decoder...

Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
Exception ignored in: <bound method IPythonKernel._clean_thread_parent_frames of <ipykernel.ipkernel.IPythonKernel object at 0x77a51045b610>>
Traceback (most recent call last):
  File "/home/ian/miniconda3/envs/w2v2_KenLM/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 781, in _clean_thread_parent_frames
    def _clean_thread_parent_frames(
KeyboardInterrupt:

In [21]:
import torch
from pathlib import Path
from transformers import Wav2Vec2BertForCTC, Wav2Vec2BertProcessor
from pyctcdecode import build_ctcdecoder
from jiwer import wer, cer
from tqdm import tqdm
import malti.tokeniser

# 1. Setup
base_path = Path(".") 
my_model_path = base_path / "Runs" / "SplitRunReducedButMid" / "checkpoint-2780"
LM_PATH = str(base_path / "4_tok_red.bin")
ARPA_PATH = str(base_path / "3_tok_red.arpa")
device = "cuda" if torch.cuda.is_available() else "cpu"

# Initialize Maltese Detokenizer
malti_tokenizer = malti.tokeniser.KMTokeniser()

# 2. Load Model and Processor
model = Wav2Vec2BertForCTC.from_pretrained(my_model_path).to(device)
processor = Wav2Vec2BertProcessor.from_pretrained(my_model_path)
model.eval()

# 3. Prepare Decoder Vocab and Unigrams
vocab = processor.tokenizer.get_vocab()
sorted_vocab = [k for k, v in sorted(vocab.items(), key=lambda item: item[1])]

def get_unigram_list(arpa_path):
    unigrams = []
    with open(arpa_path, "r") as f:
        is_unigram_section = False
        for line in f:
            if "\\1-grams:" in line:
                is_unigram_section = True
                continue
            if "\\2-grams:" in line or line.startswith("\\end\\"):
                break
            if is_unigram_section:
                parts = line.strip().split()
                if len(parts) >= 2:
                    word = parts[1]
                    if word not in ["<s>", "</s>", "<unk>"]:
                        unigrams.append(word)
    return unigrams

print("Extracting unigrams...")
unigrams = get_unigram_list(ARPA_PATH)

def evaluate_with_kenlm(dataset, alpha=0.85, beta=4.0):
    all_ground_truths = []
    greedy_preds = []
    kenlm_preds = []
    
    # Initialize Decoder
    decoder = build_ctcdecoder(
        labels=sorted_vocab,
        kenlm_model_path=LM_PATH,
        unigrams=unigrams,
        alpha=alpha,
        beta=beta
    )

    print(f"--- Evaluating {len(dataset)} samples with KenLM ---")
    
    for i in tqdm(range(len(dataset))):
        batch = dataset[i]
        audio = batch["audio"]["array"] 
        
        inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
        input_features = inputs.input_features.to(device)

        with torch.no_grad():
            logits = model(input_features).logits
        
        # 1. Greedy Decoding
        pred_ids = torch.argmax(logits, dim=-1)
        raw_greedy = processor.batch_decode(pred_ids)[0].lower()
        
        # 2. KenLM Decoding (Logits need to be CPU numpy for pyctcdecode)
        logits_numpy = logits.cpu().numpy()[0]
        raw_kenlm = decoder.decode(logits_numpy).lower()

        # 3. Reference
        raw_reference = batch["sentence"].lower()

        # --- Detokenization (The "Fair" Step) ---
        detok_ref = malti_tokenizer.detokenise(raw_reference.split())
        detok_greedy = malti_tokenizer.detokenise(raw_greedy.split())
        detok_kenlm = malti_tokenizer.detokenise(raw_kenlm.split())
        
        all_ground_truths.append(detok_ref)
        greedy_preds.append(detok_greedy)
        kenlm_preds.append(detok_kenlm)

    # --- Metrics Calculation on Detokenized Strings ---
    base_wer = wer(all_ground_truths, greedy_preds)
    base_cer = cer(all_ground_truths, greedy_preds)
    
    k_wer = wer(all_ground_truths, kenlm_preds)
    k_cer = cer(all_ground_truths, kenlm_preds)

    # --- Final Report ---
    print("\n" + "="*50)
    print(f"{'Metric (Detokenized)':<20} | {'Raw Model':<12} | {'With KenLM':<12}")
    print("-" * 50)
    print(f"{'WER':<20} | {base_wer:<12.4f} | {k_wer:<12.4f}")
    print(f"{'CER':<20} | {base_cer:<12.4f} | {k_cer:<12.4f}")
    print("="*50)
    
    return {"greedy_wer": base_wer, "kenlm_wer": k_wer}

Extracting unigrams...

#### Evaluating impact of n-grams

In [22]:
#Fourgram
evaluate_with_kenlm(common_voice_dev,alpha=0.7, beta=3.0)

Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Evaluating 1883 samples with KenLM ---

100%|██████████| 1883/1883 [05:56<00:00,  5.28it/s]

==================================================
Metric (Detokenized) | Raw Model    | With KenLM
--------------------------------------------------
WER                  | 0.1989       | 0.1530
CER                  | 0.0516       | 0.0477
==================================================

{'greedy_wer': 0.19887904538058218, 'kenlm_wer': 0.1529560658108841}

In [20]:
#Bigrams
evaluate_with_kenlm(common_voice_dev,alpha=0.5, beta=2.0)

Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Evaluating 1883 samples with KenLM ---

100%|██████████| 1883/1883 [03:09<00:00,  9.95it/s]

==================================================
Metric (Detokenized) | Raw Model    | With KenLM
--------------------------------------------------
WER                  | 0.1989       | 0.1549
CER                  | 0.0516       | 0.0469
==================================================

{'greedy_wer': 0.19887904538058218, 'kenlm_wer': 0.1548845898873019}

#### Detokenised on Test sets

In [20]:
# Common Voice
evaluate_with_kenlm(common_voice_test,alpha=0.7, beta=3.0)

Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Evaluating 1224 samples with KenLM ---

100%|██████████| 1224/1224 [01:55<00:00, 10.62it/s]

==================================================
Metric (Detokenized) | Raw Model    | With KenLM
--------------------------------------------------
WER                  | 0.1001       | 0.0699
CER                  | 0.0222       | 0.0173
==================================================

{'greedy_wer': 0.10009225092250923, 'kenlm_wer': 0.069880073800738}

In [19]:
# MASRI Only
evaluate_with_kenlm(common_voice_test,alpha=0.7, beta=3.0)

Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Evaluating 668 samples with KenLM ---

100%|██████████| 668/668 [01:44<00:00,  6.40it/s]

==================================================
Metric (Detokenized) | Raw Model    | With KenLM
--------------------------------------------------
WER                  | 0.3341       | 0.2669
CER                  | 0.0979       | 0.0948
==================================================

{'greedy_wer': 0.33408352088022003, 'kenlm_wer': 0.26694173543385846}

In [20]:
# Combined
evaluate_with_kenlm(common_voice_test,alpha=0.7, beta=3.0)

Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Evaluating 1892 samples with KenLM ---

100%|██████████| 1892/1892 [04:10<00:00,  7.54it/s]

==================================================
Metric (Detokenized) | Raw Model    | With KenLM
--------------------------------------------------
WER                  | 0.2124       | 0.1644
CER                  | 0.0581       | 0.0541
==================================================

{'greedy_wer': 0.21235752849430115, 'kenlm_wer': 0.1644271145770846}

#### Vocab tests

In [26]:
# Split run (uncleaned vocab or barely)
evaluate_with_kenlm(common_voice_dev,alpha=0.7, beta=3.0)

Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Evaluating 1883 samples with KenLM ---

100%|██████████| 1883/1883 [06:35<00:00,  4.76it/s]

==================================================
Metric (Detokenized) | Raw Model    | With KenLM
--------------------------------------------------
WER                  | 0.1979       | 0.1536
CER                  | 0.0518       | 0.0483
==================================================

{'greedy_wer': 0.19791478334237328, 'kenlm_wer': 0.15361899596215273}

In [24]:
# Mid Vocabulary (final vocab used)
evaluate_with_kenlm(common_voice_dev,alpha=0.7, beta=3.0)

Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Evaluating 1883 samples with KenLM ---

100%|██████████| 1883/1883 [04:31<00:00,  6.94it/s]

==================================================
Metric (Detokenized) | Raw Model    | With KenLM
--------------------------------------------------
WER                  | 0.1989       | 0.1526
CER                  | 0.0516       | 0.0478
==================================================

{'greedy_wer': 0.19887904538058218, 'kenlm_wer': 0.15259446754655578}

In [21]:
# Split Run reduced
evaluate_with_kenlm(common_voice_dev,alpha=0.7, beta=3.0)

Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Evaluating 1883 samples with KenLM ---

100%|██████████| 1883/1883 [04:12<00:00,  7.45it/s]

==================================================
Metric (Detokenized) | Raw Model    | With KenLM
--------------------------------------------------
WER                  | 0.2012       | 0.1546
CER                  | 0.0524       | 0.0481
==================================================

{'greedy_wer': 0.20122943409871633, 'kenlm_wer': 0.1545832580003616}

#### Big Model - Common Voice Only

In [41]:
evaluate_raw_model(common_voice_test)

--- Evaluating 1224 samples (Greedy Decoding) ---

100%|██████████| 1224/1224 [02:05<00:00,  9.74it/s]

===================================
RAW MODEL RESULTS:
WER: 0.0546 (5.46%)
CER: 0.0117 (1.17%)
===================================

Sample Transcriptions:
REF: dan ma sar qatt
HYP: dan ma sar qatt
----------
REF: min jaf kif u biex se jimlewha
HYP: min jaf kif u biex se jimlewha
----------

{'wer': 0.054610255231087604, 'cer': 0.011733092996862274}

#### Big Model - MASRI Only

In [23]:
evaluate_raw_model(common_voice_test)

--- Evaluating 668 samples (Greedy Decoding) ---

100%|██████████| 668/668 [01:11<00:00,  9.29it/s]

===================================
RAW MODEL RESULTS:
WER: 0.2262 (22.62%)
CER: 0.0729 (7.29%)
===================================

Sample Transcriptions:
REF: maskarat tini perlina għax warajk għandek xadina minflok waħda tini tnejn biex warajk ma jkollok xejn
HYP: maskerat tini perlina għax warajt għandek xadina minflok waħda tini tnejn biex warajt ma jkollok xejn
----------
REF: eħe f' dan is-suġġett se nagħtu ħarsa lejn in-novelli u r-rumanzi tal-awturi maltin kosmopolitani jiġifieri li bdew jiktbu
HYP: eħe f' dan is-suġġett se nagħtu ħarsa lejn in-novelli u r-rumanzi tal-awturi maltin kosmopolitan jiġifieri li bdew jiktbu
----------

{'wer': 0.22616845480330497, 'cer': 0.07290320197953983}

##### Bid model

In [23]:
evaluate_raw_model(common_voice_test)

--- Evaluating 1892 samples (Greedy Decoding) ---

100%|██████████| 1892/1892 [03:11<00:00,  9.88it/s]

===================================
RAW MODEL RESULTS:
WER: 0.1374 (13.74%)
CER: 0.0408 (4.08%)
===================================

Sample Transcriptions:
REF: maskarat tini perlina għax warajk għandek xadina minflok waħda tini tnejn biex warajk ma jkollok xejn
HYP: maskerat tini perlina għax warajt għandek xadina minflok waħda tini tnejn biex warajt ma jkollok xejn
----------
REF: eħe f' dan is-suġġett se nagħtu ħarsa lejn in-novelli u r-rumanzi tal-awturi maltin kosmopolitani jiġifieri li bdew jiktbu
HYP: eħe f' dan is-suġġett se nagħtu ħarsa lejn in-novelli u r-rumanzi tal-awturi maltin kosmopolitan jiġifieri li bdew jiktbu
----------

{'wer': 0.13738323317665257, 'cer': 0.040773209432804415}

##### Mid test for sanity.

In [33]:
evaluate_raw_model(common_voice_test)

--- Evaluating 1892 samples (Greedy Decoding) ---

100%|██████████| 1892/1892 [02:58<00:00, 10.60it/s]

===================================
RAW MODEL RESULTS:
WER: 0.1816 (18.16%)
CER: 0.0575 (5.75%)
===================================

Sample Transcriptions:
REF: maskarat tini perlina għax warajk għandek xadina minflok waħda tini tnejn biex warajk ma jkollok xejn
HYP: maskarat ini perlina għax warajk għandek x' għdina minflok waħda tini tnejn ix warajk ma jkollok xejn
----------
REF: eħe f' dan is- suġġett se nagħtu ħarsa lejn in- novelli u r- rumanzi tal- awturi maltin kosmopolitani jiġifieri li bdew jiktbu
HYP: eħe f' dan is- suġġett se nagħtu ħarsa lejn n- novelli u r- rumanzi ta' l- awturi maltin kosmopolitan jiġifieri bdew jiktbu
----------

{'wer': 0.18158334599604922, 'cer': 0.05749326951839665}

##### Split Run Reduced Tokenised

In [24]:
evaluate_raw_model(common_voice_test)

--- Evaluating 1892 samples ---

100%|██████████| 1892/1892 [02:51<00:00, 11.02it/s]

========================================
RESULTS Summary
Total Samples: 1892
Perfect Matches: 776
Mismatches: 1116
WER: 0.2099 | CER: 0.0580
========================================

--- DETAILED MISMATCHES ---
Sample #0
  REF: maskarat tini perlina għax warajk għandek xadina minflok waħda tini tnejn biex warajk ma jkollok xejn
  HYP: maskarat ini perlina għax warajk għandek x'għdina minflok waħda tini tnejn ix warajk ma jkollok xejn
  diff: [Length Mismatch]
---------------
Sample #1
  REF: eħe f'dan is-suġġett se nagħtu ħarsa lejn in-novelli u r-rumanzi tal-awturi maltin kosmopolitani jiġifieri li bdew jiktbu
  HYP: eħe f'dan is-suġġett se nagħtu ħarsa lejn n-novelli u r-rumanzi ta' l-awturi maltin kosmopolitan jiġifieri bdew jiktbu
  diff: [Length Mismatch]
---------------
Sample #2
  REF: mis-snin disgħin tas-seklu għoxrin issa meta ngħid kosmopolitani xi rrid infisser
  HYP: mis-snin disgħin tas-seklu għoxrin issa meta ngħid kosmopolitani x'irrid infisser
  diff:
---------------
Sample #3
  REF: mela e kosmopolitani dawn l-awturi warrbu l-fruntieri
  HYP: mela e b'kosmopolitan dawn l-awturi gwarrbu l-frontieri
  diff: [Length Mismatch]
---------------
Sample #4
  REF: u bdejna ma bqajniex iktar bil-mentalità lokalizzata fir-raħal malti
  HYP: u bdejna ma bqajniex iktar bil-mentalità lokalizzata fir-raħal malti imma
  diff: [Length Mismatch]
---------------
Sample #5
  REF: addottaw kuxjenza universali per eżempju missni ngħid li t-temi
  HYP: adottaw kuxjenza universali pereżempju nista' ngħid li it-tehmi
  diff:
---------------
Sample #6
  REF: hemm f'dawn in-novelli u rumanzi huma temi li irrispettivament mill-post
  HYP: ehm f'dawn in-novelli u r-rumanzi huma temili irrispettivament mill-post
  diff:
---------------
Sample #7
  REF: mill-pajjiż min-min-nies mill-karattri sewwa fil-fin-novelli u fir-rumanzi
  HYP: mil-pajjiż minn min-nies mill-karattri sewwa fil fil novelli u fir-rumanzi
  diff:
---------------
Sample #8
  REF: hemm huma komuni pereżempju jekk qed nitkellmu fuq l-imħabba l-abort e t-terroriżmu l-vjolenza
  HYP: ehm huma komuni pereżempju jekk qed nitkellmu fuq l-imħabba l-abbords e terroriżmu l-vjolenza
  diff: [Length Mismatch]
---------------
Sample #9
  REF: ta' dawn huma temi li m'għandekx m'għandux x'jaqsam inti l-pajjiż fejn qiegħed u
  HYP: ta daw huma temili m'għandikx m'għandux x'jaqsam int il-pajjiż fejn qiegħed
  diff: [Length Mismatch]
---------------
Sample #10
  REF: issa jingħażlu minnhom kemm fil-kontenut kif ukoll fl-istil għaliex qed ngħid hekk hemm
  HYP: i n se jingħażlu minhom kemm fil-ontenut kif ukoll fl-istil għaliex qed ngħid hekk em
  diff: [Length Mismatch]
---------------
Sample #11
  REF: din hija narrativa fejn għandek per eżempju biex nagħti eżempju narratur li ma jiġġudikax
  HYP: din hija narrattiva fejn għandek pereżempju biex nagħti eżempju narratur li ma jiġġudikax
  diff:
---------------
Sample #12
  REF: allura hemmhekk meta għandek narratur li ma jiġġudikax dik setgħet in-nuqqas ta' ġudizzju seta' kien
  HYP: allura hemmhekk meta itigħandek naraturli a jiġġudikax dik setgħt in-nuqqas ta' ġudizzju seta' kien
  diff: [Length Mismatch]
---------------
Sample #13
  REF: hemm bdew jesperjenzaw kulturi oħra jiġifieri ma'
  HYP: emm bdew jesperjenzaw kulturi oħra jiġifieri ma
  diff: [Length Mismatch]
---------------
Sample #14
  REF: huma awturi li ħadmu barra minn malta huma awturi li għexu
  HYP: huma awturi li ħadmu barraminn malti huma awturi li għexu
  diff: [Length Mismatch]
---------------
Sample #15
  REF: hemm u kien hemm ukoll jiġifieri
  HYP: em u kien hemm ukoll jiġifieri
  diff: [Length Mismatch]
---------------
Sample #16
  REF: vera ċara f'f'dawn f'dawn dawn il-kotba li
  HYP: vera ċara f'f daw f daw f'daw il-kotba li i
  diff: [Length Mismatch]
---------------
Sample #17
  REF: li inti e trabbejt bih li ma tistax tagħmel inti dan ikun sar parti minnek
  HYP: li inti trabbejtbih li ma ma tistax tagħmel inti dan inkun sar parti minnek
  diff: [Length Mismatch]
---------------
Sample #18
  REF: allura meta inti tesperjenza xi ħaġa differenti kulturi oħra hemm inti
  HYP: allura met inti tesperjenza xi ħaġa differenti kulturi oħra em inti
  diff: [Length Mismatch]
---------------
Sample #19
  REF: hekk hu fil-fatt jien ngħid ukoll hi letteratura biex ngħid hekk li ħasdet
  HYP: hekk hu fil-fatt jien għid ukoll letteratura biex ngħidlek li li ħasdet
  diff: [Length Mismatch]
---------------
Sample #20
  REF: forsi mhux it-temi kollha ma kinux assolutament ma jiġux indi-in dirizzati kienu jissemmew
  HYP: forsi mhux it-temikollha ma kinux assolutament ma jiġux i- indirizzati kienu jissemmew
  diff: [Length Mismatch]
---------------
Sample #21
  REF: imma anka l-mod kien hemm element miżjud ta' darba fis-sens ta' hemm
  HYP: imma ankegħal mod kien hemm element miżjud ta' tabu fis-sens ta' em
  diff: [Length Mismatch]
---------------
Sample #22
  REF: il-ir-reġistru l-kliem beda jkun iktar dirett ix-xbihat beda bdew ikunu iktar espliċiti
  HYP: il-r-reġistru l-kliem beda jkun aktar dirett ixbiat bddew jkunu aktar espliċiti allura
  diff: [Length Mismatch]
---------------
Sample #23
  REF: l-awturi li qed nitkellmu fuqhom illum li huma alex vella gera
  HYP: l-awturi li qed nitkellmu fuqhom illum li huma aleks vellaġera
  diff:
---------------
Sample #24
  REF: bħal claire azzopardi hemm pierre jei meilak
  HYP: han cler rozopardi em per gaimejla
  diff: [Length Mismatch]
---------------
Sample #25
  REF: kif ukoll immanuel mifsud u ġuże stagno issa huma awturi stabiliti
  HYP: f kolli manwel mifsud i ġiż estano issa huma awturi stabbiliti
  diff: [Length Mismatch]
---------------
Sample #27
  REF: din hija t-tieni li ħa jiftaħ fetaħ l-ewwel darba
  HYP: hemm din hija t-tieni darba li ħa jiftaħ fetaħ l-ewwel darba
  diff: [Length Mismatch]
---------------
Sample #28
  REF: biex biex itemmu l-kors u f'ottubru li ġej ħa jerġa' jiftaħ il-kors
  HYP: b biex itemmu l-kors u f'ottubru li ġej ħa jerġa' jiftaħ il-kors hemm
  diff: [Length Mismatch]
---------------
Sample #29
  REF: min jixtieq japplika jista' jagħmel dan sad-dsatax ta' lulju li ġej
  HYP: min jixtieq japplika jista' jagħmel dan sa satax ta' lulju li ġejja
  diff:
---------------
Sample #30
  REF: li tixtieq insaqsik kemm bħala żagħżugħa taħseb li s-segwaċi tal-brikkuni
  HYP: li tixtieq istaqsik kemm bħala żagħżugħan taħseb li s-segwaċi tal-brikuni
  diff:
---------------
Sample #31
  REF: u għan-novità għall-novità naħseb li qed jisimgħu il-malti b'dak il-mod
  HYP: u u għan-novità naħseb il-fatt li qed jisimgħu l-malti b'dak il-mod
  diff: [Length Mismatch]
---------------
Sample #33
  REF: kelli niġi għax għandi għajnejja ħomor u jdemmgħu ħażin jien widnejja
  HYP: kelli niġi għax għandi għajnejja ħomor u jdemmgħu ħażin ji widnejja
  diff: [Length Mismatch]
---------------
Sample #35
  REF: madoff hux dejjem b'xi ħaġa jien għadni kemm ġejt bit-tifel ilbieraħ għax kellu griżmejh ħomor nar
  HYP: m'għadoffux dejjem b'xi ħaġa jien għadni kemm ġejt bit-tifel ilbieraħ għax kellu griżmejh ħomor nar
  diff: [Length Mismatch]
---------------
Sample #36
  REF: ma kemm ili li nistenna fl-aħħar imissni jien
  HYP: ma kemm ili nistenna fl-aħħar imissni jien
  diff: [Length Mismatch]
---------------
Sample #40
  REF: madoff hux dejjem b'xi ħaġa jien
  HYP: m'doffux dejjem b'xi ħaġa jien
  diff: [Length Mismatch]
---------------
Sample #42
  REF: u mbagħad meta naqrahom ġie ġieli ġew f'idejja kotba kienu jkunu differenti ħafna
  HYP: imm et meta bdejt naqrahom iel ġieli ġew f'idejja kotba kienu jkunu differenti ħafna
  diff: [Length Mismatch]
---------------
Sample #43
  REF: e jew tmur ma' tork ma' ma' tork iswed pereżempju meta tkun xi tifla dħulija
  HYP: e tmur ma torkm ma' tork iswed pereżempju meta tkun xi tifla għad dħulija
  diff: [Length Mismatch]
---------------
Sample #44
  REF: peress li konna mmorru żejt iż-żejtun u nagħmlu dawk il-siltiet bid-djaletti
  HYP: peres li konna morru żejt iż-żejtun u nagħmlu dawk il-siltiet bid-dijaletti
  diff: [Length Mismatch]
---------------
Sample #45
  REF: kien qalli issa darb' oħra meta t-għax aħna niktbuhom aħna stess jiena u ir-raġel
  HYP: kien qal li issa darb oħra meta ttiqax aħna niktbuhom aħna stess jien u r-raġel
  diff: [Length Mismatch]
---------------
Sample #46
  REF: qalli darb' oħra ridt nagħmluha peress li taż-żurrieq għax ir-raġel tiegħi minn ħal għaxaq id-djalett tiegħu mhux qawwi daqs taż-żurrieq taż-żurrieq iżjed
  HYP: għalli darba oħra ridtu nagħmluha peress li taż-żurri għax ir-raġel tej minħalaxa d-dejalett tiegħ mhux qawwi daqs ta- żri taż-urieq iżjed
  diff: [Length Mismatch]
---------------
Sample #47
  REF: qalli irrid nagħmel waħda miegħek jiena biż-
  HYP: għalli irrid nagħmel waħda miegħek jiena biż
  diff:
---------------
Sample #48
  REF: konna narawha ġieli jiena u tielgħa minn wied il-għajn għax imbagħad morna noqogħdu hemm minn wied il-għajn konna narawhom konna ngħidu ara tellagħhom illum
  HYP: konna narawha aġiel ien ħawtilha mewit lin ħax imbagħad orna noqogħdu hem mewitili konna nrahom onna ngħidu wara tallahom illum
  diff: [Length Mismatch]
---------------
Sample #49
  REF: lili kien qagħad jispjegali waqt intervista li għamiltlu li trid sena biex ittellagħhom
  HYP: lili kien qagħad jispjegali waqt intervista li għamiltlu li dik trid sena biex ittallagħhom
  diff: [Length Mismatch]
---------------
Sample #50
  REF: trid sena u mbagħad biex tara il-ħin il-ġust biex tniżżilhom
  HYP: aa biex tagħraf il-ħin il-ġust biex tniżżilhom
  diff: [Length Mismatch]
---------------
Sample #51
  REF: u għandi għandi il-ħelper miż-żurrieq paċċu pereżempju tgħidlu l-baċċu
  HYP: u għandi għandi il-helper miż-żurrieq paċċu pereżempju tgħidlu l-paċċu
  diff:
---------------
Sample #52
  REF: illi jiena orrajt forsi ma kont nafhom daħal l-ingliż imma hemm ċertu kliem
  HYP: hemm ċertu kliem illi jien rajt forsi ma kontx nafhom daħal l-ingliż imma
  diff: [Length Mismatch]
---------------
Sample #53
  REF: il-ġenituri tiegħi min-naħa l-oħra min-naħa tal-isla u għandhom affarijiet illi huma differenti
  HYP: il-ġenituri tiegħ min in-naħa l-oħa min-naħa tal-ista u għandhom affarijiet ili iduma ifferenti
  diff:
---------------
Sample #54
  REF: jiena il-il-maid tiegħi hawn miż-żurrieq nitkellmu ħafna bil-malti bejnietna
  HYP: jien għal il-il-mejt tiegħi hawn iż-żurrieq nitkellmu ħafna bil-malti bejnietna
  diff: [Length Mismatch]
---------------
Sample #55
  REF: pero niskanta emmnuni niskanta meta ċċempel lil ommha jew żewġha
  HYP: pero niskanta emmnuni niskanta meta ċċempel' il ommha jew żewġha
  diff:
---------------
Sample #56
  REF: voldieri hawn xi taqbiliet jew talb li biex iġib id-deni
  HYP: oke jew forsi xi ta iit jew tal li kie biex ibid id denni
  diff: [Length Mismatch]
---------------
Sample #57
  REF: ma tiftakarhiex lin-nanna pa tgħid xi ħaġa xi talba jew hekk waqt li qed
  HYP: u tiftakarnix in-nanna a fejin xi ħadu xi dena jew ea
  diff: [Length Mismatch]
---------------
Sample #58
  REF: tiftakarha kif kienu jinterpretawha wkoll tiftakarha kif kienu jgħiduha
  HYP: kif ta kara kif kienu jinterpretawha wkoll if takara kif kienu jgħiduha
  diff:
---------------
Sample #59
  REF: għax għidtli irranġajtha ftit tiftakar forsi
  HYP: sedt li reġajta ftit staar forsi
  diff: [Length Mismatch]
---------------
Sample #60
  REF: biex insaħħaħ il-kitba tiegħi e din id-diploma fetħitli oċean ta' kittieba u kotba
  HYP: biex insaħħaħ il-kitba tiegħi din id-diploma fetħit li oxean ta' kittieba hu kotba
  diff:
---------------
Sample #61
  REF: bil-malti irrid insaħħaħ il-malti tiegħi ukoll
  HYP: il-malti inrid insaħħaħ il-malti tiegħi ukoll
  diff: [Length Mismatch]
---------------
Sample #62
  REF: iżda mbagħad sibt sapport kbir mill-kollegi tiegħi u mil-letturi
  HYP: iżda mbagħad sibt apport kbiri mill-kollegi tiegħi u mill-letturi
  diff: [Length Mismatch]
---------------
Sample #63
  REF: u għadu għal qalbi ħafna u nikkoraġġixxi' il min huwa interessat fil-letteratura maltija
  HYP: dal qalbi ħafna u ninkoraġixxi l min u nteressad fil-letteratura maltija
  diff: [Length Mismatch]
---------------
Sample #64
  REF: u għadu għal qalbi ħafna u nikkoraġġixxi' il min huwa interessat fil-letteratura maltija
  HYP: dal-qalbi ħafna u ninkoraġixxi l min u interessad fi- letteratura maltija
  diff: [Length Mismatch]
---------------
Sample #65
  REF: grazzi lil ta' nenu the artisan baker maypole bakery
  HYP: grazzi lil tanenu di artison bejker m pol bajkery
  diff: [Length Mismatch]
---------------
Sample #66
  REF: health and beauty by browns virtu ferries
  HYP: health and buty by brawns vir too ferreys
  diff:
---------------
Sample #67
  REF: estetika the cosmetic clinic u mannarinu caterers
  HYP: estetika the cosmetic clinick u mannarino caterers
  diff: [Length Mismatch]
---------------
Sample #69
  REF: illum għoxrin ta' frar elfejn u sittax qed nintervista lil stefania fenech mill-marsa ta' sebgħa u erbgħin sena
  HYP: illum għoxrin ta' febrar elfejn u sittax qed nintervista lil sepania feneck mill-marsa ta' sebgħa u erbgħin sena
  diff: [Length Mismatch]
---------------
Sample #70
  REF: għidtli li taf xi taqbila li kontu tużaw e meta kontu tfal
  HYP: għidtli taf xi taqbila li kontu tużaw meta kontu tfal
  diff: [Length Mismatch]
---------------
Sample #71
  REF: u imma hemm likk l-iktar għax tgħid seħta bedudu jew minħabba in-nifs
  HYP: imma hemm l l-iktar għax tgħid seħħ ta bedudu jew minħabba n-nifs
  diff: [Length Mismatch]
---------------
Sample #72
  REF: jiena yanica schembri fava qed nintervista lil judith schembri
  HYP: jien anica sckembri pava qed nintervista lil judit xkembri
  diff: [Length Mismatch]
---------------
Sample #73
  REF: nostrok ħa tostorni sa ma tiġi l-mewt tiġborni
  HYP: nostroka ta' stormi sa ma tiġi l-mewtiġbormi
  diff: [Length Mismatch]
---------------
Sample #75
  REF: m'hekk lil ruth castillo minn hawnhekk pero se ngħaddu għal suġġett illi
  HYP: back lil ruth castello minn hawnhekk pero se ngħaddu għall suġġett illi
  diff: [Length Mismatch]
---------------
Sample #77
  REF: e kellna hawn mistiedna letturi marbuta mad-diploma
  HYP: kellna mistiedna letturi marbuta mad-diploma
  diff: [Length Mismatch]
---------------
Sample #78
  REF: fil-letteratura maltija u e miegħi illum stidint hemm
  HYP: fil-letteratura maltijat u miegħi illum stident emm
  diff: [Length Mismatch]
---------------
Sample #79
  REF: għandna personaġġ ieħor interessanti b'aleander vella gregory illi huwa kompożitur kif ukoll mużiċist
  HYP: għandna personaġġ ieħor interessanti iwa alexander vella gregri li huwa kompożitur kif ukoll mużiċist
  diff:
---------------
Sample #80
  REF: hemm u dejjem tiskopri jiġifieri grazzi għall-programm ukoll jirnexxilna illi
  HYP: emm u dejjem tiskopry jiġifieri przzjal programm koll irnexxilna illi
  diff: [Length Mismatch]
---------------
Sample #81
  REF: u inti ukoll hemm tagħti il-krettu li jisħoqq il-lirika fil-kanzunetta
  HYP: u inti wkoll hemm tati il-krettu li jismu l-lirika fil-kanzunetta
  diff: [Length Mismatch]
---------------
Sample #82
  REF: hemm forsi nibdew nitkellmu dwar meta bdejt tgħid il-lingwaġġ
  HYP: emm se nibdeħ nitkellmu dwar meta bdejt għid il-lingwaġġ
  diff: [Length Mismatch]
---------------
Sample #84
  REF: allura il-mużika u l-lingwa hemm x'għandu x'jaqsam fil-letteratura maltija jiġifieri int hawnhekk
  HYP: allura il-mużika u l-lingw x'għandux x jaqsam fil-letteratura maltija jġifieri inti hawnhekk
  diff: [Length Mismatch]
---------------
Sample #85
  REF: kif semmejtli wkoll fil-fin-noti tiegħek illi ir-rwol tiegħek issa hawnhekk f'dan il-kors
  HYP: kif semmejtli wkoll fil-fin-noti tiegħek illi ir-rwol tiegħek issa hawnhekk f'dan il-cors
  diff:
---------------
Sample #86
  REF: ħa tidħol ukoll il-mużika għax għandek il-il-lirika u l-mużika jiġifieri t-tnejn
  HYP: ħajt idħol ukoll il-mużika ħax għandek l-lirika u l-mużika ġid tnejn
  diff: [Length Mismatch]
---------------
Sample #87
  REF: tiegħi għaliex hemm tajjeb illi forsi nkunu daqq nafu daqsxejn il-background
  HYP: għaliex hemm tajeb illi forsi nkunud nafu daqsxejn il-background
  diff: [Length Mismatch]
---------------
Sample #88
  REF: anki meta bdejt nara dawn ir-ritratti għid bħal speċi hemm
  HYP: n ank meta bdejt nara dawn ir-ritratti għadtfar spei hemm
  diff: [Length Mismatch]
---------------
Sample #89
  REF: semmejtli illi pereżempju e illi huwa il-l-unika kor
  HYP: semmejtli illi pereżempju illi huwa l-unika cor
  diff: [Length Mismatch]
---------------
Sample #90
  REF: b'diversi hemm soprano u jiġifieri artisti
  HYP: diversiem soprano u ġie artisti
  diff: [Length Mismatch]
---------------
Sample #91
  REF: hemm illi huma wkoll e internazzjonali kellek diversi
  HYP: emm li huma wkoll internazzjonali kellet diversi
  diff: [Length Mismatch]
---------------
Sample #92
  REF: hemm mawriet barra minn malta studji
  HYP: hemm mawriet ukoll barra minn malta studji
  diff: [Length Mismatch]
---------------
Sample #93
  REF: xi ħaġa oħra illi forsi tajjeb insemmu meta hemm taljani pereżempju jisimgħu b'ħafna cantautori u dan
  HYP: x'għaġogħlili forsi tajjeb insemmu meta em taljani pereżempju simgħoum ħafna kantawturi
  diff: [Length Mismatch]
---------------
Sample #94
  REF: u malta hemm tħoss illi għad għandna ftit tħoss li għandu jkun hemm iktar opportunitajiet biex
  HYP: malta emm tħoss illi għad għana ftit tħoss li għandu jkun hemm aktar opportunitajiet biex
  diff: [Length Mismatch]
---------------
Sample #95
  REF: jew kantanti u mużiċisti jibdew anke jiktbu l-lirika
  HYP: jew kantanti jew mużiġisti jibdew anki jiktbu l-lirika
  diff: [Length Mismatch]
---------------
Sample #96
  REF: tut hi hemm u jitgħajru jiġifieri
  HYP: tti ehm u jitgħajlu iġifieri
  diff: [Length Mismatch]
---------------
Sample #97
  REF: hemmhekk ukoll qegħdin nitkellmu wkoll kien li l-istil tiegħek imur fil-klassiku
  HYP: meta konn qegħdin nitkellmu kwalla kien li l-istildja imur fil-klassiku
  diff: [Length Mismatch]
---------------
Sample #98
  REF: u bdejna nitkellmu anke x't'tispiċċa illi l-mużika li tisma' tib - tibda tikklassifikaha
  HYP: u bdejna nitkellmu anki x tispiċċa li il-mużika li tisma tibda tikklassifikaha
  diff: [Length Mismatch]
---------------
Sample #99
  REF: hemm hemm min jgħidlek juża l-kelma lirika naraw li l-kelma proprja
  HYP: hemm em in jgħidlek juża l-kelma lirika naraw il-kelma proprja
  diff: [Length Mismatch]
---------------
Sample #100
  REF: hemm skont il-il-ħoss tal-mużika u dan ovvjament huwa dak li jinteressa ħafna
  HYP: hemm skont il-il-ħoss tal-mużika u dan ovvjament huwa dak li jinteressa ħafn
  diff: [Length Mismatch]
---------------
Sample #101
  REF: lilek semmejtli ħafna hawnhekk l-iżvilupp tal-mutazzjoni pereżempju il-kitba tal-mużika
  HYP: na lilek semmejtli ħafna hawnhekk l-iżvilupp tan-notazzjoni pereżempju l-kitba tal-mużika
  diff: [Length Mismatch]
---------------
Sample #102
  REF: il-lingwa hija marbuta mal-istil ta' mużika fil-fil-pereżempju jekk għandna
  HYP: il-lingwa hija marbuta mal-istil ta' mużika pereżempju jekk għandna
  diff: [Length Mismatch]
---------------
Sample #103
  REF: lingwa maltija jew il-lingwa taljana il-lingwa ingliża e lingwi oħra spanjol meta tiġi biex
  HYP: lingwa maltija jew il-lingwa taljana l-lingwa ingliża lingwi oħra spanjol meta tiġi biex
  diff: [Length Mismatch]
---------------
Sample #104
  REF: tgħaqqadhom mal-mal-mużika taħseb illi kif ħa tgħaqqad flimkien tgħid dil-istil ta' mużika tmur aktar
  HYP: taqqadhom mal-mużika taħseb illi kif ħa taqqa flimkien dak din l-istil ta' mużika tmur aktar
  diff: [Length Mismatch]
---------------
Sample #105
  REF: mal-lirika miktuba bil-malti jew bit-taljan donnha l-lingwa taljana hija melodjuża minnha nnifisha
  HYP: mal-lirika miktuba bil-malti għu bit-taljan non hal-lingwa taljana pereżempi hija melodjuża minnha nnifisha
  diff: [Length Mismatch]
---------------
Sample #106
  REF: nixtieq ħafna u jkollna ħafna dwar xiex nitkellmu pero

{'wer': 0.20989802039592081,
 'cer': 0.05800828564406839,
 'mismatches': [{'index': 0,
   'ref': 'maskarat tini perlina għax warajk għandek xadina minflok waħda tini tnejn biex warajk ma jkollok xejn',
   'hyp': "maskarat ini perlina għax warajk għandek x'għdina minflok waħda tini tnejn ix warajk ma jkollok xejn"},
  {'index': 1,
   'ref': "eħe f'dan is-suġġett se nagħtu ħarsa lejn in-novelli u r-rumanzi tal-awturi maltin kosmopolitani jiġifieri li bdew jiktbu",
   'hyp': "eħe f'dan is-suġġett se nagħtu ħarsa lejn n-novelli u r-rumanzi ta' l-awturi maltin kosmopolitan jiġifieri bdew jiktbu"},
  {'index': 2,
   'ref': 'mis-snin disgħin tas-seklu għoxrin issa meta ngħid kosmopolitani xi rrid infisser',
   'hyp': "mis-snin disgħin tas-seklu għoxrin issa meta ngħid kosmopolitani x'irrid infisser"},
  {'index': 3,
   'ref': 'mela e kosmopolitani dawn l-awturi warrbu l-fruntieri',
   'hyp': "mela e b'kosmopolitan dawn l-awturi gwarrbu l-frontieri"},
  {'index': 4,
   'ref': 'u bdejna ma bqajniex iktar bil-mentalità lokalizzata fir-raħal malti',
   'hyp': 'u bdejna ma bqajniex iktar bil-mentalità lokalizzata fir-raħal malti imma'},
  {'index': 5,
   'ref': 'addottaw kuxjenza universali per eżempju missni ngħid li t-temi',
   'hyp': "adottaw kuxjenza universali pereżempju nista' ngħid li it-tehmi"},
  {'index': 6,
   'ref': "hemm f'dawn in-novelli u rumanzi huma temi li irrispettivament mill-post",
   'hyp': "ehm f'dawn in-novelli u r-rumanzi huma temili irrispettivament mill-post"},
  {'index': 7,
   'ref': 'mill-pajjiż min-min-nies mill-karattri sewwa fil-fin-novelli u fir-rumanzi',
   'hyp': 'mil-pajjiż minn min-nies mill-karattri sewwa fil fil novelli u fir-rumanzi'},
  {'index': 8,
   'ref': 'hemm huma komuni pereżempju jekk qed nitkellmu fuq l-imħabba l-abort e t-terroriżmu l-vjolenza',
   'hyp': 'ehm huma komuni pereżempju jekk qed nitkellmu fuq l-imħabba l-abbords e terroriżmu l-vjolenza'},
  {'index': 9,
   'ref': "ta' dawn huma temi li m'għandekx m'għandux x'jaqsam inti l-pajjiż fejn qiegħed u",
   'hyp': "ta daw huma temili m'għandikx m'għandux x'jaqsam int il-pajjiż fejn qiegħed"},
  {'index': 10,
   'ref': 'issa jingħażlu minnhom kemm fil-kontenut kif ukoll fl-istil għaliex qed ngħid hekk hemm',
   'hyp': 'i n se jingħażlu minhom kemm fil-ontenut kif ukoll fl-istil għaliex qed ngħid hekk em'},
  {'index': 11,
   'ref': 'din hija narrativa fejn għandek per eżempju biex nagħti eżempju narratur li ma jiġġudikax',
   'hyp': 'din hija narrattiva fejn għandek pereżempju biex nagħti eżempju narratur li ma jiġġudikax'},
  {'index': 12,
   'ref': "allura hemmhekk meta għandek narratur li ma jiġġudikax dik setgħet in-nuqqas ta' ġudizzju seta' kien",
   'hyp': "allura hemmhekk meta itigħandek naraturli a jiġġudikax dik setgħt in-nuqqas ta' ġudizzju seta' kien"},
  {'index': 13,
   'ref': "hemm bdew jesperjenzaw kulturi oħra jiġifieri ma'",
   'hyp': 'emm bdew jesperjenzaw kulturi oħra jiġifieri ma'},
  {'index': 14,
   'ref': 'huma awturi li ħadmu barra minn malta huma awturi li għexu',
   'hyp': 'huma awturi li ħadmu barraminn malti huma awturi li għexu'},
  {'index': 15,
   'ref': 'hemm u kien hemm ukoll jiġifieri',
   'hyp': 'em u kien hemm ukoll jiġifieri'},
  {'index': 16,
   'ref': "vera ċara f'f'dawn f'dawn dawn il-kotba li",
   'hyp': "vera ċara f'f daw f daw f'daw il-kotba li i"},
  {'index': 17,
   'ref': 'li inti e trabbejt bih li ma tistax tagħmel inti dan ikun sar parti minnek',
   'hyp': 'li inti trabbejtbih li ma ma tistax tagħmel inti dan inkun sar parti minnek'},
  {'index': 18,
   'ref': 'allura meta inti tesperjenza xi ħaġa differenti kulturi oħra hemm inti',
   'hyp': 'allura met inti tesperjenza xi ħaġa differenti kulturi oħra em inti'},
  {'index': 19,
   'ref': 'hekk hu fil-fatt jien ngħid ukoll hi letteratura biex ngħid hekk li ħasdet',
   'hyp': 'hekk hu fil-fatt jien għid ukoll letteratura biex ngħidlek li li ħasdet'},
  {'index': 20,
   'ref': 'forsi mhux it-temi kollha ma kinux assolutament ma jiġux indi-in dirizzati kienu jissemmew',
   'hyp': 'forsi mhux it-temikollha ma kinux assolutament ma jiġux i- indirizzati kienu jissemmew'},
  {'index': 21,
   'ref': "imma anka l-mod kien hemm element miżjud ta' darba fis-sens ta' hemm",
   'hyp': "imma ankegħal mod kien hemm element miżjud ta' tabu fis-sens ta' em"},
  {'index': 22,
   'ref': 'il-ir-reġistru l-kliem beda jkun iktar dirett ix-xbihat beda bdew ikunu iktar espliċiti',
   'hyp': 'il-r-reġistru l-kliem beda jkun aktar dirett ixbiat bddew jkunu aktar espliċiti allura'},
  {'index': 23,
   'ref': 'l-awturi li qed nitkellmu fuqhom illum li huma alex vella gera',
   'hyp': 'l-awturi li qed nitkellmu fuqhom illum li huma aleks vellaġera'},
  {'index': 24,
   'ref': 'bħal claire azzopardi hemm pierre jei meilak',
   'hyp': 'han cler rozopardi em per gaimejla'},
  {'index': 25,
   'ref': 'kif ukoll immanuel mifsud u ġuże stagno issa huma awturi stabiliti',
   'hyp': 'f kolli manwel mifsud i ġiż estano issa huma awturi stabbiliti'},
  {'index': 27,
   'ref': 'din hija t-tieni li ħa jiftaħ fetaħ l-ewwel darba',
   'hyp': 'hemm din hija t-tieni darba li ħa jiftaħ fetaħ l-ewwel darba'},
  {'index': 28,
   'ref': "biex biex itemmu l-kors u f'ottubru li ġej ħa jerġa' jiftaħ il-kors",
   'hyp': "b biex itemmu l-kors u f'ottubru li ġej ħa jerġa' jiftaħ il-kors hemm"},
  {'index': 29,
   'ref': "min jixtieq japplika jista' jagħmel dan sad-dsatax ta' lulju li ġej",
   'hyp': "min jixtieq japplika jista' jagħmel dan sa satax ta' lulju li ġejja"},
  {'index': 30,
   'ref': 'li tixtieq insaqsik kemm bħala żagħżugħa taħseb li s-segwaċi tal-brikkuni',
   'hyp': 'li tixtieq istaqsik kemm bħala żagħżugħan taħseb li s-segwaċi tal-brikuni'},
  {'index': 31,
   'ref': "u għan-novità għall-novità naħseb li qed jisimgħu il-malti b'dak il-mod",
   'hyp': "u u għan-novità naħseb il-fatt li qed jisimgħu l-malti b'dak il-mod"},
  {'index': 33,
   'ref': 'kelli niġi għax għandi għajnejja ħomor u jdemmgħu ħażin jien widnejja',
   'hyp': 'kelli niġi għax għandi għajnejja ħomor u jdemmgħu ħażin ji widnejja'},
  {'index': 35,
   'ref': "madoff hux dejjem b'xi ħaġa jien għadni kemm ġejt bit-tifel ilbieraħ għax kellu griżmejh ħomor nar",
   'hyp': "m'għadoffux dejjem b'xi ħaġa jien għadni kemm ġejt bit-tifel ilbieraħ għax kellu griżmejh ħomor nar"},
  {'index': 36,
   'ref': 'ma kemm ili li nistenna fl-aħħar imissni jien',
   'hyp': 'ma kemm ili nistenna fl-aħħar imissni jien'},
  {'index': 40,
   'ref': "madoff hux dejjem b'xi ħaġa jien",
   'hyp': "m'doffux dejjem b'xi ħaġa jien"},
  {'index': 42,
   'ref': "u mbagħad meta naqrahom ġie ġieli ġew f'idejja kotba kienu jkunu differenti ħafna",
   'hyp': "imm et meta bdejt naqrahom iel ġieli ġew f'idejja kotba kienu jkunu differenti ħafna"},
  {'index': 43,
   'ref': "e jew tmur ma' tork ma' ma' tork iswed pereżempju meta tkun xi tifla dħulija",
   'hyp': "e tmur ma torkm ma' tork iswed pereżempju meta tkun xi tifla għad dħulija"},
  {'index': 44,
   'ref': 'peress li konna mmorru żejt iż-żejtun u nagħmlu dawk il-siltiet bid-djaletti',
   'hyp': 'peres li konna morru żejt iż-żejtun u nagħmlu dawk il-siltiet bid-dijaletti'},
  {'index': 45,
   'ref': "kien qalli issa darb' oħra meta t-għax aħna niktbuhom aħna stess jiena u ir-raġel",
   'hyp': 'kien qal li issa darb oħra meta ttiqax aħna niktbuhom aħna stess jien u r-raġel'},
  {'index': 46,
   'ref': "qalli darb' oħra ridt nagħmluha peress li taż-żurrieq għax ir-raġel tiegħi minn ħal għaxaq id-djalett tiegħu mhux qawwi daqs taż-żurrieq taż-żurrieq iżjed",
   'hyp': 'għalli darba oħra ridtu nagħmluha peress li taż-żurri għax ir-raġel tej minħalaxa d-dejalett tiegħ mhux qawwi daqs ta- żri taż-urieq iżjed'},
  {'index': 47,
   'ref': 'qalli irrid nagħmel waħda miegħek jiena biż-',
   'hyp': 'għalli irrid nagħmel waħda miegħek jiena biż'},
  {'index': 48,
   'ref': 'konna narawha ġieli jiena u tielgħa minn wied il-għajn għax imbagħad morna noqogħdu hemm minn wied il-għajn konna narawhom konna ngħidu ara tellagħhom illum',
   'hyp': 'konna narawha aġiel ien ħawtilha mewit lin ħax imbagħad orna noqogħdu hem mewitili konna nrahom onna ngħidu wara tallahom illum'},
  {'index': 49,
   'ref': 'lili kien qagħad jispjegali waqt intervista li għamiltlu li trid sena biex ittellagħhom',
   'hyp': 'lili kien qagħad jispjegali waqt intervista li għamiltlu li dik trid sena biex ittallagħhom'},
  {'index': 50,
   'ref': 'trid sena u mbagħad biex tara il-ħin il-ġust biex tniżżilhom',
   'hyp': 'aa biex tagħraf il-ħin il-ġust biex tniżżilhom'},
  {'index': 51,
   'ref': 'u għandi għandi il-ħelper miż-żurrieq paċċu pereżempju tgħidlu l-baċċu',
   'hyp': 'u għandi għandi il-helper miż-żurrieq paċċu pereżempju tgħidlu l-paċċu'},
  {'index': 52,
   'ref': 'illi jiena orrajt forsi ma kont nafhom daħal l-ingliż imma hemm ċertu kliem',
   'hyp': 'hemm ċertu kliem illi jien rajt forsi ma kontx nafhom daħal l-ingliż imma'},
  {'index': 53,
   'ref': 'il-ġenituri tiegħi min-naħa l-oħra min-naħa tal-isla u għandhom affarijiet illi huma differenti',
   'hyp': 'il-ġenituri tiegħ min in-naħa l-oħa min-naħa tal-ista u għandhom affarijiet ili iduma ifferenti'},
  {'index': 54,
   'ref': 'jiena il-il-maid tiegħi hawn miż-żurrieq nitkellmu ħafna bil-malti bejnietna',
   'hyp': 'jien għal il-il-mejt tiegħi hawn iż-żurrieq nitkellmu ħafna bil-malti bejnietna'},
  {'index': 55,
   'ref': 'pero niskanta emmnuni niskanta meta ċċempel lil ommha jew żewġha',
   'hyp': "pero niskanta emmnuni niskanta meta ċċempel' il ommha jew żewġha"},
  {'index': 56,
   'ref': 'voldieri hawn xi taqbiliet jew talb li biex iġib id-deni',
   'hyp': 'oke jew forsi xi ta iit jew tal li kie biex ibid id denni'},
  {'index': 57,
   'ref': 'ma tiftakarhiex lin-nanna pa tgħid xi ħaġa xi talba jew hekk waqt li qed',
   'hyp': 'u tiftakarnix in-nanna a fejin xi ħadu xi dena jew ea'},
  {'index': 58,
   'ref': 'tiftakarha kif kienu jinterpretawha wkoll tiftakarha kif kienu jgħiduha',
   'hyp': 'kif ta kara kif kienu jinterpretawha wkoll if takara kif kienu jgħiduha'},
  {'index': 59,
   'ref': 'għax għidtli irranġajtha ftit tiftakar forsi',
   'hyp': 'sedt li reġajta ftit staar forsi'},
  {'index': 60,
   'ref': "biex insaħħaħ il-kitba tiegħi e din id-diploma fetħitli oċean ta' kittieba u kotba",
   'hyp': "biex insaħħaħ il-kitba tiegħi din id-diploma fetħit li oxean ta' kittieba hu kotba"},
  {'index': 61,
   'ref': 'bil-malti irrid insaħħaħ il-malti tiegħi ukoll',
   'hyp': 'il-malti inrid insaħħaħ il-malti tiegħi ukoll'},
  {'index': 62,
   'ref': 'iżda mbagħad sibt sapport kbir mill-kollegi tiegħi u mil-letturi',
   'hyp': 'iżda mbagħad sibt apport kbiri mill-kollegi tiegħi u mill-letturi'},
  {'index': 63,
   'ref': "u għadu għal qalbi ħafna u nikkoraġġixxi' il min huwa interessat fil-letteratura maltija",
   'hyp': 'dal qalbi ħafna u ninkoraġixxi l min u nteressad fil-letteratura maltija'},
  {'index': 64,
   'ref': "u għadu għal qalbi ħafna u nikkoraġġixxi' il min huwa interessat fil-letteratura maltija",
   'hyp': 'dal-qalbi ħafna u ninkoraġixxi l min u interessad fi- letteratura maltija'},
  {'index': 65,
   'ref': "grazzi lil ta' nenu the artisan baker maypole bakery",
   'hyp': 'grazzi lil tanenu di artison bejker m pol bajkery'},
  {'index': 66,
   'ref': 'health and beauty by browns virtu ferries',
   'hyp': 'health and buty by brawns vir too ferreys'},
  {'index': 67,
   'ref': 'estetika the cosmetic clinic u mannarinu caterers',
   'hyp': 'estetika the cosmetic clinick u mannarino caterers'},
  {'index': 69,
   'ref': "illum għoxrin ta' frar elfejn u sittax qed nintervista lil stefania fenech mill-marsa ta' sebgħa u erbgħin sena",
   'hyp': "illum għoxrin ta' febrar elfejn u sittax qed nintervista lil sepania feneck mill-marsa ta' sebgħa u erbgħin sena"},
  {'index': 70,
   'ref': 'għidtli li taf xi taqbila li kontu tużaw e meta kontu tfal',
   'hyp': 'għidtli taf xi taqbila li kontu tużaw meta kontu tfal'},
  {'index': 71,
   'ref': 'u imma hemm likk l-iktar għax tgħid seħta bedudu jew minħabba in-nifs',
   'hyp': 'imma hemm l l-iktar għax tgħid seħħ ta bedudu jew minħabba n-nifs'},
  {'index': 72,
   'ref': 'jiena yanica schembri fava qed nintervista lil judith schembri',
   'hyp': 'jien anica sckembri pava qed nintervista lil judit xkembri'},
  {'index': 73,
   'ref': 'nostrok ħa tostorni sa ma tiġi l-mewt tiġborni',
   'hyp': "nostroka ta' stormi sa ma tiġi l-mewtiġbormi"},
  {'index': 75,
   'ref': "m'hekk lil ruth castillo minn hawnhekk pero se ngħaddu għal suġġett illi",
   'hyp': 'back lil ruth castello minn hawnhekk pero se ngħaddu għall suġġett illi'},
  {'index': 77,
   'ref': 'e kellna hawn mistiedna letturi marbuta mad-diploma',
   'hyp': 'kellna mistiedna letturi marbuta mad-diploma'},
  {'index': 78,
   'ref': 'fil-letteratura maltija u e miegħi illum stidint hemm',
   'hyp': 'fil-letteratura maltijat u miegħi illum stident emm'},
  {'index': 79,
   'ref': "għandna personaġġ ieħor interessanti b'aleander vella gregory illi huwa kompożitur kif ukoll mużiċist",
   'hyp': 'għandna personaġġ ieħor interessanti iwa alexander vella gregri li huwa kompożitur kif ukoll mużiċist'},
  {'index': 80,
   'ref': 'hemm u dejjem tiskopri jiġifieri grazzi għall-programm ukoll jirnexxilna illi',
   'hyp': 'emm u dejjem tiskopry jiġifieri przzjal programm koll irnexxilna illi'},
  {'index': 81,
   'ref': 'u inti ukoll hemm tagħti il-krettu li jisħoqq il-lirika fil-kanzunetta',
   'hyp': 'u inti wkoll hemm tati il-krettu li jismu l-lirika fil-kanzunetta'},
  {'index': 82,
   'ref': 'hemm forsi nibdew nitkellmu dwar meta bdejt tgħid il-lingwaġġ',
   'hyp': 'emm se nibdeħ nitkellmu dwar meta bdejt għid il-lingwaġġ'},
  {'index': 84,
   'ref': "allura il-mużika u l-lingwa hemm x'għandu x'jaqsam fil-letteratura maltija jiġifieri int hawnhekk",
   'hyp': "allura il-mużika u l-lingw x'għandux x jaqsam fil-letteratura maltija jġifieri inti hawnhekk"},
  {'index': 85,
   'ref': "kif semmejtli wkoll fil-fin-noti tiegħek illi ir-rwol tiegħek issa hawnhekk f'dan il-kors",
   'hyp': "kif semmejtli wkoll fil-fin-noti tiegħek illi ir-rwol tiegħek issa hawnhekk f'dan il-cors"},
  {'index': 86,
   'ref': 'ħa tidħol ukoll il-mużika għax għandek il-il-lirika u l-mużika jiġifieri t-tnejn',
   'hyp': 'ħajt idħol ukoll il-mużika ħax għandek l-lirika u l-mużika ġid tnejn'},
  {'index': 87,
   'ref': 'tiegħi għaliex hemm tajjeb illi forsi nkunu daqq nafu daqsxejn il-background',
   'hyp': 'għaliex hemm tajeb illi forsi nkunud nafu daqsxejn il-background'},
  {'index': 88,
   'ref': 'anki meta bdejt nara dawn ir-ritratti għid bħal speċi hemm',
   'hyp': 'n ank meta bdejt nara dawn ir-ritratti għadtfar spei hemm'},
  {'index': 89,
   'ref': 'semmejtli illi pereżempju e illi huwa il-l-unika kor',
   'hyp': 'semmejtli illi pereżempju illi huwa l-unika cor'},
  {'index': 90,
   'ref': "b'diversi hemm soprano u jiġifieri artisti",
   'hyp': 'diversiem soprano u ġie artisti'},
  {'index': 91,
   'ref': 'hemm illi huma wkoll e internazzjonali kellek diversi',
   'hyp': 'emm li huma wkoll internazzjonali kellet diversi'},
  {'index': 92,
   'ref': 'hemm mawriet barra minn malta studji',
   'hyp': 'hemm mawriet ukoll barra minn malta studji'},
  {'index': 93,
   'ref': "xi ħaġa oħra illi forsi tajjeb insemmu meta hemm taljani pereżempju jisimgħu b'ħafna cantautori u dan",
   'hyp': "x'għaġogħlili forsi tajjeb insemmu meta em taljani pereżempju simgħoum ħafna kantawturi"},
  {'index': 94,
   'ref': 'u malta hemm tħoss illi għad għandna ftit tħoss li għandu jkun hemm iktar opportunitajiet biex',
   'hyp': 'malta emm tħoss illi għad għana ftit tħoss li għandu jkun hemm aktar opportunitajiet biex'},
  {'index': 95,
   'ref': 'jew kantanti u mużiċisti jibdew anke jiktbu l-lirika',
   'hyp': 'jew kantanti jew mużiġisti jibdew anki jiktbu l-lirika'},
  {'index': 96,
   'ref': 'tut hi hemm u jitgħajru jiġifieri',
   'hyp': 'tti ehm u jitgħajlu iġifieri'},
  {'index': 97,
   'ref': 'hemmhekk ukoll qegħdin nitkellmu wkoll kien li l-istil tiegħek imur fil-klassiku',
   'hyp': 'meta konn qegħdin nitkellmu kwalla kien li l-istildja imur fil-klassiku'},
  {'index': 98,
   'ref': "u bdejna nitkellmu anke x't'tispiċċa illi l-mużika li tisma' tib - tibda tikklassifikaha",
   'hyp': 'u bdejna nitkellmu anki x tispiċċa li il-mużika li tisma tibda tikklassifikaha'},
  {'index': 99,
   'ref': 'hemm hemm min jgħidlek juża l-kelma lirika naraw li l-kelma proprja',
   'hyp': 'hemm em in jgħidlek juża l-kelma lirika naraw il-kelma proprja'},
  {'index': 100,
   'ref': 'hemm skont il-il-ħoss tal-mużika u dan ovvjament huwa dak li jinteressa ħafna',
   'hyp': 'hemm skont il-il-ħoss tal-mużika u dan ovvjament huwa dak li jinteressa ħafn'},
  {'index': 101,
   'ref': 'lilek semmejtli ħafna hawnhekk l-iżvilupp tal-mutazzjoni pereżempju il-kitba tal-mużika',
   'hyp': 'na lilek semmejtli ħafna hawnhekk l-iżvilupp tan-notazzjoni pereżempju l-kitba tal-mużika'},
  {'index': 102,
   'ref': "il-lingwa hija marbuta mal-istil ta' mużika fil-fil-pereżempju jekk għandna",
   'hyp': "il-lingwa hija marbuta mal-istil ta' mużika pereżempju jekk għandna"},
  {'index': 103,
   'ref': 'lingwa maltija jew il-lingwa taljana il-lingwa ingliża e lingwi oħra spanjol meta tiġi biex',
   'hyp': 'lingwa maltija jew il-lingwa taljana l-lingwa ingliża lingwi oħra spanjol meta tiġi biex'},
  {'index': 104,
   'ref': "tgħaqqadhom mal-mal-mużika taħseb illi kif ħa tgħaqqad flimkien tgħid dil-istil ta' mużika tmur aktar",
   'hyp': "taqqadhom mal-mużika taħseb illi kif ħa taqqa flimkien dak din l-istil ta' mużika tmur aktar"},
  {'index': 105,
   'ref': 'mal-lirika miktuba bil-malti jew bit-taljan donnha l-lingwa taljana hija melodjuża minnha nnifisha',
   'hyp': 'mal-lirika miktuba bil-malti għu bit-taljan non hal-lingwa taljana pereżempi hija melodjuża minnha nnifisha'},
  {'index': 106,
   'ref': 'nixtieq ħafna u jkollna ħafna dwar xiex nitkellmu pero',
   'hyp': 'mistieq ħafna u kollna ħafna dwar xiex nitkellmu pero'},
  {'index': 107,
   'ref': 'sfortunatament il-ħin jibda jagħfas għaliex hemm xtaqt illi forsi nagħlqu hawnhekk meta',
   'hyp': 'fortunatamel il-ħin jibda jagħfas għaliex hemm jaqtilli forsi nagħlqu awnhek meta'},
  {'index': 108,
   'ref': 'tidħol semmejt għal pereżempju il-lirika fil-festi jiġifieri semmejtilna ftit',
   'hyp': 'tidħol semmejt jawn pereżempju l-lirita fil-festi jiġifieri semmejtilna ftit'},
  {'index': 109,
   'ref': 'pero biex nikkonkludu malli tibda tgħaqqad dawn l-attivitajiet differenti dawn',
   'hyp': 'pero biex nikkonkludu meta tibda taqad dawn l-attivitajiet differenti dawn'},
  {'index': 110,
   'ref': 'l-istili differenti anke meta tibda tagħmel il-lezzjonijiet inti',
   'hyp': 'l-istili differenti ankki meta tibda tagħmel il-lezzjonijiet inti'},
  {'index': 111,
   'ref': 'hemm xi tkun ir-reazzjoni tal-istudenti jgħidlek imma',
   'hyp': 'hemm xi tkun ir-reazzjoni tant tal-istudenti dutur'},
  {'index': 112,
   'ref': "nisperaw illi ma ndumux ma nerġgħu niltaqgħu ukoll f'dan il-programm nawguralek ukoll",
   'hyp': "nisperaw ili m'għandumx ma nerġgħu nitaqgħu ukol f'dan il-programm nawguralek ukoll"},
  {'index': 113,
   'ref': 'għaliex għidtli fi żmien tliet ġimgħat issa ukoll e',
   'hyp': 'għaliex qadtli fi żmien tliet ġimgħat issa u palul'},
  {'index': 114,
   'ref': 'nisperaw li forsi fi żmien xahar ix-xahar id-dieħel nergħu niltaqgħu flimkien u nkomplu dwar dan is-suġġett bil-qalb kollha',
   'hyp': 'rgau li forsi fi żmien xaha ix-xagħr i diegħa nergħu niltaqħu flimkien nkomplu dwar dan is-suġġett'},
  {'index': 115,
   'ref': 'awguri il-jum it-tajjeb minn hawnhekk pero hemm ħa ngħaddu biex nagħtu ħarsa lejn it-traffiku',
   'hyp': 'awguri u l-jum it-tajjeb minn hawnhekk pero hemm ħa ngħaddu biex nagħtu ħarsa lejn it-traffiku'},
  {'index': 116,
   'ref': 'hemm bħal dejjem naraw mela hawnhekk qegħdin naraw l-imsida donnhom',
   'hyp': 'emm bħal dejjem naraw mela hawnhekk qegħdin naraw l-imsida donnhom'},
  {'index': 117,

##### Split Run Reduced UnTokenised

In [26]:
evaluate_raw_model(common_voice_test)

--- Evaluating 1892 samples (Greedy Decoding) ---

100%|██████████| 1892/1892 [03:32<00:00,  8.91it/s]

===================================
RAW MODEL RESULTS:
WER: 0.2125 (21.25%)
CER: 0.0577 (5.77%)
===================================

Sample Transcriptions:
REF: maskarat tini perlina għax warajk għandek xadina minflok waħda tini tnejn biex warajk ma jkollok xejn
HYP: maskerat tini perlina għax warajk għandek xadina minflok waħda tini t-tnejn biex warajk ma jkollok xejn
----------
REF: eħe f' dan is-suġġett se nagħtu ħarsa lejn in-novelli u r-rumanzi tal-awturi maltin kosmopolitani jiġifieri li bdew jiktbu
HYP: eef dan is-suġġett se nagħtu ħarsa lejn in-novelli u r-rumanzi ta' l-awturi maltin kosmopolitan jiġifieri bdew jiktbu
----------

{'wer': 0.21247099422859522, 'cer': 0.05765757867975804}

##### Common Voice Tokenised but normalised

In [64]:
evaluate_raw_model(common_voice_test)

--- Evaluating 1224 samples ---

100%|██████████| 1224/1224 [01:49<00:00, 11.16it/s]

========================================
RESULTS Summary
Total Samples: 1224
Perfect Matches: 866
Mismatches: 358
WER: 0.0710 | CER: 0.0151
========================================

--- DETAILED MISMATCHES ---
Sample #2
  REF: xi tħobb f'pajjiżek
  HYP: xi thobb f'pajjiżek
  diff:
---------------
Sample #4
  REF: huwa suġġett għall-konfiska taħt dik il-proklama
  HYP: huwa suġġett tal-konfiska taħt dik il-proklama
  diff: [Length Mismatch]
---------------
Sample #8
  REF: isaac kien akkumpanjat mill-kowċ tiegħu u missieru alex bezzina
  HYP: aiżak kien ikkumpanjat mill-kowċ tiegħu u missieru alexs bezzina
  diff: [Length Mismatch]
---------------
Sample #14
  REF: din hija kompetizzjoni li tintlagħab fuq żewġ logħbiet kontra l-istess tim
  HYP: din hija kompetizzjoni li tintlagħab fuq żewġ lgħbiet kontra l-istess tim
  diff: [Length Mismatch]
---------------
Sample #15
  REF: ħalli ngħaddi issa għal dak li qed jingħad fir-rapport annwali
  HYP: ħalli ngħaddi iss għa dak li qed jingħad fir-rapport annwali
  diff: [Length Mismatch]
---------------
Sample #18
  REF: x'investors programme hu dan
  HYP: x'investor s programm hu dan
  diff:
---------------
Sample #20
  REF: clint camilleri jew therese comodini cachia
  HYP: clint camilleri jew terese comodiny cachia
  diff: [Length Mismatch]
---------------
Sample #25
  REF: nerġa' ngħidlek biex isserraħ moħħok għax is-sodod se nipprovduhom
  HYP: nerġa' ngħidlek biex isseraħ moħok għax is-sodod se nipprovduhom
  diff: [Length Mismatch]
---------------
Sample #27
  REF: b'xorti tajba ħarba oħra ta' żiemel ma kellha l-ebda konsegwenzi koroh
  HYP: b'xorti tajba ħaba oħra ta' żiemel ma kellha l-ebda konsegwenzi koroh
  diff: [Length Mismatch]
---------------
Sample #29
  REF: kont il-brażil ukoll għat-tazza tad-dinja
  HYP: kont il-brażil ukoll għattazza tad-dinja
  diff: [Length Mismatch]
---------------
Sample #31
  REF: din l-informazzjoni kien ħariġha saviour balzan
  HYP: din l-informazzjoni kien ħariġha savior balzan
  diff: [Length Mismatch]
---------------
Sample #34
  REF: bħalissa għadha għaddejja t-tfittxija għall-kumplament tan-nies irrappurtati nieqsa
  HYP: bħalissa da ddejja tfittxija l-kumplament tan-nies irrappurtati nieqsa
  diff: [Length Mismatch]
---------------
Sample #39
  REF: x'passi ttieħdu fil-konfront ta' dawk li nqabdu jkarkru
  HYP: x'passi ttieħdu fil-konfront ta' dawk li nqabbdu jikkarkru
  diff: [Length Mismatch]
---------------
Sample #40
  REF: dak il-ħin instema' għasfur ikanta fuq siġra
  HYP: dak il-ħin instema' asfuri kanta fuq siġra
  diff: [Length Mismatch]
---------------
Sample #43
  REF: jiena infurmat li l-għażla li saret ġa qed tagħti l-frott
  HYP: jien infurmat li l-għażla li saret ġà qed tagħti frott
  diff: [Length Mismatch]
---------------
Sample #45
  REF: ħalli l-kummenti tiegħek hawn taħt bl-isem u l-kunjom
  HYP: ħalli l-kummenti tiegħek hawn taħt bl-isem u l-kunjum
  diff:
---------------
Sample #50
  REF: ma xbajniex ngħidulkom
  HYP: ma ġbajniex ngħidulkom
  diff:
---------------
Sample #56
  REF: tmerih f'wiċċu
  HYP: tmeriegħ f'wiċċu
  diff: [Length Mismatch]
---------------
Sample #61
  REF: l-investigazzjoni qed issir f'nanterre pariġi
  HYP: l-investigazzjoni qed issir f'nanterr pariġi
  diff: [Length Mismatch]
---------------
Sample #66
  REF: il-konferenza għalqet b'diskors mill-isqof ta' għawdex monsmario grech
  HYP: il-konferenza għalqet b'diskors mill-isqof ta' għawdex monsurmario grech
  diff: [Length Mismatch]
---------------
Sample #68
  REF: it-taħlit mhuwiex faċli biex isir u jrid ikollok knowledge sew
  HYP: it-taħlit mhuwiex faċli biex isir u jrid ikollok nolege sew
  diff: [Length Mismatch]
---------------
Sample #74
  REF: issa wieħed jara kif tkompli għaddejja d-diskussjoni f'dan ir-rigward
  HYP: issa wieħed jara bie komli għaddejj ħad-diskussjoni f'dan ir-rigward
  diff: [Length Mismatch]
---------------
Sample #77
  REF: messi u missieru qed jiġu mixlija b'akkużi relatati ma' frodi
  HYP: messi u missieri qed jiġu mixlija b'akkużi relatati ma' frodi
  diff:
---------------
Sample #80
  REF: wara l-irġiel għallquha sakemm mietet
  HYP: wara l-irġiel għalquha sakemm mietet
  diff: [Length Mismatch]
---------------
Sample #83
  REF: irrid ngħid ukoll li dan is-self kollu ngħata mingħajr ebda garanzija
  HYP: irrid ngħid ukoll li dan is-self kollu ingħata mingħajr ebda garanzija
  diff: [Length Mismatch]
---------------
Sample #98
  REF: dak ukoll kien ordni reliġjuż
  HYP: dak ukoll kien ordni religius
  diff:
---------------
Sample #103
  REF: dawn huma tliet stadji fuq normi internazzjonali
  HYP: dawn huma tliet stadi fuq normi internazzjonali
  diff: [Length Mismatch]
---------------
Sample #104
  REF: x'tip ta' tajr ġie rreġistrat
  HYP: x'tip ta' taire ġie rreġistrat
  diff: [Length Mismatch]
---------------
Sample #109
  REF: id-differenza bejniethom naturalment hija l-part - time
  HYP: id-differenza bejniethom naturalment hija l-part time
  diff: [Length Mismatch]
---------------
Sample #110
  REF: bl-ewro dgħajjef kumpaniji ewropej qed isibuha eħfef biex jesportaw
  HYP: bl-ewroday kumpaniji ewropeji qed isimuhoa eħfef biex jesportaw
  diff: [Length Mismatch]
---------------
Sample #114
  REF: allura min se jerfa' r-responsabilità għal dan
  HYP: allura min se jerfa r-responsabbiltà għal dan
  diff: [Length Mismatch]
---------------
Sample #117
  REF: it-tfajla waqfet ħesrem u daret
  HYP: it-tfajla waffqet estrem u daret
  diff: [Length Mismatch]
---------------
Sample #119
  REF: nerġa' ngħid li jien għandi biss kopja tar-rapport u tal-minute sheets
  HYP: nerġa ngħid li jien għandi biss kopja tar-rapport u tal-minut ts
  diff: [Length Mismatch]
---------------
Sample #124
  REF: l-italja għandha foreign policy differenti minn ta' franza
  HYP: l-italja għandha forene policy differenti minn ta' franza
  diff: [Length Mismatch]
---------------
Sample #125
  REF: il-bomba splodiet f'ħin meta kienet għaddejja karozza tal-linja
  HYP: il-bomba splodiet f'ħin meta kienet għaddejja karozz tal-linja
  diff: [Length Mismatch]
---------------
Sample #126
  REF: ħassejtni fis-seba' sema li ksirt rekord nazzjonali
  HYP: ħassejtni fis-seba' sema' li ksirt rekord nazzjonali
  diff: [Length Mismatch]
---------------
Sample #130
  REF: jien tfajla li ili noħroġ ma' ġuvni aktar minn sentejn
  HYP: jien tfajla li hili noħroġ ma' ġuvni aktar minn sentejn
  diff: [Length Mismatch]
---------------
Sample #131
  REF: dan kollu fir-rispett tad-drittijiettal-oppożizzjoni u tad-deputati individwali
  HYP: dan kollu fir-rispett ta- drittijiettal-oppożizzjoni u tad-deputati individwali
  diff:
---------------
Sample #140
  REF: ngħaddu għall-punt li jmiss fl-aġenda' affarijiet oħra'
  HYP: ngħaddu għall-punt li jmiss fl-aġenda affarijiet oħra
  diff: [Length Mismatch]
---------------
Sample #142
  REF: dan minbarra l-iskemi ta' kreditu għall-intrapriżi żgħar u medji
  HYP: dan minnbarra l-iskemi ta' kreditu għall-intrapriżi żgħar u medji
  diff: [Length Mismatch]
---------------
Sample #150
  REF: jien kelli okkażjoni nikteb fil-blog tiegħi fuq dan
  HYP: jien kelli okkażjoni nikteb fil-blokk tiegħi fuq dan
  diff: [Length Mismatch]
---------------
Sample #151
  REF: genel hija l-kumpanija li qed tmexxi l-operazzjonijiet ta' tfittix taż-żejt
  HYP: gene hija l-kumpanija li qed tmexxi l-operazzjonijiet tat-tfittig taż-żejt
  diff: [Length Mismatch]
---------------
Sample #160
  REF: ikun żball jekk tiżen naħa waħda u tagħlaq għajnejk għal aspetti oħra
  HYP: ikun żbaljeak tiżen naħa waħda u tgħlaq għajnejk għall aspetti oħra
  diff: [Length Mismatch]
---------------
Sample #162
  REF: newsbook dot com dot mt hija waħda minnhom
  HYP: newsbook com mt hija waħda minnhom
  diff: [Length Mismatch]
---------------
Sample #164
  REF: bihom huma jgħinu lill-missjunarji maltin tal-pajjiżi foqra tat-tielet dinja
  HYP: biehom huma jgħinu lill-missjonarji maltin tal-pajjiżi foqra tat-tielet dinja
  diff: [Length Mismatch]
---------------
Sample #165
  REF: u biex wieħed josserva r-regoli jrid ikun hemm il-volontá
  HYP: u biex wieħed josserva r-regoli jrid ikun hemm il-volontà
  diff:
---------------
Sample #168
  REF: jien personalment ma togħġobnix u anzi ġismi jqumli xewk xewk
  HYP: jien personalment ma togħġobnix u anzi ġismi jgqum li ċewk xewk
  diff: [Length Mismatch]
---------------
Sample #177
  REF: dan mingħajr ma jiġu esklużi l-ispeċi tradizzjonali bħall-awrat u l-ispnott
  HYP: dan mingħajr ma jiġu esklużi l-ispeċji tradizzjonali bħall-awrat u l-ispnot
  diff:
---------------
Sample #183
  REF: it-tweġiba tiegħi kienet iva għandu jkollu l-libertà li jagħmel dak
  HYP: it-tweġiba tiegħi kienet iva għandu jkollu libertà li jagħmel dak
  diff: [Length Mismatch]
---------------
Sample #184
  REF: biex wieħed jakkwista liċenzja għal arma jrid ikun irreġistrat ma' organizzazzjoni
  HYP: biex wieħed jakkwista liċenzja għallarma jrid ikun irreġistrat ma' organizzazzjoni
  diff:
---------------
Sample #185
  REF: in-nuqqas f'dan il-każ kien min-naħa tal-land department
  HYP: in-nuqqas f'dan il-każ kien min-naħa tal-lend department
  diff:
---------------
Sample #188
  REF: issa m'hemmx biss glieda mal-ħin iżda anke mal-maltemp
  HYP: issa m'hemmx biss grieda mal-ħin iżda anke mal-maltemp
  diff:
---------------
Sample #192
  REF: john ma setax iżomm lura s-sarkażmu f'leħnu
  HYP: jon ma setax iżomm lura s-sarkażmu f'leħnu
  diff: [Length Mismatch]
---------------
Sample #193
  REF: nirien ħakmu bini abbandunat f'manoel island
  HYP: nirien ħakmu bini abbandunat f'manoel iland
  diff: [Length Mismatch]
---------------
Sample #196
  REF: qalet li l-aħħar sena kienet waħda li biddlitilha ħajjitha
  HYP: qalet i l-aħħar sena kienet waħda li biddlit ilha ħajjitha
  diff:
---------------
Sample #197
  REF: is-sitwazzjoni hi li hemm bżonn ammontta' karozzi oħra
  HYP: is-sitwazzjoni hi li hemm bżonn ammontta' kaozzi oħra
  diff: [Length Mismatch]
---------------
Sample #206
  REF: dan filwaqt li tħares ukoll il-benefiċċji tal-konsumaturi
  HYP: dan filwaqt li tħares ukoll lejn il-enfiċji tal-konsumaturi
  diff: [Length Mismatch]
---------------
Sample #213
  REF: in-nannu sar sinjur f'daqqa u omm it-tarbija irrappurtatu lill-pulizija
  HYP: in-nannu sar sinjur f'daqqa u omm it-tarbija rrappurtatu lill-pulizija
  diff: [Length Mismatch]
---------------
Sample #220
  REF: iż-żewġt irġiel kienu nżammu taħt arrest għal madwar jumejn
  HYP: iż-żewġ tirġiel kienu nżammu taħt arrest għal madwar jumejn
  diff:
---------------
Sample #221
  REF: dawn l-irziezet inbnew fi żmien il-gran mastru lascaris
  HYP: dawn l-irziet se tinbnew fi żmien il-gram mastru l-askaris
  diff: [Length Mismatch]
---------------
Sample #222
  REF: lill-irġiel
  HYP: ill-irġiel
  diff: [Length Mismatch]
---------------
Sample #226
  REF: hu mistenni jirritorna lura fil-belt tal-vatikan dakinhar stess
  HYP: hu mistenni jirritorna lura fil-elt tal-vatikan dakinhar stess
  diff: [Length Mismatch]
---------------
Sample #227
  REF: kienet ilha nieżla xita qliel għal aktar minn jumejn bla waqfien
  HYP: kienet ilha nieżla xi ta' qliel għal aktar minn jumejn bla waqfien
  diff: [Length Mismatch]
---------------
Sample #230
  REF: pereżempju qal li għal dan il-gvern l-arroganza saret virtù
  HYP: pereżempju għal dan il-gvern l-arroganza saret virtu
  diff: [Length Mismatch]
---------------
Sample #231
  REF: ħadd ma weġġa' f'ħabta bejn trakk u karozza fil-wied tal-imsida
  HYP: ħadd ma weġġa' f'ħabta bejn trakk u kaozza fil-wied tal-imsida
  diff: [Length Mismatch]
---------------
Sample #233
  REF: xi tgħidli dwar il-poligamija
  HYP: xi tgħid li dwar il-poligamija
  diff: [Length Mismatch]
---------------
Sample #235
  REF: x'kien jisimhom dawn il-bċejjeċ tal-baħar
  HYP: x'kien jisimhom dawk il-bċejjeċ tal-baħar
  diff:
---------------
Sample #243
  REF: kieku dawn kisru jew weġġgħu lil xi ħadd orrajt
  HYP: kieku dawn kissru jewweġġaħu lil xi ħadd torraijt
  diff: [Length Mismatch]
---------------
Sample #244
  REF: dan ifisser li dawn kienu suppressed
  HYP: dan ifisser li dawn kienu sapprest
  diff: [Length Mismatch]
---------------
Sample #245
  REF: il-waiting lists bilfors jikbru
  HYP: il-wating lists bilfors jikbru
  diff: [Length Mismatch]
---------------
Sample #248
  REF: jimmy ma felaħx jirreżisti
  HYP: jimmi ma felaħx jirreżisti
  diff:
---------------
Sample #251
  REF: jien ngħid li ħallejnielhom ħofra sabiħa għaliex ix-xogħol inbeda fi żmienna
  HYP: jien għid li ħallejnilhom ħafrna sabiħa għaliexix- xogħol inbeda fi żmienna
  diff: [Length Mismatch]
---------------
Sample #253
  REF: dan wara li l-prezz kien ħa tisbita fil-bidu ta' ottubru
  HYP: dan wara li l-prezz kien ħat isbita fil-bidu ta' ottubru
  diff:
---------------
Sample #255
  REF: taħt imneħirna
  HYP: taħtimneħilna
  diff: [Length Mismatch]
---------------
Sample #262
  REF: hija procedura normali li wara li jintefa' l-cable it-trinka tintradam
  HYP: hija proċedura normali li wara li intefa' l-kcabel it-trinka tintradam
  diff:
---------------
Sample #264
  REF: oriġinarjament maradona kellu jkun parti mill-istaff tekniku matul is-sajf li għadda
  HYP: oriġinarjament maradona kellu jkun parti mill-istaff tekniku matulis sajf li għadda
  diff: [Length Mismatch]
---------------
Sample #267
  REF: m'għandix għalfejn neħodha bi kbira meta nagħmel xi żball
  HYP: m'għandix għalfejn noħodha bi kbira meta nagħmel xi żball
  diff:
---------------
Sample #269
  REF: anke l-ministru kemm-il darba deher fil-media u qal hekk
  HYP: anke l-ministru kemm il darba dir fil-midja u qal lek
  diff: [Length Mismatch]
---------------
Sample #273
  REF: il-gvern jemmen bis-sħiħ fiż-żgħażagħ
  HYP: il-gvern jemmen bi sħieħ fiż-żgħażagħ
  diff:
---------------
Sample #276
  REF: bikram arora u haroon majeed kienu ferm dominanti
  HYP: bikram arora u haron majed kienu ferm dominanti
  diff: [Length Mismatch]
---------------
Sample #277
  REF: kont ilek tafu seba' snin ma tafx fejn għandu kont
  HYP: kontilek tafu seba' snin ma tafx fejn għandu kont
  diff: [Length Mismatch]
---------------
Sample #280
  REF: u wara l-handover purposes x'kont se tagħmel tirritornahom
  HYP: uwara l-handover parposis x'kont se tagħmel tirritorna howm
  diff: [Length Mismatch]
---------------
Sample #281
  REF: ħallu lilkom infuskom issibu l-ħniena t'alla
  HYP: ħallu lilkom infuskom issibu l-ħdiena t'alla
  diff:
---------------
Sample #284
  REF: qatt m'emmint li t-triq tas-suċċess hija faċli
  HYP: qatt m'emmint li t-triq tas suċċess hija faċli
  diff:
---------------
Sample #286
  REF: qed ngħidilkom biex tmorru ftit s'hemmhekk ħalli taraw b'għajnejkom
  HYP: qed ngħidilkom biex tmorru ftit s'hemmhekk ħalli taraw b'għanejkom
  diff: [Length Mismatch]
---------------
Sample #287
  REF: kemm ilek ma trodd salib fil-pubbliku
  HYP: kemm hilek ma trozgalib fil-pubbliku
  diff: [Length Mismatch]
---------------
Sample #289
  REF: dawn qed jaħdmu taħt pressjoni kontinwa kemm minn fuq kif ukoll minn isfel
  HYP: dawn qed jaħdmu ba taħt pressjoni kontinwa kemm minn fuq kif ukoll minn isfel
  diff: [Length Mismatch]
---------------
Sample #291
  REF: x'inhi l-idea tiegħek dwar dawn l-antennae tal-mobile phones
  HYP: x'inhi l-idea tiegħek dwar dawn l-antenni tal-mobaile honds
  diff: [Length Mismatch]
---------------
Sample #292
  REF: u ċertament din hija xi ħaġa li ma tistax tittolleraha
  HYP: u ċertament din hija xi ħaġa li ma tistax tittollera
  diff: [Length Mismatch]
---------------
Sample #308
  REF: ministru tista' tgħidilna x-xhieda min se jkunu
  HYP: ministru tista' tgħidilna x-xieda min se jkunu
  diff: [Length Mismatch]
---------------
Sample #310
  REF: il-poplu jevolvi meta l-kritika tittieħed bħala kostruttiva u mhux bħala tmaqdir
  HYP: il-poplu jevolvi meta l-kritika tittieħed bħala kostruttiva u mhux bħala tmaqdin
  diff:
---------------
Sample #312
  REF: dan apparti l-ammontkonsidervoli ta' mowbajls li l-maltin jixtru mill-internet
  HYP: dan apparti l-ammontkonsiderevoli ta' mobailes li l-maltin jixtru mill-internet
  diff: [Length Mismatch]
---------------
Sample #314
  REF: tista' tispjegaha din għax għandi dubju fuqha
  HYP: tista' tispjegaha din għax għandi dubji fuqha
  diff:
---------------
Sample #315
  REF: l-aġent skrivan tal-kamra qara l-ordnijiet tal-ġurnata
  HYP: l-aġent skrivan tal-kamra ara l-ordnijiet tal-ġurnata
  diff: [Length Mismatch]
---------------
Sample #317
  REF: ma kontx naf x'ġara mill-bqija tal-familja
  HYP: ma kontx naf x'ġar mill-bqija tal-familja
  diff: [Length Mismatch]
---------------
Sample #320
  REF: dan hu riżultat ta' żewġ fatturi prinċipali
  HYP: dan hu r-riżultat ta' żewġ fatturi prinċipali
  diff: [Length Mismatch]
---------------
Sample #324
  REF: apple ħabbru mudelli ġodda tal-ismartphone popolari iphone
  HYP: appl ħabru mudelli ġodda tal-ismarthon popolari iyhon
  diff: [Length Mismatch]
---------------
Sample #333
  REF: kull storja ta' emigrazzjoni hija unika
  HYP: kull storja ta' emmigrazzjoni hija unika
  diff: [Length Mismatch]
---------------
Sample #339
  REF: jista' l-gvern jagħti breakdown tan-nefqa
  HYP: jista' l-gvern jagħti breakdown tan-nafqa
  diff:
---------------
Sample #341
  REF: iżda kif qed insemmi l-kunsilli lokali ma nistax ma nagħmilx osservazzjoni
  HYP: iżda kif qed issemmi l-kunsill lokali ma nistax ma nagħmilx osservazzjoni
  diff: [Length Mismatch]
---------------
Sample #343
  REF: sur president jien nixtieq nerġa' nfakkar fil-qosor ħafna x'inhi demokrazija
  HYP: sur president jien nixtieq nerġa' nfakkar fil-qosor ħafna x'inhi d-demokrazija
  diff: [Length Mismatch]
---------------
Sample #345
  REF: imwielda l-isla u llum toqgħod wied il-għajn
  HYP: imwielda l-isna u llum toqgħod mit il-għajn
  diff: [Length Mismatch]
---------------
Sample #349
  REF: jien ma kontx naf x'se nagħmel bit-tarbija
  HYP: jien ma kontx naf se nagħmel bit-tarbija
  diff: [Length Mismatch]
---------------
Sample #350
  REF: anzi jien għedt li huwa għandu jkun ix-xhud prinċipali
  HYP: anzi jien għedd li huwa għandu jkun ix-xhud prinċipali
  diff:
---------------
Sample #353
  REF: kollha ġew fl-istess żmien naħseb li kieku tippjanahom ma jiġux hekk
  HYP: kollha ġew fl-istess żmien naħseb li kieku dippjanhom ma jiġux hekk
  diff: [Length Mismatch]
---------------
Sample #354
  REF: madanakollu din id-darba għandna sitwazzjoni li s'issa qatt ma kellna bħalha
  HYP: madankollu din id-darba għandna sitwazzjoni li s'issa qatt ma kellna bħalha
  diff: [Length Mismatch]
---------------
Sample #355
  REF: kien hemm programm partikolari bħalma huwa l-outlook
  HYP: kien hemm programm partikolari bħalma huwa l-outlok
  diff: [Length Mismatch]
---------------
Sample #357
  REF: konfront ieħor interessanti kien dak bejn kirkop united u fgura united
  HYP: konfront ieħor interessanti kien dak bejn circop junited u gura junited
  diff: [Length Mismatch]
---------------
Sample #359
  REF: kemm kienu jgħidu li din fabbrika tal-kanċer u smajniehom jirrepetuha llum ukoll
  HYP: kemm kienu jgħidu li din fabbrika tal-kanċer u smajniehom jirrepetu għalum ukoll
  diff:
---------------
Sample #370
  REF: karmni grima semgħet issejħilha l-madonna mill-kwadru tagħha f'ta' pinu
  HYP: carmny grima semet is-sejħilha l-madonna mill-kwadru tagħha f'tapinu
  diff: [Length Mismatch]
---------------
Sample #372
  REF: nistgħu issa ngħaddu għall-item li għandna fuq l-aġenda llejla
  HYP: nistgħu issa ngħaddu għall-aitem li għandna fuq l-aġenda llejla
  diff: [Length Mismatch]
---------------
Sample #374
  REF: il-bixra ta' wiċċhom waqt il-kompetizzjonijiet kienet taffaxxinak u tixhed determinazzjoni
  HYP: il-bixra ta' wiċċhom waqt il-kompetizzjonijiet kienet taffaxxinak u tixhety determinazzjoni
  diff: [Length Mismatch]
---------------
Sample #375
  REF: dimech kien mixli wkoll li kiser il-paċi pubblika
  HYP: dimekk kien mixli wkoll li kiser il-paċi pubblika
  diff:
---------------
Sample #379

{'wer': 0.07103321033210332,
 'cer': 0.015077894104092571,
 'mismatches': [{'index': 2,
   'ref': "xi tħobb f'pajjiżek",
   'hyp': "xi thobb f'pajjiżek"},
  {'index': 4,
   'ref': 'huwa suġġett għall-konfiska taħt dik il-proklama',
   'hyp': 'huwa suġġett tal-konfiska taħt dik il-proklama'},
  {'index': 8,
   'ref': 'isaac kien akkumpanjat mill-kowċ tiegħu u missieru alex bezzina',
   'hyp': 'aiżak kien ikkumpanjat mill-kowċ tiegħu u missieru alexs bezzina'},
  {'index': 14,
   'ref': 'din hija kompetizzjoni li tintlagħab fuq żewġ logħbiet kontra l-istess tim',
   'hyp': 'din hija kompetizzjoni li tintlagħab fuq żewġ lgħbiet kontra l-istess tim'},
  {'index': 15,
   'ref': 'ħalli ngħaddi issa għal dak li qed jingħad fir-rapport annwali',
   'hyp': 'ħalli ngħaddi iss għa dak li qed jingħad fir-rapport annwali'},
  {'index': 18,
   'ref': "x'investors programme hu dan",
   'hyp': "x'investor s programm hu dan"},
  {'index': 20,
   'ref': 'clint camilleri jew therese comodini cachia',
   'hyp': 'clint camilleri jew terese comodiny cachia'},
  {'index': 25,
   'ref': "nerġa' ngħidlek biex isserraħ moħħok għax is-sodod se nipprovduhom",
   'hyp': "nerġa' ngħidlek biex isseraħ moħok għax is-sodod se nipprovduhom"},
  {'index': 27,
   'ref': "b'xorti tajba ħarba oħra ta' żiemel ma kellha l-ebda konsegwenzi koroh",
   'hyp': "b'xorti tajba ħaba oħra ta' żiemel ma kellha l-ebda konsegwenzi koroh"},
  {'index': 29,
   'ref': 'kont il-brażil ukoll għat-tazza tad-dinja',
   'hyp': 'kont il-brażil ukoll għattazza tad-dinja'},
  {'index': 31,
   'ref': 'din l-informazzjoni kien ħariġha saviour balzan',
   'hyp': 'din l-informazzjoni kien ħariġha savior balzan'},
  {'index': 34,
   'ref': 'bħalissa għadha għaddejja t-tfittxija għall-kumplament tan-nies irrappurtati nieqsa',
   'hyp': 'bħalissa da ddejja tfittxija l-kumplament tan-nies irrappurtati nieqsa'},
  {'index': 39,
   'ref': "x'passi ttieħdu fil-konfront ta' dawk li nqabdu jkarkru",
   'hyp': "x'passi ttieħdu fil-konfront ta' dawk li nqabbdu jikkarkru"},
  {'index': 40,
   'ref': "dak il-ħin instema' għasfur ikanta fuq siġra",
   'hyp': "dak il-ħin instema' asfuri kanta fuq siġra"},
  {'index': 43,
   'ref': 'jiena infurmat li l-għażla li saret ġa qed tagħti l-frott',
   'hyp': 'jien infurmat li l-għażla li saret ġà qed tagħti frott'},
  {'index': 45,
   'ref': 'ħalli l-kummenti tiegħek hawn taħt bl-isem u l-kunjom',
   'hyp': 'ħalli l-kummenti tiegħek hawn taħt bl-isem u l-kunjum'},
  {'index': 50,
   'ref': 'ma xbajniex ngħidulkom',
   'hyp': 'ma ġbajniex ngħidulkom'},
  {'index': 56, 'ref': "tmerih f'wiċċu", 'hyp': "tmeriegħ f'wiċċu"},
  {'index': 61,
   'ref': "l-investigazzjoni qed issir f'nanterre pariġi",
   'hyp': "l-investigazzjoni qed issir f'nanterr pariġi"},
  {'index': 66,
   'ref': "il-konferenza għalqet b'diskors mill-isqof ta' għawdex monsmario grech",
   'hyp': "il-konferenza għalqet b'diskors mill-isqof ta' għawdex monsurmario grech"},
  {'index': 68,
   'ref': 'it-taħlit mhuwiex faċli biex isir u jrid ikollok knowledge sew',
   'hyp': 'it-taħlit mhuwiex faċli biex isir u jrid ikollok nolege sew'},
  {'index': 74,
   'ref': "issa wieħed jara kif tkompli għaddejja d-diskussjoni f'dan ir-rigward",
   'hyp': "issa wieħed jara bie komli għaddejj ħad-diskussjoni f'dan ir-rigward"},
  {'index': 77,
   'ref': "messi u missieru qed jiġu mixlija b'akkużi relatati ma' frodi",
   'hyp': "messi u missieri qed jiġu mixlija b'akkużi relatati ma' frodi"},
  {'index': 80,
   'ref': 'wara l-irġiel għallquha sakemm mietet',
   'hyp': 'wara l-irġiel għalquha sakemm mietet'},
  {'index': 83,
   'ref': 'irrid ngħid ukoll li dan is-self kollu ngħata mingħajr ebda garanzija',
   'hyp': 'irrid ngħid ukoll li dan is-self kollu ingħata mingħajr ebda garanzija'},
  {'index': 98,
   'ref': 'dak ukoll kien ordni reliġjuż',
   'hyp': 'dak ukoll kien ordni religius'},
  {'index': 103,
   'ref': 'dawn huma tliet stadji fuq normi internazzjonali',
   'hyp': 'dawn huma tliet stadi fuq normi internazzjonali'},
  {'index': 104,
   'ref': "x'tip ta' tajr ġie rreġistrat",
   'hyp': "x'tip ta' taire ġie rreġistrat"},
  {'index': 109,
   'ref': 'id-differenza bejniethom naturalment hija l-part - time',
   'hyp': 'id-differenza bejniethom naturalment hija l-part time'},
  {'index': 110,
   'ref': 'bl-ewro dgħajjef kumpaniji ewropej qed isibuha eħfef biex jesportaw',
   'hyp': 'bl-ewroday kumpaniji ewropeji qed isimuhoa eħfef biex jesportaw'},
  {'index': 114,
   'ref': "allura min se jerfa' r-responsabilità għal dan",
   'hyp': 'allura min se jerfa r-responsabbiltà għal dan'},
  {'index': 117,
   'ref': 'it-tfajla waqfet ħesrem u daret',
   'hyp': 'it-tfajla waffqet estrem u daret'},
  {'index': 119,
   'ref': "nerġa' ngħid li jien għandi biss kopja tar-rapport u tal-minute sheets",
   'hyp': 'nerġa ngħid li jien għandi biss kopja tar-rapport u tal-minut ts'},
  {'index': 124,
   'ref': "l-italja għandha foreign policy differenti minn ta' franza",
   'hyp': "l-italja għandha forene policy differenti minn ta' franza"},
  {'index': 125,
   'ref': "il-bomba splodiet f'ħin meta kienet għaddejja karozza tal-linja",
   'hyp': "il-bomba splodiet f'ħin meta kienet għaddejja karozz tal-linja"},
  {'index': 126,
   'ref': "ħassejtni fis-seba' sema li ksirt rekord nazzjonali",
   'hyp': "ħassejtni fis-seba' sema' li ksirt rekord nazzjonali"},
  {'index': 130,
   'ref': "jien tfajla li ili noħroġ ma' ġuvni aktar minn sentejn",
   'hyp': "jien tfajla li hili noħroġ ma' ġuvni aktar minn sentejn"},
  {'index': 131,
   'ref': 'dan kollu fir-rispett tad-drittijiettal-oppożizzjoni u tad-deputati individwali',
   'hyp': 'dan kollu fir-rispett ta- drittijiettal-oppożizzjoni u tad-deputati individwali'},
  {'index': 140,
   'ref': "ngħaddu għall-punt li jmiss fl-aġenda' affarijiet oħra'",
   'hyp': 'ngħaddu għall-punt li jmiss fl-aġenda affarijiet oħra'},
  {'index': 142,
   'ref': "dan minbarra l-iskemi ta' kreditu għall-intrapriżi żgħar u medji",
   'hyp': "dan minnbarra l-iskemi ta' kreditu għall-intrapriżi żgħar u medji"},
  {'index': 150,
   'ref': 'jien kelli okkażjoni nikteb fil-blog tiegħi fuq dan',
   'hyp': 'jien kelli okkażjoni nikteb fil-blokk tiegħi fuq dan'},
  {'index': 151,
   'ref': "genel hija l-kumpanija li qed tmexxi l-operazzjonijiet ta' tfittix taż-żejt",
   'hyp': 'gene hija l-kumpanija li qed tmexxi l-operazzjonijiet tat-tfittig taż-żejt'},
  {'index': 160,
   'ref': 'ikun żball jekk tiżen naħa waħda u tagħlaq għajnejk għal aspetti oħra',
   'hyp': 'ikun żbaljeak tiżen naħa waħda u tgħlaq għajnejk għall aspetti oħra'},
  {'index': 162,
   'ref': 'newsbook dot com dot mt hija waħda minnhom',
   'hyp': 'newsbook com mt hija waħda minnhom'},
  {'index': 164,
   'ref': 'bihom huma jgħinu lill-missjunarji maltin tal-pajjiżi foqra tat-tielet dinja',
   'hyp': 'biehom huma jgħinu lill-missjonarji maltin tal-pajjiżi foqra tat-tielet dinja'},
  {'index': 165,
   'ref': 'u biex wieħed josserva r-regoli jrid ikun hemm il-volontá',
   'hyp': 'u biex wieħed josserva r-regoli jrid ikun hemm il-volontà'},
  {'index': 168,
   'ref': 'jien personalment ma togħġobnix u anzi ġismi jqumli xewk xewk',
   'hyp': 'jien personalment ma togħġobnix u anzi ġismi jgqum li ċewk xewk'},
  {'index': 177,
   'ref': 'dan mingħajr ma jiġu esklużi l-ispeċi tradizzjonali bħall-awrat u l-ispnott',
   'hyp': 'dan mingħajr ma jiġu esklużi l-ispeċji tradizzjonali bħall-awrat u l-ispnot'},
  {'index': 183,
   'ref': 'it-tweġiba tiegħi kienet iva għandu jkollu l-libertà li jagħmel dak',
   'hyp': 'it-tweġiba tiegħi kienet iva għandu jkollu libertà li jagħmel dak'},
  {'index': 184,
   'ref': "biex wieħed jakkwista liċenzja għal arma jrid ikun irreġistrat ma' organizzazzjoni",
   'hyp': "biex wieħed jakkwista liċenzja għallarma jrid ikun irreġistrat ma' organizzazzjoni"},
  {'index': 185,
   'ref': "in-nuqqas f'dan il-każ kien min-naħa tal-land department",
   'hyp': "in-nuqqas f'dan il-każ kien min-naħa tal-lend department"},
  {'index': 188,
   'ref': "issa m'hemmx biss glieda mal-ħin iżda anke mal-maltemp",
   'hyp': "issa m'hemmx biss grieda mal-ħin iżda anke mal-maltemp"},
  {'index': 192,
   'ref': "john ma setax iżomm lura s-sarkażmu f'leħnu",
   'hyp': "jon ma setax iżomm lura s-sarkażmu f'leħnu"},
  {'index': 193,
   'ref': "nirien ħakmu bini abbandunat f'manoel island",
   'hyp': "nirien ħakmu bini abbandunat f'manoel iland"},
  {'index': 196,
   'ref': 'qalet li l-aħħar sena kienet waħda li biddlitilha ħajjitha',
   'hyp': 'qalet i l-aħħar sena kienet waħda li biddlit ilha ħajjitha'},
  {'index': 197,
   'ref': "is-sitwazzjoni hi li hemm bżonn ammontta' karozzi oħra",
   'hyp': "is-sitwazzjoni hi li hemm bżonn ammontta' kaozzi oħra"},
  {'index': 206,
   'ref': 'dan filwaqt li tħares ukoll il-benefiċċji tal-konsumaturi',
   'hyp': 'dan filwaqt li tħares ukoll lejn il-enfiċji tal-konsumaturi'},
  {'index': 213,
   'ref': "in-nannu sar sinjur f'daqqa u omm it-tarbija irrappurtatu lill-pulizija",
   'hyp': "in-nannu sar sinjur f'daqqa u omm it-tarbija rrappurtatu lill-pulizija"},
  {'index': 220,
   'ref': 'iż-żewġt irġiel kienu nżammu taħt arrest għal madwar jumejn',
   'hyp': 'iż-żewġ tirġiel kienu nżammu taħt arrest għal madwar jumejn'},
  {'index': 221,
   'ref': 'dawn l-irziezet inbnew fi żmien il-gran mastru lascaris',
   'hyp': 'dawn l-irziet se tinbnew fi żmien il-gram mastru l-askaris'},
  {'index': 222, 'ref': 'lill-irġiel', 'hyp': 'ill-irġiel'},
  {'index': 226,
   'ref': 'hu mistenni jirritorna lura fil-belt tal-vatikan dakinhar stess',
   'hyp': 'hu mistenni jirritorna lura fil-elt tal-vatikan dakinhar stess'},
  {'index': 227,
   'ref': 'kienet ilha nieżla xita qliel għal aktar minn jumejn bla waqfien',
   'hyp': "kienet ilha nieżla xi ta' qliel għal aktar minn jumejn bla waqfien"},
  {'index': 230,
   'ref': 'pereżempju qal li għal dan il-gvern l-arroganza saret virtù',
   'hyp': 'pereżempju għal dan il-gvern l-arroganza saret virtu'},
  {'index': 231,
   'ref': "ħadd ma weġġa' f'ħabta bejn trakk u karozza fil-wied tal-imsida",
   'hyp': "ħadd ma weġġa' f'ħabta bejn trakk u kaozza fil-wied tal-imsida"},
  {'index': 233,
   'ref': 'xi tgħidli dwar il-poligamija',
   'hyp': 'xi tgħid li dwar il-poligamija'},
  {'index': 235,
   'ref': "x'kien jisimhom dawn il-bċejjeċ tal-baħar",
   'hyp': "x'kien jisimhom dawk il-bċejjeċ tal-baħar"},
  {'index': 243,
   'ref': 'kieku dawn kisru jew weġġgħu lil xi ħadd orrajt',
   'hyp': 'kieku dawn kissru jewweġġaħu lil xi ħadd torraijt'},
  {'index': 244,
   'ref': 'dan ifisser li dawn kienu suppressed',
   'hyp': 'dan ifisser li dawn kienu sapprest'},
  {'index': 245,
   'ref': 'il-waiting lists bilfors jikbru',
   'hyp': 'il-wating lists bilfors jikbru'},
  {'index': 248,
   'ref': 'jimmy ma felaħx jirreżisti',
   'hyp': 'jimmi ma felaħx jirreżisti'},
  {'index': 251,
   'ref': 'jien ngħid li ħallejnielhom ħofra sabiħa għaliex ix-xogħol inbeda fi żmienna',
   'hyp': 'jien għid li ħallejnilhom ħafrna sabiħa għaliexix- xogħol inbeda fi żmienna'},
  {'index': 253,
   'ref': "dan wara li l-prezz kien ħa tisbita fil-bidu ta' ottubru",
   'hyp': "dan wara li l-prezz kien ħat isbita fil-bidu ta' ottubru"},
  {'index': 255, 'ref': 'taħt imneħirna', 'hyp': 'taħtimneħilna'},
  {'index': 262,
   'ref': "hija procedura normali li wara li jintefa' l-cable it-trinka tintradam",
   'hyp': "hija proċedura normali li wara li intefa' l-kcabel it-trinka tintradam"},
  {'index': 264,
   'ref': 'oriġinarjament maradona kellu jkun parti mill-istaff tekniku matul is-sajf li għadda',
   'hyp': 'oriġinarjament maradona kellu jkun parti mill-istaff tekniku matulis sajf li għadda'},
  {'index': 267,
   'ref': "m'għandix għalfejn neħodha bi kbira meta nagħmel xi żball",
   'hyp': "m'għandix għalfejn noħodha bi kbira meta nagħmel xi żball"},
  {'index': 269,
   'ref': 'anke l-ministru kemm-il darba deher fil-media u qal hekk',
   'hyp': 'anke l-ministru kemm il darba dir fil-midja u qal lek'},
  {'index': 273,
   'ref': 'il-gvern jemmen bis-sħiħ fiż-żgħażagħ',
   'hyp': 'il-gvern jemmen bi sħieħ fiż-żgħażagħ'},
  {'index': 276,
   'ref': 'bikram arora u haroon majeed kienu ferm dominanti',
   'hyp': 'bikram arora u haron majed kienu ferm dominanti'},
  {'index': 277,
   'ref': "kont ilek tafu seba' snin ma tafx fejn għandu kont",
   'hyp': "kontilek tafu seba' snin ma tafx fejn għandu kont"},
  {'index': 280,
   'ref': "u wara l-handover purposes x'kont se tagħmel tirritornahom",
   'hyp': "uwara l-handover parposis x'kont se tagħmel tirritorna howm"},
  {'index': 281,
   'ref': "ħallu lilkom infuskom issibu l-ħniena t'alla",
   'hyp': "ħallu lilkom infuskom issibu l-ħdiena t'alla"},
  {'index': 284,
   'ref': "qatt m'emmint li t-triq tas-suċċess hija faċli",
   'hyp': "qatt m'emmint li t-triq tas suċċess hija faċli"},
  {'index': 286,
   'ref': "qed ngħidilkom biex tmorru ftit s'hemmhekk ħalli taraw b'għajnejkom",
   'hyp': "qed ngħidilkom biex tmorru ftit s'hemmhekk ħalli taraw b'għanejkom"},
  {'index': 287,
   'ref': 'kemm ilek ma trodd salib fil-pubbliku',
   'hyp': 'kemm hilek ma trozgalib fil-pubbliku'},
  {'index': 289,
   'ref': 'dawn qed jaħdmu taħt pressjoni kontinwa kemm minn fuq kif ukoll minn isfel',
   'hyp': 'dawn qed jaħdmu ba taħt pressjoni kontinwa kemm minn fuq kif ukoll minn isfel'},
  {'index': 291,
   'ref': "x'inhi l-idea tiegħek dwar dawn l-antennae tal-mobile phones",
   'hyp': "x'inhi l-idea tiegħek dwar dawn l-antenni tal-mobaile honds"},
  {'index': 292,
   'ref': 'u ċertament din hija xi ħaġa li ma tistax tittolleraha',
   'hyp': 'u ċertament din hija xi ħaġa li ma tistax tittollera'},
  {'index': 308,
   'ref': "ministru tista' tgħidilna x-xhieda min se jkunu",
   'hyp': "ministru tista' tgħidilna x-xieda min se jkunu"},
  {'index': 310,
   'ref': 'il-poplu jevolvi meta l-kritika tittieħed bħala kostruttiva u mhux bħala tmaqdir',
   'hyp': 'il-poplu jevolvi meta l-kritika tittieħed bħala kostruttiva u mhux bħala tmaqdin'},
  {'index': 312,
   'ref': "dan apparti l-ammontkonsidervoli ta' mowbajls li l-maltin jixtru mill-internet",
   'hyp': "dan apparti l-ammontkonsiderevoli ta' mobailes li l-maltin jixtru mill-internet"},
  {'index': 314,
   'ref': "tista' tispjegaha din għax għandi dubju fuqha",
   'hyp': "tista' tispjegaha din għax għandi dubji fuqha"},
  {'index': 315,
   'ref': 'l-aġent skrivan tal-kamra qara l-ordnijiet tal-ġurnata',
   'hyp': 'l-aġent skrivan tal-kamra ara l-ordnijiet tal-ġurnata'},
  {'index': 317,
   'ref': "ma kontx naf x'ġara mill-bqija tal-familja",
   'hyp': "ma kontx naf x'ġar mill-bqija tal-familja"},
  {'index': 320,
   'ref': "dan hu riżultat ta' żewġ fatturi prinċipali",
   'hyp': "dan hu r-riżultat ta' żewġ fatturi prinċipali"},
  {'index': 324,
   'ref': 'apple ħabbru mudelli ġodda tal-ismartphone popolari iphone',
   'hyp': 'appl ħabru mudelli ġodda tal-ismarthon popolari iyhon'},
  {'index': 333,
   'ref': "kull storja ta' emigrazzjoni hija unika",
   'hyp': "kull storja ta' emmigrazzjoni hija unika"},
  {'index': 339,
   'ref': "jista' l-gvern jagħti breakdown tan-nefqa",
   'hyp': "jista' l-gvern jagħti breakdown tan-nafqa"},
  {'index': 341,
   'ref': 'iżda kif qed insemmi l-kunsilli lokali ma nistax ma nagħmilx osservazzjoni',
   'hyp': 'iżda kif qed issemmi l-kunsill lokali ma nistax ma nagħmilx osservazzjoni'},
  {'index': 343,
   'ref': "sur president jien nixtieq nerġa' nfakkar fil-qosor ħafna x'inhi demokrazija",
   'hyp': "sur president jien nixtieq nerġa' nfakkar fil-qosor ħafna x'inhi d-demokrazija"},
  {'index': 345,
   'ref': 'imwielda l-isla u llum toqgħod wied il-għajn',
   'hyp': 'imwielda l-isna u llum toqgħod mit il-għajn'},
  {'index': 349,
   'ref': "jien ma kontx naf x'se nagħmel bit-tarbija",
   'hyp': 'jien ma kontx naf se nagħmel bit-tarbija'},
  {'index': 350,
   'ref': 'anzi jien għedt li huwa għandu jkun ix-xhud prinċipali',
   'hyp': 'anzi jien għedd li huwa għandu jkun ix-xhud prinċipali'},
  {'index': 353,
   'ref': 'kollha ġew fl-istess żmien naħseb li kieku tippjanahom ma jiġux hekk',
   'hyp': 'kollha ġew fl-istess żmien naħseb li kieku dippjanhom ma jiġux hekk'},
  {'index': 354,
   'ref': "madanakollu din id-darba għandna sitwazzjoni li s'issa qatt ma kellna bħalha",
   'hyp': "madankollu din id-darba għandna sitwazzjoni li s'issa qatt ma kellna bħalha"},
  {'index': 355,
   'ref': 'kien hemm programm partikolari bħalma huwa l-outlook',
   'hyp': 'kien hemm programm partikolari bħalma huwa l-outlok'},
  {'index': 357,
   'ref': 'konfront ieħor interessanti kien dak bejn kirkop united u fgura united',
   'hyp': 'konfront ieħor interessanti kien dak bejn circop junited u gura junited'},
  {'index': 359,
   'ref': 'kemm kienu jgħidu li din fabbrika tal-kanċer u smajniehom jirrepetuha llum ukoll',
   'hyp': 'kemm kienu jgħidu li din fabbrika tal-kanċer u smajniehom jirrepetu għalum ukoll'},
  {'index': 370,
   'ref': "karmni grima semgħet issejħilha l-madonna mill-kwadru tagħha f'ta' pinu",
   'hyp': "carmny grima semet is-sejħilha l-madonna mill-kwadru tagħha f'tapinu"},
  {'index': 372,
   'ref': 'nistgħu issa ngħaddu għall-item li għandna fuq l-aġenda llejla',
   'hyp': 'nistgħu issa ngħaddu għall-aitem li għandna fuq l-aġenda llejla'},
  {'index': 374,
   'ref': "il-bixra ta' wiċċhom waqt il-kompetizzjonijiet kienet taffaxxinak u tixhed determinazzjoni",
   'hyp': "il-bixra ta' wiċċhom waqt il-kompetizzjonijiet kienet taffaxxinak u tixhety determinazzjoni"},
  {'index': 375,
   'ref': 'dimech kien mixli wkoll li kiser il-paċi pubblika',
   'hyp': 'dimekk kien mixli wkoll li kiser il-paċi pubblika'},
  {'index': 379,
   'ref': "dmugħ tal-kukkudrilli ta' min dejjem jurik wiċċ imbagħad jagħmel mod ieħor",
   'hyp': "moħħ ta' kukkudrilli ta' min dejje jrid wiċċ imbagħad jagħmel mod ieħor"},
  {'index': 383,
   'ref': 'dak huwa argument ieħor fejn nistgħu ngħidu għal opt - out',
   'hyp': 'dak huwa argument ieħor fejn nistgħu ngħidu għall opthout'},
  {'index': 384,
   'ref': "skont il-birdlife l-isparar sar f'erba' lokalitajiet differenti madwar malta",
   'hyp': "skont il-bordlife l-isparar sar f'erba' lokalitajiet differenti madwar malta"},
  {'index': 387,
   'ref': 'din abbandunawha għax kien proġett tal-partit laburista kif abbandunaw proġetti oħra',
   'hyp': 'din abbandunawha għax kien proġett tal-partit laburista kieku abbandunaw proġetti oħra'},
  {'index': 396,
   'ref': 'talb fis-skiet quddiem ġesù sagramentat',
   'hyp': 'talb fis-skiet quddiem ġesu sagramentat'},
  {'index': 398,
   'ref': 'dawn huma problemi li xbajna nisimgħu dwarhom',
   'hyp': 'dawn huma problemi li ġbajna nisimgħu dwarhom'},
  {'index': 399,
   'ref': 'illum għandna sitwazzjoni fejn id-drenaġġkollu li jipproduċi l-pajjiż jiġi trattat',
   'hyp': 'illum għandna sitwazzjoni fejn id-dranaġġkollu li jipproduċi l-pajjiż jiġi trattat'},
  {'index': 400,
   'ref': "it-tieni nett aħna lanqas ma naqblu mal-konċett ta' kera",
   'hyp': "it-tieni nett aħna lanqas ma naqblu mal-kunċett ta' kera"},
  {'index': 401,
   'ref': 'biss dik il-korrespondenza ma kkonkludiet xejn',
   'hyp': 'biss dik il-korrespondenza ma konkludiet xejn'},
  {'index': 403,
   'ref': "jien wisq nibża' li l-oppożizzjoni m'għandhiex pjan fis-saħħa",
   'hyp': "jien usq nibża' li l-oppożizzjoni m'għandhiex pjan fis-saħħa"},
  {'index': 404,
   'ref': 'din appellat għas-sens komun tan-nies u naħseb li ħafna qablu magħha',
   'hyp': 'din appella tas-sens komun tan-nies u naħseb li ħafna qablu magħha'},
  {'index': 410,
   'ref': 'dan huwa d-diffett tal-politiċi opportunisti',
   'hyp': 'dan huwa d-difett tal-politiċi opportunisti'},
  {'index': 418,
   'ref': 'naħseb li nkunu qed indgħajfuha ħafna',
   'hyp': 'naħseb li nkunu qegħdindajfuha ħafna'},
  {'index': 420, 'ref': 'tuh l-uno', 'hyp': 'tuħlunu'},
  {'index': 422,
   'ref': 'christine mill-ewwel għannqitu u aċċettat il-proposta għaż-żwieġ',
   'hyp': 'cristin mill-ewwel għanqitu u aċċettat il-proposta għaż-żwieġ'},
  {'index': 424,
   'ref': "john ma setax iżomm lura s-sarkażmu f'leħnu",

##### Common Voise Untokenised

In [ ]:
evaluate_raw_model(common_voice_test)

--- Evaluating 1224 samples (Greedy Decoding) ---

100%|██████████| 1224/1224 [01:52<00:00, 10.89it/s]

===================================
RAW MODEL RESULTS:
WER: 0.0667 (6.67%)
CER: 0.0141 (1.41%)
===================================

Sample Transcriptions:
REF: dan ma sar qatt
HYP: dan ma sar qatt
----------
REF: min jaf kif u biex se jimlewha
HYP: min jaf kif u biex se jimlewha
----------

{'wer': 0.0666819958611175, 'cer': 0.014053007543894786}

In [19]:
evaluate_raw_model(masri_test)

--- Evaluating 668 samples (Greedy Decoding) ---

100%|██████████| 668/668 [01:11<00:00,  9.28it/s]

===================================
RAW MODEL RESULTS:
WER: 0.2894 (28.94%)
CER: 0.0989 (9.89%)
===================================

Sample Transcriptions:
REF: maskarat tini perlina għax warajk għandek xadina minflok waħda tini tnejn biex warajk ma jkollok xejn
HYP: maskerattini perlina għax warajk għandek xadina minflok waħda tini - tnejn għiex warajk ma jkollok xejn
----------
REF: eħe f' dan is- suġġett se nagħtu ħarsa lejn in- novelli u r- rumanzi tal- awturi maltin kosmopolitani jiġifieri li bdew jiktbu
HYP: eħe f' dan is- suġġett se nagħtu ħarsa lejn in-novelli u r- rumanzi ta' l- awturi maltin kosmopolitan jiġifierili bdew jiktbu
----------

{'wer': 0.28939313984168863, 'cer': 0.0989193083573487}

#### With LM

In [19]:
import torch
from pathlib import Path
from transformers import Wav2Vec2BertForCTC, Wav2Vec2BertProcessor
from pyctcdecode import build_ctcdecoder
from jiwer import wer, cer
from tqdm import tqdm

# 1. Setup paths
base_path = Path(".") 
my_model_path = base_path / "Runs" / "SplitRunReducedNoToken" / "checkpoint-2780"
LM_PATH = str(base_path / "3_tok_red.bin")

device = "cuda" if torch.cuda.is_available() else "cpu"

# 2. Load Model and Processor
model = Wav2Vec2BertForCTC.from_pretrained(my_model_path).to(device)
processor = Wav2Vec2BertProcessor.from_pretrained(my_model_path)
model.eval()

# 3. Prepare Decoder Vocab
vocab = processor.tokenizer.get_vocab()
sorted_vocab = [k for k, v in sorted(vocab.items(), key=lambda item: item[1])]

def evaluate_kenlm_manual(dataset, alpha=0.85, beta=4.0):
    all_logits_numpy = []
    all_ground_truths = []
    greedy_preds = []

    print(f"--- Step 1: Generating Logits for {len(dataset)} samples ---")
    
    for i in tqdm(range(len(dataset))):
        batch = dataset[i]
        audio = batch["audio"]["array"] 
        
        inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
        input_features = inputs.input_features.to(device)

        with torch.no_grad():
            logits = model(input_features).logits
        
        all_logits_numpy.append(logits.cpu().numpy()[0])
        all_ground_truths.append(batch["sentence"].lower())
        
        pred_ids = torch.argmax(logits, dim=-1)
        greedy_preds.append(processor.batch_decode(pred_ids)[0].lower())

    # Calculate Raw Metrics
    baseline_wer = wer(all_ground_truths, greedy_preds)
    baseline_cer = cer(all_ground_truths, greedy_preds)

    # --- Step 2: Decode with fixed KenLM parameters ---
    print(f"\n--- Step 2: Decoding with KenLM (Alpha: {alpha}, Beta: {beta}) ---")
    
    decoder = build_ctcdecoder(
        labels=sorted_vocab,
        kenlm_model_path=LM_PATH,
        alpha=alpha,
        beta=beta
    )
    
    kenlm_preds = [decoder.decode(l).lower() for l in all_logits_numpy]
    kenlm_wer = wer(all_ground_truths, kenlm_preds)
    kenlm_cer = cer(all_ground_truths, kenlm_preds)

    # --- Final Results ---
    print("\n" + "="*45)
    print(f"{'Metric':<10} | {'Raw Model':<12} | {'With KenLM':<12}")
    print("-" * 45)
    print(f"{'WER':<10} | {baseline_wer:<12.4f} | {kenlm_wer:<12.4f}")
    print(f"{'CER':<10} | {baseline_cer:<12.4f} | {kenlm_cer:<12.4f}")
    print("="*45)
    
    improvement = baseline_wer - kenlm_wer
    print(f"\nWER Improvement: {improvement:.4f}")
    
    return {"raw_wer": baseline_wer, "kenlm_wer": kenlm_wer}

#### Big Run - COmbined but my test set not aidens.

In [20]:
results = evaluate_kenlm_manual(common_voice_test, alpha=0.5, beta=3.0)

--- Step 1: Generating Logits for 1892 samples ---

100%|██████████| 1892/1892 [02:59<00:00, 10.51it/s]
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

--- Step 2: Decoding with KenLM (Alpha: 0.5, Beta: 3.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.2144       | 0.2138
CER        | 0.0580       | 0.0610
=============================================

WER Improvement: 0.0006

#### Big Run - Common Voice

In [ ]:
results = evaluate_kenlm_manual(common_voice_test, alpha=0.5, beta=3.0)

##### Split Run Reduced Non-Tokenised

In [ ]:
results = evaluate_kenlm_manual(common_voice_test, alpha=0.7, beta=3.0)

##### SplitRun

In [19]:
results = evaluate_kenlm_manual(common_voice_test, alpha=0.7, beta=3.0)

--- Step 1: Generating Logits for 1892 samples ---

100%|██████████| 1892/1892 [03:00<00:00, 10.46it/s]
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

--- Step 2: Decoding with KenLM (Alpha: 0.7, Beta: 3.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.1850       | 0.1546
CER        | 0.0592       | 0.0590
=============================================

WER Improvement: 0.0304

##### Mid Reduction

In [21]:
results = evaluate_kenlm_manual(common_voice_test, alpha=0.7, beta=3.0)

--- Step 1: Generating Logits for 1892 samples ---

100%|██████████| 1892/1892 [03:01<00:00, 10.42it/s]
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

--- Step 2: Decoding with KenLM (Alpha: 0.7, Beta: 3.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.1842       | 0.1503
CER        | 0.0573       | 0.0563
=============================================

WER Improvement: 0.0339

##### High Reduction

In [23]:
results = evaluate_kenlm_manual(common_voice_test, alpha=0.7, beta=3.0)

--- Step 1: Generating Logits for 1892 samples ---

100%|██████████| 1892/1892 [03:00<00:00, 10.50it/s]
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

--- Step 2: Decoding with KenLM (Alpha: 0.7, Beta: 3.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.1833       | 0.1525
CER        | 0.0578       | 0.0577
=============================================

WER Improvement: 0.0308

#### With Unigrams

In [20]:
import torch
import time
from pathlib import Path
from transformers import Wav2Vec2BertForCTC, Wav2Vec2BertProcessor
from pyctcdecode import build_ctcdecoder
from jiwer import wer, cer
from tqdm import tqdm

# 1. Setup paths
base_path = Path(".") 
my_model_path = base_path / "Runs" / "checkpoint-5500"
LM_PATH = str(base_path / "3_untok_red.bin")
ARPA_PATH = str(base_path / "3_untok_red.arpa") # We need the text version for unigrams

device = "cuda" if torch.cuda.is_available() else "cpu"

# 2. Load Model and Processor
model = Wav2Vec2BertForCTC.from_pretrained(my_model_path).to(device)
processor = Wav2Vec2BertProcessor.from_pretrained(my_model_path)
model.eval()

# 3. Prepare Decoder Vocab
vocab = processor.tokenizer.get_vocab()
sorted_vocab = [k for k, v in sorted(vocab.items(), key=lambda item: item[1])]

# --- NEW: Extract unigrams from ARPA to pass into the binary decoder ---
def get_unigram_list(arpa_path):
    unigrams = []
    with open(arpa_path, "r") as f:
        is_unigram_section = False
        for line in f:
            if "\\1-grams:" in line:
                is_unigram_section = True
                continue
            if "\\2-grams:" in line or line.startswith("\\end\\"):
                break
            if is_unigram_section:
                parts = line.strip().split()
                if len(parts) >= 2:
                    word = parts[1]
                    if word not in ["<s>", "</s>", "<unk>"]:
                        unigrams.append(word)
    return unigrams

print("Extracting unigrams...")
unigrams = get_unigram_list(ARPA_PATH)
# -----------------------------------------------------------------------

Extracting unigrams...

In [21]:
def evaluate_kenlm_manual(dataset, alpha=0.85, beta=4.0):
    all_logits_numpy = []
    all_ground_truths = []
    greedy_preds = []

    print(f"--- Step 1: Generating Logits for {len(dataset)} samples ---")
    
    for i in tqdm(range(len(dataset))):
        batch = dataset[i]
        audio = batch["audio"]["array"] 
        
        inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
        input_features = inputs.input_features.to(device)

        with torch.no_grad():
            logits = model(input_features).logits
        
        all_logits_numpy.append(logits.cpu().numpy()[0])
        all_ground_truths.append(batch["sentence"].lower())
        
        pred_ids = torch.argmax(logits, dim=-1)
        greedy_preds.append(processor.batch_decode(pred_ids)[0].lower())

    # Calculate Raw Metrics
    baseline_wer = wer(all_ground_truths, greedy_preds)
    baseline_cer = cer(all_ground_truths, greedy_preds)

    # --- Step 2: Decode with fixed KenLM parameters ---
    print(f"\n--- Step 2: Decoding with KenLM (Alpha: {alpha}, Beta: {beta}) ---")
    
    # UPDATED: Added 'unigrams' argument
    decoder = build_ctcdecoder(
        labels=sorted_vocab,
        kenlm_model_path=LM_PATH,
        unigrams=unigrams, # <--- Crucial fix
        alpha=alpha,
        beta=beta
    )
    
    kenlm_preds = [decoder.decode(l).lower() for l in all_logits_numpy]
    kenlm_wer = wer(all_ground_truths, kenlm_preds)
    kenlm_cer = cer(all_ground_truths, kenlm_preds)

    # --- Final Results ---
    print("\n" + "="*45)
    print(f"{'Metric':<10} | {'Raw Model':<12} | {'With KenLM':<12}")
    print("-" * 45)
    print(f"{'WER':<10} | {baseline_wer:<12.4f} | {kenlm_wer:<12.4f}")
    print(f"{'CER':<10} | {baseline_cer:<12.4f} | {kenlm_cer:<12.4f}")
    print("="*45)
    
    improvement = baseline_wer - kenlm_wer
    print(f"\nWER Improvement: {improvement:.4f}")
    
    return {"raw_wer": baseline_wer, "kenlm_wer": kenlm_wer}

In [22]:
### Optimal Checkpoint on CV ONly
results = evaluate_kenlm_manual(common_voice_test, alpha=0.5, beta=3.0)

--- Step 1: Generating Logits for 1224 samples ---

100%|██████████| 1224/1224 [01:51<00:00, 11.00it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Step 2: Decoding with KenLM (Alpha: 0.5, Beta: 3.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.0538       | 0.0386
CER        | 0.0116       | 0.0093
=============================================

WER Improvement: 0.0152

In [20]:
### Optimal Checkpoint on MASRI
results = evaluate_kenlm_manual(common_voice_test, alpha=0.5, beta=3.0)

--- Step 1: Generating Logits for 668 samples ---

100%|██████████| 668/668 [01:26<00:00,  7.68it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Step 2: Decoding with KenLM (Alpha: 0.5, Beta: 3.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.2241       | 0.1989
CER        | 0.0747       | 0.0741
=============================================

WER Improvement: 0.0252

In [21]:
### Checking the optimal checkpoint on combined
results = evaluate_kenlm_manual(common_voice_test, alpha=0.5, beta=3.0)

--- Step 1: Generating Logits for 1892 samples ---

100%|██████████| 1892/1892 [03:05<00:00, 10.20it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Step 2: Decoding with KenLM (Alpha: 0.5, Beta: 3.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.1360       | 0.1160
CER        | 0.0416       | 0.0401
=============================================

WER Improvement: 0.0200

In [20]:
# Masri Test
results = evaluate_kenlm_manual(common_voice_test, alpha=0.5, beta=3.0)

--- Step 1: Generating Logits for 668 samples ---

100%|██████████| 668/668 [01:25<00:00,  7.80it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Step 2: Decoding with KenLM (Alpha: 0.5, Beta: 3.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.2262       | 0.1966
CER        | 0.0729       | 0.0712
=============================================

WER Improvement: 0.0296

In [23]:
results = evaluate_kenlm_manual(common_voice_test, alpha=0.5, beta=3.0)

--- Step 1: Generating Logits for 1892 samples ---

100%|██████████| 1892/1892 [03:05<00:00, 10.21it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Step 2: Decoding with KenLM (Alpha: 0.5, Beta: 3.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.1374       | 0.1148
CER        | 0.0408       | 0.0386
=============================================

WER Improvement: 0.0226

In [24]:
results = evaluate_kenlm_manual(common_voice_test, alpha=0.5, beta=3.0)

--- Step 1: Generating Logits for 1224 samples ---

100%|██████████| 1224/1224 [02:16<00:00,  8.98it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Step 2: Decoding with KenLM (Alpha: 0.5, Beta: 3.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.0546       | 0.0385
CER        | 0.0117       | 0.0092
=============================================

WER Improvement: 0.0161

In [ ]:
results = evaluate_kenlm_manual(common_voice_test, alpha=0.7, beta=3.0)

--- Step 1: Generating Logits for 1892 samples ---

100%|██████████| 1892/1892 [02:58<00:00, 10.60it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Step 2: Decoding with KenLM (Alpha: 0.7, Beta: 3.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.1833       | 0.1457
CER        | 0.0578       | 0.0552
=============================================

WER Improvement: 0.0376

Alright! The transcription can definitely be recognized from our prediction, but it is not perfect yet. Training the model a bit longer, spending more time on the data preprocessing, and especially using a language model for decoding would certainly improve the model's overall performance.

For a demonstration model on a low-resource language, the results are quite acceptable however 🤗.

#### Evaluating with beam width

In [22]:
def evaluate_kenlm_manual(dataset, alpha=0.85, beta=4.0):
    all_logits_numpy = []
    all_ground_truths = []
    greedy_preds = []

    print(f"--- Step 1: Generating Logits for {len(dataset)} samples ---")
    
    for i in tqdm(range(len(dataset))):
        batch = dataset[i]
        audio = batch["audio"]["array"] 
        
        inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
        input_features = inputs.input_features.to(device)

        with torch.no_grad():
            logits = model(input_features).logits
        
        all_logits_numpy.append(logits.cpu().numpy()[0])
        all_ground_truths.append(batch["sentence"].lower())
        
        pred_ids = torch.argmax(logits, dim=-1)
        greedy_preds.append(processor.batch_decode(pred_ids)[0].lower())

    # Calculate Raw Metrics
    baseline_wer = wer(all_ground_truths, greedy_preds)
    baseline_cer = cer(all_ground_truths, greedy_preds)

    # --- Step 2: Decode with fixed KenLM parameters (Default Beam 100) ---
    print(f"\n--- Step 2: Decoding with KenLM (Alpha: {alpha}, Beta: {beta}, Beam: 100) ---")
    
    decoder = build_ctcdecoder(
        labels=sorted_vocab,
        kenlm_model_path=LM_PATH,
        unigrams=unigrams, 
        alpha=alpha,
        beta=beta
    )
    
    kenlm_preds = [decoder.decode(l).lower() for l in all_logits_numpy]
    kenlm_wer = wer(all_ground_truths, kenlm_preds)
    kenlm_cer = cer(all_ground_truths, kenlm_preds)

    # --- Step 3: Beam Sensitivity Analysis ---
    # This specifically addresses your thesis question: "Does search depth matter?"
    print(f"\n--- Step 3: Beam Sensitivity Analysis (Testing Search Depth) ---")
    print(f"{'Beam Width':<12} | {'WER':<10} | {'Time (s)':<10}")
    print("-" * 35)
    
    beam_results = {}
    for bw in [32, 100, 128, 512]: # Narrow, slightly above default, and deep
        start_time = time.time()
        # We pass beam_width explicitly here
        preds = [decoder.decode(l, beam_width=bw).lower() for l in all_logits_numpy]
        bw_wer = wer(all_ground_truths, preds)
        elapsed = time.time() - start_time
        
        print(f"{bw:<12} | {bw_wer:<10.4f} | {elapsed:<10.2f}")
        beam_results[bw] = bw_wer

    # --- Final Results Report ---
    print("\n" + "="*45)
    print(f"{'Metric':<10} | {'Raw Model':<12} | {'With KenLM':<12}")
    print("-" * 45)
    print(f"{'WER':<10} | {baseline_wer:<12.4f} | {kenlm_wer:<12.4f}")
    print(f"{'CER':<10} | {baseline_cer:<12.4f} | {kenlm_cer:<12.4f}")
    print("="*45)
    
    improvement = baseline_wer - kenlm_wer
    print(f"\nBaseline vs KenLM (100 beam) Improvement: {improvement:.4f}")
    
    # Thesis-ready insight:
    deep_gain = kenlm_wer - beam_results[512]
    if deep_gain > 0.001:
        print(f"Note: Increasing beam to 512 unlocked an additional {deep_gain:.4f} WER reduction.")
    else:
        print("Note: Increasing beam width beyond 100 yielded no significant gain.")
    
    return {"raw_wer": baseline_wer, "kenlm_wer": kenlm_wer, "beam_results": beam_results}

#### Trigram Big model

In [23]:
results = evaluate_kenlm_manual(common_voice_dev, alpha=0.5, beta=3.0)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [02:47<00:00, 11.25it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Step 2: Decoding with KenLM (Alpha: 0.5, Beta: 3.0, Beam: 100) ---

--- Step 3: Beam Sensitivity Analysis (Testing Search Depth) ---
Beam Width   | WER        | Time (s)
-----------------------------------
32           | 0.1079     | 71.63
100          | 0.1064     | 110.06
128          | 0.1067     | 122.44
512          | 0.1076     | 301.32

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.1237       | 0.1064
CER        | 0.0358       | 0.0339
=============================================

Baseline vs KenLM (100 beam) Improvement: 0.0173
Note: Increasing beam width beyond 100 yielded no significant gain.

In [27]:
results = evaluate_kenlm_manual(common_voice_test, alpha=0.7, beta=3.0)

--- Step 1: Generating Logits for 1892 samples ---

100%|██████████| 1892/1892 [02:59<00:00, 10.54it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Step 2: Decoding with KenLM (Alpha: 0.7, Beta: 3.0, Beam: 100) ---

--- Step 3: Beam Sensitivity Analysis (Testing Search Depth) ---
Beam Width   | WER        | Time (s)
-----------------------------------
32           | 0.1475     | 44.04
128          | 0.1424     | 81.87
512          | 0.1419     | 270.34

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.1842       | 0.1429
CER        | 0.0573       | 0.0538
=============================================

Baseline vs KenLM (100 beam) Improvement: 0.0413
Note: Increasing beam to 512 unlocked an additional 0.0010 WER reduction.

#### Normalised Test

In [26]:
import torch
import numpy as np
from pathlib import Path
from transformers import Wav2Vec2BertForCTC, Wav2Vec2BertProcessor
from pyctcdecode import build_ctcdecoder
from jiwer import wer, cer
from tqdm import tqdm

# ==========================================
# 1. Normalization Protocol for Fair Testing
# ==========================================
def normalize_maltese_text(text):
    """
    Maps low-frequency/noisy characters back to the core Maltese set.
    This ensures models with larger vocabularies are not penalized for 
    phonetic variants not present in the ground truth.
    """
    if not text:
        return ""
    
    # Define mapping for characters with <20 occurrences or foreign accents
    mapping = {
        "á": "a", 
        "é": "e", 
        "ć": "ċ",
        "`": "",   # Remove backticks/noise symbols
        "´": "",
    }
    
    text = text.lower()
    for noisy_char, clean_char in mapping.items():
        text = text.replace(noisy_char, clean_char)
        
    # Standardize whitespace
    return " ".join(text.split())

In [27]:
# ==========================================
# 2. Setup Paths & Device
# ==========================================
base_path = Path(".") 
# Update this path to the specific checkpoint you are testing (Split, Mid, or Reduced)
my_model_path = base_path / "Runs" / "SplitRunReduced" / "checkpoint-2780"
LM_PATH = str(base_path / "3_tok_red.bin")

device = "cuda" if torch.cuda.is_available() else "cpu"

# ==========================================
# 3. Load Model and Processor
# ==========================================
print(f"Loading model from: {my_model_path}")
model = Wav2Vec2BertForCTC.from_pretrained(my_model_path).to(device)
processor = Wav2Vec2BertProcessor.from_pretrained(my_model_path)
model.eval()

# Prepare Decoder Vocab
vocab = processor.tokenizer.get_vocab()
sorted_vocab = [k for k, v in sorted(vocab.items(), key=lambda item: item[1])]

# ==========================================
# 4. Evaluation Function
# ==========================================
def evaluate_kenlm_manual(dataset, alpha=0.85, beta=4.0):
    all_logits_numpy = []
    all_ground_truths = []
    greedy_preds = []

    print(f"--- Step 1: Generating Logits for {len(dataset)} samples ---")
    
    for i in tqdm(range(len(dataset))):
        batch = dataset[i]
        audio = batch["audio"]["array"] 
        
        inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
        input_features = inputs.input_features.to(device)

        with torch.no_grad():
            logits = model(input_features).logits
        
        all_logits_numpy.append(logits.cpu().numpy()[0])
        all_ground_truths.append(batch["sentence"]) # Lowercasing handled in normalization
        
        pred_ids = torch.argmax(logits, dim=-1)
        greedy_preds.append(processor.batch_decode(pred_ids)[0])

    # --- Step 2: Decoding with KenLM ---
    print(f"\n--- Step 2: Decoding with KenLM (Alpha: {alpha}, Beta: {beta}) ---")
    
    decoder = build_ctcdecoder(
        labels=sorted_vocab,
        kenlm_model_path=LM_PATH,
        alpha=alpha,
        beta=beta
    )
    
    # Generate raw KenLM predictions
    kenlm_preds = [decoder.decode(l) for l in all_logits_numpy]

    # --- Step 3: Apply Normalization for Fair Comparison ---
    # This step is CRITICAL for the thesis to isolate acoustic performance
    clean_ground_truths = [normalize_maltese_text(gt) for gt in all_ground_truths]
    clean_greedy_preds = [normalize_maltese_text(p) for p in greedy_preds]
    clean_kenlm_preds = [normalize_maltese_text(p) for p in kenlm_preds]

    # --- Step 4: Calculate Metrics ---
    baseline_wer = wer(clean_ground_truths, clean_greedy_preds)
    baseline_cer = cer(clean_ground_truths, clean_greedy_preds)
    
    kenlm_wer = wer(clean_ground_truths, clean_kenlm_preds)
    kenlm_cer = cer(clean_ground_truths, clean_kenlm_preds)

    # --- Final Results Output ---
    print("\n" + "="*45)
    print(f"{'Metric':<10} | {'Raw Model':<12} | {'With KenLM':<12}")
    print("-" * 45)
    print(f"{'WER':<10} | {baseline_wer:<12.4f} | {kenlm_wer:<12.4f}")
    print(f"{'CER':<10} | {baseline_cer:<12.4f} | {kenlm_cer:<12.4f}")
    print("="*45)
    
    improvement = baseline_wer - kenlm_wer
    print(f"\nNormalized WER Improvement: {improvement:.4f}")
    
    return {"raw_wer": baseline_wer, "kenlm_wer": kenlm_wer}

Loading model from: Runs/SplitRunReduced/checkpoint-2780

In [28]:
results = evaluate_kenlm_manual(common_voice_test)

--- Step 1: Generating Logits for 1892 samples ---

100%|██████████| 1892/1892 [02:59<00:00, 10.55it/s]
Unigrams not provided and cannot be automatically determined from LM file (only arpa format). Decoding accuracy might be reduced.
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?
No known unigrams provided, decoding results might be a lot worse.

--- Step 2: Decoding with KenLM (Alpha: 0.85, Beta: 4.0) ---

=============================================
Metric     | Raw Model    | With KenLM
---------------------------------------------
WER        | 0.1833       | 0.1539
CER        | 0.0579       | 0.0582
=============================================

Normalized WER Improvement: 0.0294


## Scaling-up the training

We've shown in this blogpost how Meta's `w2v-bert-2.0` fine-tuning can give near state-of-the-art performance on low-resource languages.

To take things a step further, I've put together a set of tips and pointers given by my colleagues at Hugging Face on how to scale up training for this model. Many thanks to [Patrick](https://huggingface.co/patrickvonplaten), [Sanchit](https://huggingface.co/sanchit-gandhi) and [Pablo](https://huggingface.co/Molbap) for their valuable expertise and help 🤗

Note that Common Voice newest version ([CV16](https://huggingface.co/datasets/mozilla-foundation/common_voice_16_0)) provides many more hours of data and for may languages and thus provides fertile ground for much more efficient models in many low-resource languages.


### Datasets-related tips

CTC ASR is typically done with lower-case, un-punctuated transcriptions. This simplifies the CTC task since the model is considered as "acoustic only", meaning that it makes prediction largely based on the phonetics sounds of the audio, rather than any language modelling context of the spoken sentence.

Very low-frequency characters can significantly affect loss during learning by causing loss spikes via erroneous targets. By default, the CTC tokenizer created in this blog post would add them to the vocabulary even if their frequency is negligible compared to more frequent characters. We can treat these characters as "errors" in the dataset annotation, so that they can be removed from the vocabulary, and simply classified as `"[UNK]"` during training.

It is therefore absolutely necessary to recheck the tokenizer vocabulary and remove all low-frequency characters, in much the same way as we removed Latin characters when creating the tokenizer.

Note that the Common Voice dataset is particularly prone to such "wrong" characters, for example characters from other languages (阪).

### Training-related tips

**Average duration seen by each CTC token:** According to the advice of my colleagues, the ideal ratio of duration seen per CTC token is 10 to 35 ms. In other words, to be able to learn and predict correctly, the duration of the acoustic information a CTC token needs to see should be neither too low nor too high. In fact, it should more or less correspond to a fraction of the time it takes us humans to pronounce a phoneme.

This is something that came to light when I started refining this new W2V2-Bert model (you can find the logs of one of my experiments [here](https://wandb.ai/ylacombe/huggingface/runs/4y8pd2gq)). I quickly noticed that the loss curve of my model was initially going nicely downwards, as expected, but at some point it started to explode.

After discussing this with my colleagues, I realized that I had been using a [basic checkpoint with no architecture changes](https://huggingface.co/facebook/w2v-bert-2.0), and that each CTC token was seeing a piece of the signal for 30 to 60 ms. Adding an adapter layer was enough to reduce the signal chunk sampling to the desired duration.


**Under-training:** After showing this blog post [training run](https://huggingface.co/hf-audio/w2v-bert-2.0-mongolian-colab-CV16.0#training-results) and another [training attempt](https://wandb.ai/ylacombe/huggingface/runs/nasaux7f?workspace=user-ylacombe) on English Common Voice (about 2.5k validated hours) to my colleagues, they pointed out that the model was severely under-trained, something that could have been spotted by looking at the loss curve, which looks like it was stopped in the middle of a steep descent. This pointed out other issues as well, notably the loss curve not being smooth enough, a sign of wrong hyper-parameters settings.

Here are a few ways to solve under-training in our case:
- the warm-up rate might be too high, causing the learning rate to drop too quickly. A way to solve this would be keep the warmup ratio to 5 to 15% and scale up the number of epochs. The warm-up steps are essential to gradually bring the new language-model head weights into alignment with the pre-trained model.
- Loss curve lack of smoothness can be played around thanks to [AdamW](https://pytorch.org/docs/stable/generated/torch.optim.AdamW.html)'s [\\( \beta_2 \\)](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.adam_beta2) which can typically set from 0.95 to 0.98 by default.




*Related posts and additional links are listed here:*
- [**Official paper**](https://huggingface.co/papers/2305.13516)
- [**Original cobebase**](https://ai.meta.com/research/publications/seamless-multilingual-expressive-and-streaming-speech-translation/)
- [**Transformers Docs**](https://huggingface.co/docs/transformers/main/en/model_doc/wav2vec2-bert)
- [**Related XLS-R blog post**](https://huggingface.co/blog/fine-tune-xlsr-wav2vec2)
- [**Related MMS blog post**](https://huggingface.co/blog/mms_adapters)

In [ ]:
import torch
import time
import pandas as pd
from pathlib import Path
from transformers import Wav2Vec2BertForCTC, Wav2Vec2BertProcessor
from pyctcdecode import build_ctcdecoder
from jiwer import wer, cer, process_words
from tqdm import tqdm

# =====================================================================
# 1. Setup Paths & Device
# =====================================================================
base_path = Path(".") 
my_model_path = base_path / "Runs" / "checkpoint-5690"
LM_PATH = str(base_path / "3_untok_red.bin")
ARPA_PATH = str(base_path / "3_untok_red.arpa") 

device = "cuda" if torch.cuda.is_available() else "cpu"

# =====================================================================
# 2. Load Model, Processor, and Vocab
# =====================================================================
print("Loading model and processor...")
model = Wav2Vec2BertForCTC.from_pretrained(my_model_path).to(device)
processor = Wav2Vec2BertProcessor.from_pretrained(my_model_path)
model.eval()

vocab = processor.tokenizer.get_vocab()
sorted_vocab = [k for k, v in sorted(vocab.items(), key=lambda item: item[1])]

# =====================================================================
# 3. Extract Unigrams from ARPA
# =====================================================================
def get_unigram_list(arpa_path):
    unigrams = []
    with open(arpa_path, "r") as f:
        is_unigram_section = False
        for line in f:
            if "\\1-grams:" in line:
                is_unigram_section = True
                continue
            if "\\2-grams:" in line or line.startswith("\\end\\"):
                break
            if is_unigram_section:
                parts = line.strip().split()
                if len(parts) >= 2:
                    word = parts[1]
                    if word not in ["<s>", "</s>", "<unk>"]:
                        unigrams.append(word)
    return unigrams

print("Extracting unigrams...")
unigrams = get_unigram_list(ARPA_PATH)

# =====================================================================
# 4. Evaluation Function with Granular Logging
# =====================================================================
def evaluate_kenlm_manual_with_logging(dataset, alpha=0.85, beta=4.0, output_csv="asr_evaluation_big_model.csv"):
    all_logits_numpy = []
    all_ground_truths = []
    greedy_preds = []
    ids = []

    # --- Step 1: Generate Logits & Greedy Predictions ---
    print(f"\n--- Step 1: Generating Logits for {len(dataset)} samples ---")
    
    # New lists to keep track of metadata
    filenames = []
    domains = []
    
    for i in tqdm(range(len(dataset))):
        batch = dataset[i]
        audio = batch["audio"]["array"] 
        
        # Pull metadata straight from your loaded dataset schema
        fname = batch.get("sentence_id", f"unknown_{i}")
        domain = batch.get("sentence_domain", "unknown")
        
        filenames.append(fname)
        domains.append(domain)
        
        inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
        input_features = inputs.input_features.to(device)

        with torch.no_grad():
            logits = model(input_features).logits
        
        all_logits_numpy.append(logits.cpu().numpy()[0])
        all_ground_truths.append(batch["sentence"].lower())
        
        pred_ids = torch.argmax(logits, dim=-1)
        greedy_preds.append(processor.batch_decode(pred_ids)[0].lower())

    # --- Step 2: Decode with KenLM ---
    print(f"\n--- Step 2: Decoding with KenLM (Alpha: {alpha}, Beta: {beta}) ---")
    
    decoder = build_ctcdecoder(
        labels=sorted_vocab,
        kenlm_model_path=LM_PATH,
        unigrams=unigrams, 
        alpha=alpha,
        beta=beta
    )
    
    kenlm_preds = [decoder.decode(l).lower() for l in all_logits_numpy]

    # --- Step 3: Compute Breakdown Metrics & Compile Rows ---
    print("\n--- Step 3: Computing error alignments and saving dataset ---")
    rows = []
    
    # Added 'fname' and 'domain' to the zip statement
    for fname, domain, gt, greedy, kenlm in zip(filenames, domains, all_ground_truths, greedy_preds, kenlm_preds):
        
        if gt.strip():
            g_wer = wer(gt, greedy)
            g_cer = cer(gt, greedy)
            k_wer = wer(gt, kenlm)
            k_cer = cer(gt, kenlm)
            
            greedy_align = process_words(gt, greedy)
            kenlm_align = process_words(gt, kenlm)
            
            g_sub, g_ins, g_del = greedy_align.substitutions, greedy_align.insertions, greedy_align.deletions
            k_sub, k_ins, k_del = kenlm_align.substitutions, kenlm_align.insertions, kenlm_align.deletions
        else:
            g_wer, g_cer, k_wer, k_cer = 0.0, 0.0, 0.0, 0.0
            g_sub, g_ins, g_del = 0, 0, 0
            k_sub, k_ins, k_del = 0, 0, 0

        rows.append({
            # --- Brand New Metadata Columns ---
            "source_domain": domain,        # e.g., 'MASRI' or 'CommonVoice'
            "filename": fname,              # e.g., 'audio_sample_123.wav'
            
            "ground_truth": gt,
            "greedy_pred": greedy,
            "kenlm_pred": kenlm,
            
            # Error Rates
            "greedy_wer": g_wer,
            "greedy_cer": g_cer,
            "kenlm_wer": k_wer,
            "kenlm_cer": k_cer,
            
            # Improvement Delta
            "wer_improvement": g_wer - k_wer,
            "cer_improvement": g_cer - k_cer,
            
            # Baseline Error Breakdown
            "greedy_substitutions": g_sub, 
            "greedy_insertions": g_ins,    
            "greedy_deletions": g_del,
            
            # KenLM Error Breakdown
            "kenlm_substitutions": k_sub, 
            "kenlm_insertions": k_ins,    
            "kenlm_deletions": k_del     
        })

    # Convert to DataFrame and export
    df = pd.DataFrame(rows)
    df.to_csv(output_csv, index=False)
    print(f"🎉 Analysis file saved successfully to: {output_csv}")

    # Dataset-wide global summary metrics for quick CLI reference
    global_baseline_wer = wer(all_ground_truths, greedy_preds)
    global_kenlm_wer = wer(all_ground_truths, kenlm_preds)
    
    print("\n" + "="*45)
    print(f"{'Global Metric':<15} | {'Raw Model':<12} | {'With KenLM':<12}")
    print("-" * 45)
    print(f"{'WER':<15} | {global_baseline_wer:<12.4f} | {global_kenlm_wer:<12.4f}")
    print("="*45)
    print(f"Overall Delta: {global_baseline_wer - global_kenlm_wer:.4f}\n")
    
    return df

# =====================================================================
# 5. Execution Example
# =====================================================================
if __name__ == "__main__":
    # Assuming 'eval_dataset' is your dataset object loaded from Hugging Face or custom script
    # df_results = evaluate_kenlm_manual_with_logging(eval_dataset, alpha=0.85, beta=4.0)
    pass

Loading model and processor...
Extracting unigrams...

In [20]:
import torch
import time
import pandas as pd
from pathlib import Path
from transformers import Wav2Vec2BertForCTC, Wav2Vec2BertProcessor
from pyctcdecode import build_ctcdecoder
from jiwer import wer, cer, process_words
from tqdm import tqdm
import malti.tokeniser  # Imported for Maltese detokenization

# =====================================================================
# 1. Setup Paths & Device
# =====================================================================
base_path = Path(".") 
my_model_path = base_path / "Runs" / "SplitRunReducedButMid" / "checkpoint-2780"
LM_PATH = str(base_path / "3_tok_red.bin")
ARPA_PATH = str(base_path / "3_tok_red.arpa") 

device = "cuda" if torch.cuda.is_available() else "cpu"

# Initialize Maltese Detokenizer globally
malti_tokenizer = malti.tokeniser.KMTokeniser()

# =====================================================================
# 2. Load Model, Processor, and Vocab
# =====================================================================
print("Loading model and processor...")
model = Wav2Vec2BertForCTC.from_pretrained(my_model_path).to(device)
processor = Wav2Vec2BertProcessor.from_pretrained(my_model_path)
model.eval()

vocab = processor.tokenizer.get_vocab()
sorted_vocab = [k for k, v in sorted(vocab.items(), key=lambda item: item[1])]

# =====================================================================
# 3. Extract Unigrams from ARPA
# =====================================================================
def get_unigram_list(arpa_path):
    unigrams = []
    with open(arpa_path, "r") as f:
        is_unigram_section = False
        for line in f:
            if "\\1-grams:" in line:
                is_unigram_section = True
                continue
            if "\\2-grams:" in line or line.startswith("\\end\\"):
                break
            if is_unigram_section:
                parts = line.strip().split()
                if len(parts) >= 2:
                    word = parts[1]
                    if word not in ["<s>", "</s>", "<unk>"]:
                        unigrams.append(word)
    return unigrams

print("Extracting unigrams...")
unigrams = get_unigram_list(ARPA_PATH)

# =====================================================================
# 4. Evaluation Function with Granular Logging & Detokenization
# =====================================================================
def evaluate_kenlm_manual_with_logging(dataset, alpha=0.85, beta=4.0, output_csv="asr_evaluation_small_model.csv"):
    all_logits_numpy = []
    all_ground_truths = []
    greedy_preds = []
    filenames = []
    domains = []

    # --- Step 1: Generate Logits & Greedy Predictions ---
    print(f"\n--- Step 1: Generating Logits for {len(dataset)} samples ---")
    
    for i in tqdm(range(len(dataset))):
        batch = dataset[i]
        audio = batch["audio"]["array"] 
        
        # Pull metadata
        fname = batch.get("sentence_id", f"unknown_{i}")
        domain = batch.get("sentence_domain", "unknown")
        
        filenames.append(fname)
        domains.append(domain)
        
        inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
        input_features = inputs.input_features.to(device)

        with torch.no_grad():
            logits = model(input_features).logits
        
        all_logits_numpy.append(logits.cpu().numpy()[0])
        
        # 1. Process Raw Greedy Output
        pred_ids = torch.argmax(logits, dim=-1)
        raw_greedy = processor.batch_decode(pred_ids)[0].lower()
        
        # 2. Process Raw Reference
        raw_reference = batch["sentence"].lower()
        
        # --- Detokenization Step ---
        detok_ref = malti_tokenizer.detokenise(raw_reference.split())
        detok_greedy = malti_tokenizer.detokenise(raw_greedy.split())
        
        all_ground_truths.append(detok_ref)
        greedy_preds.append(detok_greedy)

    # --- Step 2: Decode with KenLM & Detokenize ---
    print(f"\n--- Step 2: Decoding with KenLM (Alpha: {alpha}, Beta: {beta}) ---")
    
    decoder = build_ctcdecoder(
        labels=sorted_vocab,
        kenlm_model_path=LM_PATH,
        unigrams=unigrams, 
        alpha=alpha,
        beta=beta
    )
    
    kenlm_preds = []
    for l in all_logits_numpy:
        raw_kenlm = decoder.decode(l).lower()
        # Detokenize the KenLM output string
        detok_kenlm = malti_tokenizer.detokenise(raw_kenlm.split())
        kenlm_preds.append(detok_kenlm)

    # --- Step 3: Compute Breakdown Metrics & Compile Rows ---
    print("\n--- Step 3: Computing error alignments and saving dataset ---")
    rows = []
    
    for fname, domain, gt, greedy, kenlm in zip(filenames, domains, all_ground_truths, greedy_preds, kenlm_preds):
        
        if gt.strip():
            g_wer = wer(gt, greedy)
            g_cer = cer(gt, greedy)
            k_wer = wer(gt, kenlm)
            k_cer = cer(gt, kenlm)
            
            greedy_align = process_words(gt, greedy)
            kenlm_align = process_words(gt, kenlm)
            
            g_sub, g_ins, g_del = greedy_align.substitutions, greedy_align.insertions, greedy_align.deletions
            k_sub, k_ins, k_del = kenlm_align.substitutions, kenlm_align.insertions, kenlm_align.deletions
        else:
            g_wer, g_cer, k_wer, k_cer = 0.0, 0.0, 0.0, 0.0
            g_sub, g_ins, g_del = 0, 0, 0
            k_sub, k_ins, k_del = 0, 0, 0

        rows.append({
            "source_domain": domain,        
            "filename": fname,              
            
            "ground_truth": gt,
            "greedy_pred": greedy,
            "kenlm_pred": kenlm,
            
            # Error Rates (Calculated on Fair Detokenized text)
            "greedy_wer": g_wer,
            "greedy_cer": g_cer,
            "kenlm_wer": k_wer,
            "kenlm_cer": k_cer,
            
            # Improvement Delta
            "wer_improvement": g_wer - k_wer,
            "cer_improvement": g_cer - k_cer,
            
            # Baseline Error Breakdown
            "greedy_substitutions": g_sub, 
            "greedy_insertions": g_ins,    
            "greedy_deletions": g_del,
            
            # KenLM Error Breakdown
            "kenlm_substitutions": k_sub, 
            "kenlm_insertions": k_ins,    
            "kenlm_deletions": k_del     
        })

    # Convert to DataFrame and export
    df = pd.DataFrame(rows)
    df.to_csv(output_csv, index=False)
    print(f"🎉 Analysis file saved successfully to: {output_csv}")

    # Dataset-wide global summary metrics (Fair Evaluation)
    global_baseline_wer = wer(all_ground_truths, greedy_preds)
    global_baseline_cer = cer(all_ground_truths, greedy_preds)
    global_kenlm_wer = wer(all_ground_truths, kenlm_preds)
    global_kenlm_cer = cer(all_ground_truths, kenlm_preds)
    
    print("\n" + "="*50)
    print(f"{'Global Metric (Detok)':<20} | {'Raw Model':<12} | {'With KenLM':<12}")
    print("-" * 50)
    print(f"{'WER':<20} | {global_baseline_wer:<12.4f} | {global_kenlm_wer:<12.4f}")
    print(f"{'CER':<20} | {global_baseline_cer:<12.4f} | {global_kenlm_cer:<12.4f}")
    print("="*50)
    print(f"Overall WER Delta: {global_baseline_wer - global_kenlm_wer:.4f}\n")
    
    return df

# =====================================================================
# 5. Execution Example
# =====================================================================
if __name__ == "__main__":
    # Assuming 'eval_dataset' is your dataset object loaded from Hugging Face or custom script
    # df_results = evaluate_kenlm_manual_with_logging(eval_dataset, alpha=0.85, beta=4.0)
    pass

Loading model and processor...
Extracting unigrams...

In [21]:
results = evaluate_kenlm_manual_with_logging(common_voice_dev, alpha=0.7, beta=3.0)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [03:39<00:00,  8.60it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Step 2: Decoding with KenLM (Alpha: 0.7, Beta: 3.0) ---

--- Step 3: Computing error alignments and saving dataset ---
🎉 Analysis file saved successfully to: asr_evaluation_small_model.csv

==================================================
Global Metric (Detok) | Raw Model    | With KenLM
--------------------------------------------------
WER                  | 0.1989       | 0.1526
CER                  | 0.0516       | 0.0478
==================================================
Overall WER Delta: 0.0463

In [19]:
results = evaluate_kenlm_manual_with_logging(common_voice_dev, alpha=0.5, beta=3.0)

--- Step 1: Generating Logits for 1883 samples ---

100%|██████████| 1883/1883 [02:59<00:00, 10.48it/s]
Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

--- Step 2: Decoding with KenLM (Alpha: 0.5, Beta: 3.0) ---

--- Step 3: Computing error alignments and saving dataset ---
🎉 Analysis file saved successfully to: asr_evaluation_big_model.csv

=============================================
Global Metric   | Raw Model    | With KenLM
---------------------------------------------
WER             | 0.1237       | 0.1064
=============================================
Overall Delta: 0.0173